<?php

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/bank.jce'
// **********************************************************************


require_once('jce.php');
class TReqCaifutongBatchPay extends c_struct
{
    public $uid;
    public $strName;
    public $cid;
    public $dValue;
    public $banktype;
    public $area;
    public $city;
    public $subbankname;
    public $username;
    public $usercard;
    public $bankaccount;
    public $desc;
    public $recmobile;
    public $acctype;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->strName = clone $this->strName;
        $this->cid = clone $this->cid;
        $this->dValue = clone $this->dValue;
        $this->banktype = clone $this->banktype;
        $this->area = clone $this->area;
        $this->city = clone $this->city;
        $this->subbankname = clone $this->subbankname;
        $this->username = clone $this->username;
        $this->usercard = clone $this->usercard;
        $this->bankaccount = clone $this->bankaccount;
        $this->desc = clone $this->desc;
        $this->recmobile = clone $this->recmobile;
        $this->acctype = clone $this->acctype;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->strName = new  c_string;
        $this->cid = new  c_int;
        $this->dValue = new  c_int;
        $this->banktype = new  c_string;
        $this->area = new  c_string;
        $this->city = new  c_string;
        $this->subbankname = new  c_string;
        $this->username = new  c_string;
        $this->usercard = new  c_string;
        $this->bankaccount = new  c_string;
        $this->desc = new  c_string;
        $this->recmobile = new  c_string;
        $this->acctype = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqCaifutongBatchPay";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->strName->write($_out,1);
        $this->cid->write($_out,2);
        $this->dValue->write($_out,3);
        $this->banktype->write($_out,4);
        $this->area->write($_out,5);
        $this->city->write($_out,6);
        $this->subbankname->write($_out,7);
        $this->username->write($_out,8);
        $this->usercard->write($_out,9);
        $this->bankaccount->write($_out,10);
        $this->desc->write($_out,11);
        $this->recmobile->write($_out,12);
        $this->acctype->write($_out,13);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->strName->read($_in , 1, true);
        $this->cid->read($_in , 2, true);
        $this->dValue->read($_in , 3, true);
        $this->banktype->read($_in , 4, true);
        $this->area->read($_in , 5, true);
        $this->city->read($_in , 6, true);
        $this->subbankname->read($_in , 7, true);
        $this->username->read($_in , 8, true);
        $this->usercard->read($_in , 9, true);
        $this->bankaccount->read($_in , 10, true);
        $this->desc->read($_in , 11, true);
        $this->recmobile->read($_in , 12, true);
        $this->acctype->read($_in , 13, true);
    }
}

class TReqWeiXiUnifiedOrder extends c_struct
{
    public $body;
    public $total_fee;
    public $spbill_create_ip;
    public $product_id;
    public $out_trade_no;

    public function __clone()
    {
        $this->body = clone $this->body;
        $this->total_fee = clone $this->total_fee;
        $this->spbill_create_ip = clone $this->spbill_create_ip;
        $this->product_id = clone $this->product_id;
        $this->out_trade_no = clone $this->out_trade_no;
    }

    public function __construct()
    {
        $this->body = new  c_string;
        $this->total_fee = new  c_int;
        $this->spbill_create_ip = new  c_string;
        $this->product_id = new  c_string;
        $this->out_trade_no = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqWeiXiUnifiedOrder";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->body->write($_out,0);
        $this->total_fee->write($_out,1);
        $this->spbill_create_ip->write($_out,2);
        $this->product_id->write($_out,3);
        $this->out_trade_no->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->body->read($_in , 0, true);
        $this->total_fee->read($_in , 1, true);
        $this->spbill_create_ip->read($_in , 2, true);
        $this->product_id->read($_in , 3, true);
        $this->out_trade_no->read($_in , 4, true);
    }
}

class TRespWeiXiUnifiedOrder extends c_struct
{
    public $result_code;
    public $err_code;
    public $err_code_des;
    public $prepay_id;
    public $out_trade_no;

    public function __clone()
    {
        $this->result_code = clone $this->result_code;
        $this->err_code = clone $this->err_code;
        $this->err_code_des = clone $this->err_code_des;
        $this->prepay_id = clone $this->prepay_id;
        $this->out_trade_no = clone $this->out_trade_no;
    }

    public function __construct()
    {
        $this->result_code = new  c_string;
        $this->err_code = new  c_string;
        $this->err_code_des = new  c_string;
        $this->prepay_id = new  c_string;
        $this->out_trade_no = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespWeiXiUnifiedOrder";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->result_code->write($_out,0);
        $this->err_code->write($_out,1);
        $this->err_code_des->write($_out,2);
        $this->prepay_id->write($_out,3);
        $this->out_trade_no->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->result_code->read($_in , 0, true);
        $this->err_code->read($_in , 1, true);
        $this->err_code_des->read($_in , 2, true);
        $this->prepay_id->read($_in , 3, true);
        $this->out_trade_no->read($_in , 4, true);
    }
}

class TReqWeiXiNotifyResult extends c_struct
{
    public $appid;
    public $mch_id;
    public $nonce_str;
    public $sign;
    public $result_code;
    public $openid;
    public $trade_type;
    public $bank_type;
    public $total_fee;
    public $cash_fee;
    public $transaction_id;
    public $out_trade_no;
    public $time_end;

    public function __clone()
    {
        $this->appid = clone $this->appid;
        $this->mch_id = clone $this->mch_id;
        $this->nonce_str = clone $this->nonce_str;
        $this->sign = clone $this->sign;
        $this->result_code = clone $this->result_code;
        $this->openid = clone $this->openid;
        $this->trade_type = clone $this->trade_type;
        $this->bank_type = clone $this->bank_type;
        $this->total_fee = clone $this->total_fee;
        $this->cash_fee = clone $this->cash_fee;
        $this->transaction_id = clone $this->transaction_id;
        $this->out_trade_no = clone $this->out_trade_no;
        $this->time_end = clone $this->time_end;
    }

    public function __construct()
    {
        $this->appid = new  c_string;
        $this->mch_id = new  c_string;
        $this->nonce_str = new  c_string;
        $this->sign = new  c_string;
        $this->result_code = new  c_string;
        $this->openid = new  c_string;
        $this->trade_type = new  c_string;
        $this->bank_type = new  c_string;
        $this->total_fee = new  c_string;
        $this->cash_fee = new  c_string;
        $this->transaction_id = new  c_string;
        $this->out_trade_no = new  c_string;
        $this->time_end = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqWeiXiNotifyResult";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->appid->write($_out,0);
        $this->mch_id->write($_out,1);
        $this->nonce_str->write($_out,2);
        $this->sign->write($_out,3);
        $this->result_code->write($_out,4);
        $this->openid->write($_out,5);
        $this->trade_type->write($_out,6);
        $this->bank_type->write($_out,7);
        $this->total_fee->write($_out,8);
        $this->cash_fee->write($_out,9);
        $this->transaction_id->write($_out,10);
        $this->out_trade_no->write($_out,11);
        $this->time_end->write($_out,12);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->appid->read($_in , 0, true);
        $this->mch_id->read($_in , 1, true);
        $this->nonce_str->read($_in , 2, true);
        $this->sign->read($_in , 3, true);
        $this->result_code->read($_in , 4, true);
        $this->openid->read($_in , 5, true);
        $this->trade_type->read($_in , 6, true);
        $this->bank_type->read($_in , 7, true);
        $this->total_fee->read($_in , 8, true);
        $this->cash_fee->read($_in , 9, true);
        $this->transaction_id->read($_in , 10, true);
        $this->out_trade_no->read($_in , 11, true);
        $this->time_end->read($_in , 12, true);
    }
}

class TReqWeiXiQueryOrder extends c_struct
{
    public $transaction_id;
    public $out_trade_no;

    public function __clone()
    {
        $this->transaction_id = clone $this->transaction_id;
        $this->out_trade_no = clone $this->out_trade_no;
    }

    public function __construct()
    {
        $this->transaction_id = new  c_string;
        $this->out_trade_no = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqWeiXiQueryOrder";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->transaction_id->write($_out,0);
        $this->out_trade_no->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->transaction_id->read($_in , 0, true);
        $this->out_trade_no->read($_in , 1, false);
    }
}

class TRespWeiXiQueryOrder extends c_struct
{
    public $result_code;
    public $trade_type;
    public $trade_state;
    public $bank_type;
    public $total_fee;
    public $transaction_id;
    public $out_trade_no;
    public $time_end;
    public $trade_state_desc;

    public function __clone()
    {
        $this->result_code = clone $this->result_code;
        $this->trade_type = clone $this->trade_type;
        $this->trade_state = clone $this->trade_state;
        $this->bank_type = clone $this->bank_type;
        $this->total_fee = clone $this->total_fee;
        $this->transaction_id = clone $this->transaction_id;
        $this->out_trade_no = clone $this->out_trade_no;
        $this->time_end = clone $this->time_end;
        $this->trade_state_desc = clone $this->trade_state_desc;
    }

    public function __construct()
    {
        $this->result_code = new  c_string;
        $this->trade_type = new  c_string;
        $this->trade_state = new  c_string;
        $this->bank_type = new  c_string;
        $this->total_fee = new  c_int;
        $this->transaction_id = new  c_string;
        $this->out_trade_no = new  c_string;
        $this->time_end = new  c_string;
        $this->trade_state_desc = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespWeiXiQueryOrder";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->result_code->write($_out,0);
        $this->trade_type->write($_out,1);
        $this->trade_state->write($_out,2);
        $this->bank_type->write($_out,3);
        $this->total_fee->write($_out,4);
        $this->transaction_id->write($_out,5);
        $this->out_trade_no->write($_out,6);
        $this->time_end->write($_out,7);
        $this->trade_state_desc->write($_out,8);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->result_code->read($_in , 0, true);
        $this->trade_type->read($_in , 1, true);
        $this->trade_state->read($_in , 2, true);
        $this->bank_type->read($_in , 3, true);
        $this->total_fee->read($_in , 4, true);
        $this->transaction_id->read($_in , 5, true);
        $this->out_trade_no->read($_in , 6, true);
        $this->time_end->read($_in , 7, true);
        $this->trade_state_desc->read($_in , 8, true);
    }
}

class TReqWeiXiCloseOrder extends c_struct
{
    public $out_trade_no;

    public function __clone()
    {
        $this->out_trade_no = clone $this->out_trade_no;
    }

    public function __construct()
    {
        $this->out_trade_no = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqWeiXiCloseOrder";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->out_trade_no->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->out_trade_no->read($_in , 0, false);
    }
}

class TRespWeiXiCloseOrder extends c_struct
{
    public $return_code;
    public $out_trade_no;

    public function __clone()
    {
        $this->return_code = clone $this->return_code;
        $this->out_trade_no = clone $this->out_trade_no;
    }

    public function __construct()
    {
        $this->return_code = new  c_string;
        $this->out_trade_no = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespWeiXiCloseOrder";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->return_code->write($_out,0);
        $this->out_trade_no->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->return_code->read($_in , 0, true);
        $this->out_trade_no->read($_in , 1, true);
    }
}

class TReqWeiXiRefundOrder extends c_struct
{
    public $transaction_id;
    public $out_trade_no;
    public $out_refund_no;
    public $total_fee;
    public $refund_fee;

    public function __clone()
    {
        $this->transaction_id = clone $this->transaction_id;
        $this->out_trade_no = clone $this->out_trade_no;
        $this->out_refund_no = clone $this->out_refund_no;
        $this->total_fee = clone $this->total_fee;
        $this->refund_fee = clone $this->refund_fee;
    }

    public function __construct()
    {
        $this->transaction_id = new  c_string;
        $this->out_trade_no = new  c_string;
        $this->out_refund_no = new  c_string;
        $this->total_fee = new  c_int;
        $this->refund_fee = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqWeiXiRefundOrder";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->transaction_id->write($_out,0);
        $this->out_trade_no->write($_out,1);
        $this->out_refund_no->write($_out,2);
        $this->total_fee->write($_out,3);
        $this->refund_fee->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->transaction_id->read($_in , 0, false);
        $this->out_trade_no->read($_in , 1, true);
        $this->out_refund_no->read($_in , 2, true);
        $this->total_fee->read($_in , 3, true);
        $this->refund_fee->read($_in , 4, true);
    }
}

class TRespWeiXiRefundOrder extends c_struct
{
    public $result_code;
    public $transaction_id;
    public $out_trade_no;
    public $out_refund_no;
    public $refund_id;
    public $refund_channel;
    public $refund_fee;
    public $total_fee;

    public function __clone()
    {
        $this->result_code = clone $this->result_code;
        $this->transaction_id = clone $this->transaction_id;
        $this->out_trade_no = clone $this->out_trade_no;
        $this->out_refund_no = clone $this->out_refund_no;
        $this->refund_id = clone $this->refund_id;
        $this->refund_channel = clone $this->refund_channel;
        $this->refund_fee = clone $this->refund_fee;
        $this->total_fee = clone $this->total_fee;
    }

    public function __construct()
    {
        $this->result_code = new  c_string;
        $this->transaction_id = new  c_string;
        $this->out_trade_no = new  c_string;
        $this->out_refund_no = new  c_string;
        $this->refund_id = new  c_string;
        $this->refund_channel = new  c_string;
        $this->refund_fee = new  c_int;
        $this->total_fee = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespWeiXiRefundOrder";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->result_code->write($_out,0);
        $this->transaction_id->write($_out,1);
        $this->out_trade_no->write($_out,2);
        $this->out_refund_no->write($_out,3);
        $this->refund_id->write($_out,4);
        $this->refund_channel->write($_out,5);
        $this->refund_fee->write($_out,6);
        $this->total_fee->write($_out,7);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->result_code->read($_in , 0, true);
        $this->transaction_id->read($_in , 1, true);
        $this->out_trade_no->read($_in , 2, true);
        $this->out_refund_no->read($_in , 3, true);
        $this->refund_id->read($_in , 4, true);
        $this->refund_channel->read($_in , 5, true);
        $this->refund_fee->read($_in , 6, true);
        $this->total_fee->read($_in , 7, true);
    }
}

class TReqAlipayNotifyResult extends c_struct
{
    public $notify_time;
    public $notify_type;
    public $notify_id;
    public $sign_type;
    public $sign;
    public $out_trade_no;
    public $subject;
    public $payment_type;
    public $trade_no;
    public $trade_status;
    public $seller_id;
    public $seller_email;
    public $buyer_id;
    public $buyer_email;
    public $total_fee;
    public $quantity;
    public $price;
    public $body;
    public $gmt_create;
    public $gmt_payment;
    public $is_total_fee_adjust;
    public $use_coupon;
    public $discount;
    public $refund_status;
    public $gmt_refund;

    public function __clone()
    {
        $this->notify_time = clone $this->notify_time;
        $this->notify_type = clone $this->notify_type;
        $this->notify_id = clone $this->notify_id;
        $this->sign_type = clone $this->sign_type;
        $this->sign = clone $this->sign;
        $this->out_trade_no = clone $this->out_trade_no;
        $this->subject = clone $this->subject;
        $this->payment_type = clone $this->payment_type;
        $this->trade_no = clone $this->trade_no;
        $this->trade_status = clone $this->trade_status;
        $this->seller_id = clone $this->seller_id;
        $this->seller_email = clone $this->seller_email;
        $this->buyer_id = clone $this->buyer_id;
        $this->buyer_email = clone $this->buyer_email;
        $this->total_fee = clone $this->total_fee;
        $this->quantity = clone $this->quantity;
        $this->price = clone $this->price;
        $this->body = clone $this->body;
        $this->gmt_create = clone $this->gmt_create;
        $this->gmt_payment = clone $this->gmt_payment;
        $this->is_total_fee_adjust = clone $this->is_total_fee_adjust;
        $this->use_coupon = clone $this->use_coupon;
        $this->discount = clone $this->discount;
        $this->refund_status = clone $this->refund_status;
        $this->gmt_refund = clone $this->gmt_refund;
    }

    public function __construct()
    {
        $this->notify_time = new  c_string;
        $this->notify_type = new  c_string;
        $this->notify_id = new  c_string;
        $this->sign_type = new  c_string;
        $this->sign = new  c_string;
        $this->out_trade_no = new  c_string;
        $this->subject = new  c_string;
        $this->payment_type = new  c_string;
        $this->trade_no = new  c_string;
        $this->trade_status = new  c_string;
        $this->seller_id = new  c_string;
        $this->seller_email = new  c_string;
        $this->buyer_id = new  c_string;
        $this->buyer_email = new  c_string;
        $this->total_fee = new  c_string;
        $this->quantity = new  c_string;
        $this->price = new  c_string;
        $this->body = new  c_string;
        $this->gmt_create = new  c_string;
        $this->gmt_payment = new  c_string;
        $this->is_total_fee_adjust = new  c_string;
        $this->use_coupon = new  c_string;
        $this->discount = new  c_string;
        $this->refund_status = new  c_string;
        $this->gmt_refund = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqAlipayNotifyResult";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->notify_time->write($_out,0);
        $this->notify_type->write($_out,1);
        $this->notify_id->write($_out,2);
        $this->sign_type->write($_out,3);
        $this->sign->write($_out,4);
        $this->out_trade_no->write($_out,5);
        $this->subject->write($_out,6);
        $this->payment_type->write($_out,7);
        $this->trade_no->write($_out,8);
        $this->trade_status->write($_out,9);
        $this->seller_id->write($_out,10);
        $this->seller_email->write($_out,11);
        $this->buyer_id->write($_out,12);
        $this->buyer_email->write($_out,13);
        $this->total_fee->write($_out,14);
        $this->quantity->write($_out,15);
        $this->price->write($_out,16);
        $this->body->write($_out,17);
        $this->gmt_create->write($_out,18);
        $this->gmt_payment->write($_out,19);
        $this->is_total_fee_adjust->write($_out,20);
        $this->use_coupon->write($_out,21);
        $this->discount->write($_out,22);
        $this->refund_status->write($_out,23);
        $this->gmt_refund->write($_out,24);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->notify_time->read($_in , 0, true);
        $this->notify_type->read($_in , 1, true);
        $this->notify_id->read($_in , 2, true);
        $this->sign_type->read($_in , 3, true);
        $this->sign->read($_in , 4, true);
        $this->out_trade_no->read($_in , 5, true);
        $this->subject->read($_in , 6, true);
        $this->payment_type->read($_in , 7, true);
        $this->trade_no->read($_in , 8, true);
        $this->trade_status->read($_in , 9, true);
        $this->seller_id->read($_in , 10, true);
        $this->seller_email->read($_in , 11, true);
        $this->buyer_id->read($_in , 12, true);
        $this->buyer_email->read($_in , 13, true);
        $this->total_fee->read($_in , 14, true);
        $this->quantity->read($_in , 15, true);
        $this->price->read($_in , 16, true);
        $this->body->read($_in , 17, true);
        $this->gmt_create->read($_in , 18, true);
        $this->gmt_payment->read($_in , 19, true);
        $this->is_total_fee_adjust->read($_in , 20, true);
        $this->use_coupon->read($_in , 21, true);
        $this->discount->read($_in , 22, true);
        $this->refund_status->read($_in , 23, true);
        $this->gmt_refund->read($_in , 24, true);
    }
}


?>