<?php

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Bean.jce'
// **********************************************************************


require_once('jce.php');
class TReqBeanOperation extends c_struct
{
    public $uid;
    public $identity;
    public $iRuleId;
    public $number;
    public $clientType;
    public $transformBean;
    public $consumeBean;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->identity = clone $this->identity;
        $this->iRuleId = clone $this->iRuleId;
        $this->number = clone $this->number;
        $this->clientType = clone $this->clientType;
        $this->transformBean = clone $this->transformBean;
        $this->consumeBean = clone $this->consumeBean;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->identity = new  c_int;
        $this->iRuleId = new  c_int;
        $this->number = new  c_int;
        $this->clientType = new  c_int;
        $this->transformBean = new  c_int;
        $this->consumeBean = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqBeanOperation";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->identity->write($_out,1);
        $this->iRuleId->write($_out,2);
        $this->number->write($_out,3);
        $this->clientType->write($_out,4);
        $this->transformBean->write($_out,5);
        $this->consumeBean->write($_out,6);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->identity->read($_in , 1, true);
        $this->iRuleId->read($_in , 2, true);
        $this->number->read($_in , 3, true);
        $this->clientType->read($_in , 4, true);
        $this->transformBean->read($_in , 5, false);
        $this->consumeBean->read($_in , 6, false);
    }
}

class TRespBeanOperation extends c_struct
{
    public $uid;
    public $alterBean;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->alterBean = clone $this->alterBean;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->alterBean = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespBeanOperation";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->alterBean->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->alterBean->read($_in , 1, true);
    }
}

class TReqAcquireBeanInfo extends c_struct
{
    public $uid;

    public function __clone()
    {
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqAcquireBeanInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
    }
}

class TRespAcquireBeanInfo extends c_struct
{
    public $bean;

    public function __clone()
    {
        $this->bean = clone $this->bean;
    }

    public function __construct()
    {
        $this->bean = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespAcquireBeanInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->bean->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->bean->read($_in , 0, true);
    }
}

class TBeanOperationRecord extends c_struct
{
    public $uid;
    public $iRuleId;
    public $clientType;
    public $alterBean;
    public $index;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->iRuleId = clone $this->iRuleId;
        $this->clientType = clone $this->clientType;
        $this->alterBean = clone $this->alterBean;
        $this->index = clone $this->index;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->iRuleId = new  c_int;
        $this->clientType = new  c_int;
        $this->alterBean = new  c_int;
        $this->index = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TBeanOperationRecord";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->iRuleId->write($_out,1);
        $this->clientType->write($_out,2);
        $this->alterBean->write($_out,3);
        $this->index->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->iRuleId->read($_in , 1, true);
        $this->clientType->read($_in , 2, true);
        $this->alterBean->read($_in , 3, true);
        $this->index->read($_in , 4, false);
    }
}

class TReqAcquireBeanLog extends c_struct
{
    public $uid;
    public $index;
    public $flag;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->index = clone $this->index;
        $this->flag = clone $this->flag;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->index = new  c_int;
        $this->flag = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqAcquireBeanLog";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->index->write($_out,1);
        $this->flag->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->index->read($_in , 1, true);
        $this->flag->read($_in , 2, true);
    }
}

class TRespAcquireBeanLog extends c_struct
{
    public $vBeanLog;

    public function __clone()
    {
        $this->vBeanLog = clone $this->vBeanLog;
    }

    public function __construct()
    {
        $this->vBeanLog = new  c_vector (new TBeanOperationRecord);
    }

    public function get_class_name()
    {
        return "Apollo.TRespAcquireBeanLog";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vBeanLog->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vBeanLog->read($_in , 0, true);
    }
}


?>