<?php

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************


require_once('jce.php');
class TStuctClassTeacher extends c_struct
{
    public $uid;
    public $subject;
    public $type;
    public $creationtime;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->subject = clone $this->subject;
        $this->type = clone $this->type;
        $this->creationtime = clone $this->creationtime;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->subject = new  c_string;
        $this->type = new  c_short;
        $this->creationtime = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TStuctClassTeacher";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->subject->write($_out,1);
        $this->type->write($_out,2);
        $this->creationtime->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->subject->read($_in , 1, true);
        $this->type->read($_in , 2, true);
        $this->creationtime->read($_in , 3, true);
    }
}

class TStuctClassStudent extends c_struct
{
    public $uid;
    public $creationtime;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->creationtime = clone $this->creationtime;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->creationtime = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TStuctClassStudent";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->creationtime->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->creationtime->read($_in , 1, true);
    }
}

class TStructStudentGuardian extends c_struct
{
    public $uid;
    public $role;
    public $main;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->role = clone $this->role;
        $this->main = clone $this->main;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->role = new  c_string;
        $this->main = new  c_short;
    }

    public function get_class_name()
    {
        return "Apollo.TStructStudentGuardian";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->role->write($_out,1);
        $this->main->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->role->read($_in , 1, true);
        $this->main->read($_in , 2, true);
    }
}

class TStructUserChild extends c_struct
{
    public $studentid;
    public $role;
    public $main;

    public function __clone()
    {
        $this->studentid = clone $this->studentid;
        $this->role = clone $this->role;
        $this->main = clone $this->main;
    }

    public function __construct()
    {
        $this->studentid = new  c_string;
        $this->role = new  c_string;
        $this->main = new  c_short;
    }

    public function get_class_name()
    {
        return "Apollo.TStructUserChild";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->studentid->write($_out,0);
        $this->role->write($_out,1);
        $this->main->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->studentid->read($_in , 0, true);
        $this->role->read($_in , 1, true);
        $this->main->read($_in , 2, true);
    }
}

class TStructTeacherClass extends c_struct
{
    public $cid;
    public $subject;
    public $type;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->subject = clone $this->subject;
        $this->type = clone $this->type;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->subject = new  c_string;
        $this->type = new  c_short;
    }

    public function get_class_name()
    {
        return "Apollo.TStructTeacherClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->subject->write($_out,1);
        $this->type->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->subject->read($_in , 1, true);
        $this->type->read($_in , 2, true);
    }
}

class TUserInfo extends c_struct
{
    public $uid;
    public $name;
    public $sex;
    public $mobilephone;
    public $icon;
    public $teacherauth;
    public $address;
    public $signature;
    public $issmsauth;
    public $usertype;
    public $photo;
    public $pingyin;
    public $birthday;
    public $banbanno;
    public $userdesc;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->sex = clone $this->sex;
        $this->mobilephone = clone $this->mobilephone;
        $this->icon = clone $this->icon;
        $this->teacherauth = clone $this->teacherauth;
        $this->address = clone $this->address;
        $this->signature = clone $this->signature;
        $this->issmsauth = clone $this->issmsauth;
        $this->usertype = clone $this->usertype;
        $this->photo = clone $this->photo;
        $this->pingyin = clone $this->pingyin;
        $this->birthday = clone $this->birthday;
        $this->banbanno = clone $this->banbanno;
        $this->userdesc = clone $this->userdesc;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->sex = new  c_short;
        $this->mobilephone = new  c_string;
        $this->icon = new  c_int;
        $this->teacherauth = new  c_short;
        $this->address = new  c_int;
        $this->signature = new  c_string;
        $this->issmsauth = new  c_short;
        $this->usertype = new  c_short;
        $this->photo = new  c_string;
        $this->pingyin = new  c_string;
        $this->birthday = new  c_int64;
        $this->banbanno = new  c_string;
        $this->userdesc = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TUserInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->sex->write($_out,2);
        $this->mobilephone->write($_out,3);
        $this->icon->write($_out,4);
        $this->teacherauth->write($_out,5);
        $this->address->write($_out,6);
        $this->signature->write($_out,7);
        $this->issmsauth->write($_out,8);
        $this->usertype->write($_out,9);
        $this->photo->write($_out,10);
        $this->pingyin->write($_out,11);
        $this->birthday->write($_out,12);
        $this->banbanno->write($_out,13);
        $this->userdesc->write($_out,14);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->sex->read($_in , 2, true);
        $this->mobilephone->read($_in , 3, true);
        $this->icon->read($_in , 4, true);
        $this->teacherauth->read($_in , 5, true);
        $this->address->read($_in , 6, true);
        $this->signature->read($_in , 7, true);
        $this->issmsauth->read($_in , 8, true);
        $this->usertype->read($_in , 9, true);
        $this->photo->read($_in , 10, true);
        $this->pingyin->read($_in , 11, true);
        $this->birthday->read($_in , 12, false);
        $this->banbanno->read($_in , 13, false);
        $this->userdesc->read($_in , 14, false);
    }
}

class TStructThirdAccount extends c_struct
{
    public $userfrom;
    public $threeuserid;
    public $threeusername;

    public function __clone()
    {
        $this->userfrom = clone $this->userfrom;
        $this->threeuserid = clone $this->threeuserid;
        $this->threeusername = clone $this->threeusername;
    }

    public function __construct()
    {
        $this->userfrom = new  c_int;
        $this->threeuserid = new  c_string;
        $this->threeusername = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TStructThirdAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->userfrom->write($_out,0);
        $this->threeuserid->write($_out,1);
        $this->threeusername->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->userfrom->read($_in , 0, true);
        $this->threeuserid->read($_in , 1, true);
        $this->threeusername->read($_in , 2, true);
    }
}

class TStructUserLabel extends c_struct
{
    public $id;
    public $text;

    public function __clone()
    {
        $this->id = clone $this->id;
        $this->text = clone $this->text;
    }

    public function __construct()
    {
        $this->id = new  c_int;
        $this->text = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TStructUserLabel";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->id->write($_out,0);
        $this->text->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->id->read($_in , 0, true);
        $this->text->read($_in , 1, true);
    }
}

class TClassInfo extends c_struct
{
    public $cid;
    public $name;
    public $year;
    public $sid;
    public $stid;
    public $type;
    public $master;
    public $info;
    public $creator;
    public $classcode;
    public $createtype;
    public $joinverify;
    public $grade;
    public $joinschool;
    public $pingyin;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->name = clone $this->name;
        $this->year = clone $this->year;
        $this->sid = clone $this->sid;
        $this->stid = clone $this->stid;
        $this->type = clone $this->type;
        $this->master = clone $this->master;
        $this->info = clone $this->info;
        $this->creator = clone $this->creator;
        $this->classcode = clone $this->classcode;
        $this->createtype = clone $this->createtype;
        $this->joinverify = clone $this->joinverify;
        $this->grade = clone $this->grade;
        $this->joinschool = clone $this->joinschool;
        $this->pingyin = clone $this->pingyin;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->name = new  c_string;
        $this->year = new  c_int;
        $this->sid = new  c_int;
        $this->stid = new  c_int;
        $this->type = new  c_short;
        $this->master = new  c_string;
        $this->info = new  c_string;
        $this->creator = new  c_string;
        $this->classcode = new  c_string;
        $this->createtype = new  c_short;
        $this->joinverify = new  c_short;
        $this->grade = new  c_short;
        $this->joinschool = new  c_short;
        $this->pingyin = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TClassInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->name->write($_out,1);
        $this->year->write($_out,2);
        $this->sid->write($_out,3);
        $this->stid->write($_out,4);
        $this->type->write($_out,5);
        $this->master->write($_out,6);
        $this->info->write($_out,7);
        $this->creator->write($_out,8);
        $this->classcode->write($_out,9);
        $this->createtype->write($_out,10);
        $this->joinverify->write($_out,11);
        $this->grade->write($_out,12);
        $this->joinschool->write($_out,13);
        $this->pingyin->write($_out,14);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->year->read($_in , 2, true);
        $this->sid->read($_in , 3, true);
        $this->stid->read($_in , 4, true);
        $this->type->read($_in , 5, true);
        $this->master->read($_in , 6, true);
        $this->info->read($_in , 7, true);
        $this->creator->read($_in , 8, true);
        $this->classcode->read($_in , 9, true);
        $this->createtype->read($_in , 10, true);
        $this->joinverify->read($_in , 11, true);
        $this->grade->read($_in , 12, true);
        $this->joinschool->read($_in , 13, true);
        $this->pingyin->read($_in , 14, true);
    }
}

class TSchoolInfo extends c_struct
{
    public $sid;
    public $name;
    public $aid;
    public $createtype;
    public $smsnum;
    public $schoolcode;
    public $isauth;
    public $buysms;
    public $pingyin;

    public function __clone()
    {
        $this->sid = clone $this->sid;
        $this->name = clone $this->name;
        $this->aid = clone $this->aid;
        $this->createtype = clone $this->createtype;
        $this->smsnum = clone $this->smsnum;
        $this->schoolcode = clone $this->schoolcode;
        $this->isauth = clone $this->isauth;
        $this->buysms = clone $this->buysms;
        $this->pingyin = clone $this->pingyin;
    }

    public function __construct()
    {
        $this->sid = new  c_int;
        $this->name = new  c_string;
        $this->aid = new  c_int;
        $this->createtype = new  c_short;
        $this->smsnum = new  c_int;
        $this->schoolcode = new  c_string;
        $this->isauth = new  c_short;
        $this->buysms = new  c_int;
        $this->pingyin = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TSchoolInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sid->write($_out,0);
        $this->name->write($_out,1);
        $this->aid->write($_out,2);
        $this->createtype->write($_out,3);
        $this->smsnum->write($_out,4);
        $this->schoolcode->write($_out,5);
        $this->isauth->write($_out,6);
        $this->buysms->write($_out,7);
        $this->pingyin->write($_out,8);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->aid->read($_in , 2, true);
        $this->createtype->read($_in , 3, true);
        $this->smsnum->read($_in , 4, true);
        $this->schoolcode->read($_in , 5, true);
        $this->isauth->read($_in , 6, true);
        $this->buysms->read($_in , 7, true);
        $this->pingyin->read($_in , 8, true);
    }
}

class TSchoolTypeInfo extends c_struct
{
    public $stid;
    public $name;

    public function __clone()
    {
        $this->stid = clone $this->stid;
        $this->name = clone $this->name;
    }

    public function __construct()
    {
        $this->stid = new  c_int;
        $this->name = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TSchoolTypeInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->stid->write($_out,0);
        $this->name->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->stid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
    }
}

class TAreaInfo extends c_struct
{
    public $aid;
    public $name;
    public $parentid;
    public $type;
    public $postcode;
    public $areacode;
    public $path;

    public function __clone()
    {
        $this->aid = clone $this->aid;
        $this->name = clone $this->name;
        $this->parentid = clone $this->parentid;
        $this->type = clone $this->type;
        $this->postcode = clone $this->postcode;
        $this->areacode = clone $this->areacode;
        $this->path = clone $this->path;
    }

    public function __construct()
    {
        $this->aid = new  c_int;
        $this->name = new  c_string;
        $this->parentid = new  c_int;
        $this->type = new  c_short;
        $this->postcode = new  c_string;
        $this->areacode = new  c_string;
        $this->path = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TAreaInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->aid->write($_out,0);
        $this->name->write($_out,1);
        $this->parentid->write($_out,2);
        $this->type->write($_out,3);
        $this->postcode->write($_out,4);
        $this->areacode->write($_out,5);
        $this->path->write($_out,6);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->aid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->parentid->read($_in , 2, true);
        $this->type->read($_in , 3, true);
        $this->postcode->read($_in , 4, true);
        $this->areacode->read($_in , 5, true);
        $this->path->read($_in , 6, true);
    }
}

class TStructUserSchool extends c_struct
{
    public $uid;
    public $sid;
    public $schoolName;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->sid = clone $this->sid;
        $this->schoolName = clone $this->schoolName;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->sid = new  c_int;
        $this->schoolName = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TStructUserSchool";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->sid->write($_out,1);
        $this->schoolName->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->sid->read($_in , 1, true);
        $this->schoolName->read($_in , 2, true);
    }
}

class TClassCardInfo extends c_struct
{
    public $cid;
    public $cName;
    public $classCode;
    public $masterName;
    public $joinverify;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->cName = clone $this->cName;
        $this->classCode = clone $this->classCode;
        $this->masterName = clone $this->masterName;
        $this->joinverify = clone $this->joinverify;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->cName = new  c_string;
        $this->classCode = new  c_string;
        $this->masterName = new  c_string;
        $this->joinverify = new  c_short;
    }

    public function get_class_name()
    {
        return "Apollo.TClassCardInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->cName->write($_out,1);
        $this->classCode->write($_out,2);
        $this->masterName->write($_out,3);
        $this->joinverify->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->cName->read($_in , 1, true);
        $this->classCode->read($_in , 2, true);
        $this->masterName->read($_in , 3, true);
        $this->joinverify->read($_in , 4, false);
    }
}

class TSchool extends c_struct
{
    public $scid;
    public $name;
    public $city;
    public $region;
    public $aid;

    public function __clone()
    {
        $this->scid = clone $this->scid;
        $this->name = clone $this->name;
        $this->city = clone $this->city;
        $this->region = clone $this->region;
        $this->aid = clone $this->aid;
    }

    public function __construct()
    {
        $this->scid = new  c_int;
        $this->name = new  c_string;
        $this->city = new  c_string;
        $this->region = new  c_string;
        $this->aid = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TSchool";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->scid->write($_out,0);
        $this->name->write($_out,1);
        $this->city->write($_out,2);
        $this->region->write($_out,3);
        $this->aid->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->scid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->city->read($_in , 2, false);
        $this->region->read($_in , 3, false);
        $this->aid->read($_in , 4, false);
    }
}

class TClass extends c_struct
{
    public $cid;
    public $name;
    public $code;
    public $tSchool;
    public $authority;
    public $studentTotal;
    public $teacherTotal;
    public $subject;
    public $year;
    public $stid;
    public $type;
    public $masterName;
    public $joinverify;
    public $createType;
    public $childName;
    public $classFee;
    public $masterUid;
    public $grade;
    public $blacklist;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->name = clone $this->name;
        $this->code = clone $this->code;
        $this->tSchool = clone $this->tSchool;
        $this->authority = clone $this->authority;
        $this->studentTotal = clone $this->studentTotal;
        $this->teacherTotal = clone $this->teacherTotal;
        $this->subject = clone $this->subject;
        $this->year = clone $this->year;
        $this->stid = clone $this->stid;
        $this->type = clone $this->type;
        $this->masterName = clone $this->masterName;
        $this->joinverify = clone $this->joinverify;
        $this->createType = clone $this->createType;
        $this->childName = clone $this->childName;
        $this->classFee = clone $this->classFee;
        $this->masterUid = clone $this->masterUid;
        $this->grade = clone $this->grade;
        $this->blacklist = clone $this->blacklist;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->name = new  c_string;
        $this->code = new  c_string;
        $this->tSchool = new  TSchool;
        $this->authority = new  c_int;
        $this->studentTotal = new  c_int;
        $this->teacherTotal = new  c_int;
        $this->subject = new  c_string;
        $this->year = new  c_int;
        $this->stid = new  c_int;
        $this->type = new  c_int;
        $this->masterName = new  c_string;
        $this->joinverify = new  c_int;
        $this->createType = new  c_int;
        $this->childName = new  c_string;
        $this->classFee = new  c_int;
        $this->masterUid = new  c_string;
        $this->grade = new  c_int;
        $this->blacklist = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->name->write($_out,1);
        $this->code->write($_out,2);
        $this->tSchool->write($_out,3);
        $this->authority->write($_out,4);
        $this->studentTotal->write($_out,5);
        $this->teacherTotal->write($_out,6);
        $this->subject->write($_out,7);
        $this->year->write($_out,8);
        $this->stid->write($_out,9);
        $this->type->write($_out,10);
        $this->masterName->write($_out,11);
        $this->joinverify->write($_out,12);
        $this->createType->write($_out,13);
        $this->childName->write($_out,14);
        $this->classFee->write($_out,15);
        $this->masterUid->write($_out,16);
        $this->grade->write($_out,17);
        $this->blacklist->write($_out,18);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->code->read($_in , 2, false);
        $this->tSchool->read($_in , 3, false);
        $this->authority->read($_in , 4, true);
        $this->studentTotal->read($_in , 5, false);
        $this->teacherTotal->read($_in , 6, false);
        $this->subject->read($_in , 7, false);
        $this->year->read($_in , 8, false);
        $this->stid->read($_in , 9, false);
        $this->type->read($_in , 10, false);
        $this->masterName->read($_in , 11, false);
        $this->joinverify->read($_in , 12, false);
        $this->createType->read($_in , 13, false);
        $this->childName->read($_in , 14, false);
        $this->classFee->read($_in , 15, false);
        $this->masterUid->read($_in , 16, false);
        $this->grade->read($_in , 17, false);
        $this->blacklist->read($_in , 18, false);
    }
}

class TClassGroup extends c_struct
{
    public $name;
    public $vClasses;
    public $childId;

    public function __clone()
    {
        $this->name = clone $this->name;
        $this->vClasses = clone $this->vClasses;
        $this->childId = clone $this->childId;
    }

    public function __construct()
    {
        $this->name = new  c_string;
        $this->vClasses = new  c_vector (new TClass);
        $this->childId = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TClassGroup";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->name->write($_out,0);
        $this->vClasses->write($_out,1);
        $this->childId->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->name->read($_in , 0, true);
        $this->vClasses->read($_in , 1, true);
        $this->childId->read($_in , 2, false);
    }
}

class TFamily extends c_struct
{
    public $uid;
    public $name;
    public $photo;
    public $relation;
    public $guardianType;
    public $mobilePhone;
    public $icon;
    public $loginstatus;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->photo = clone $this->photo;
        $this->relation = clone $this->relation;
        $this->guardianType = clone $this->guardianType;
        $this->mobilePhone = clone $this->mobilePhone;
        $this->icon = clone $this->icon;
        $this->loginstatus = clone $this->loginstatus;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->photo = new  c_string;
        $this->relation = new  c_string;
        $this->guardianType = new  c_int;
        $this->mobilePhone = new  c_string;
        $this->icon = new  c_int;
        $this->loginstatus = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TFamily";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->photo->write($_out,2);
        $this->relation->write($_out,3);
        $this->guardianType->write($_out,4);
        $this->mobilePhone->write($_out,5);
        $this->icon->write($_out,6);
        $this->loginstatus->write($_out,7);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->photo->read($_in , 2, false);
        $this->relation->read($_in , 3, true);
        $this->guardianType->read($_in , 4, true);
        $this->mobilePhone->read($_in , 5, false);
        $this->icon->read($_in , 6, false);
        $this->loginstatus->read($_in , 7, false);
    }
}

class TStudent extends c_struct
{
    public $sid;
    public $vFamilys;
    public $name;
    public $photo;
    public $studentNumber;
    public $joinTime;
    public $icon;

    public function __clone()
    {
        $this->sid = clone $this->sid;
        $this->vFamilys = clone $this->vFamilys;
        $this->name = clone $this->name;
        $this->photo = clone $this->photo;
        $this->studentNumber = clone $this->studentNumber;
        $this->joinTime = clone $this->joinTime;
        $this->icon = clone $this->icon;
    }

    public function __construct()
    {
        $this->sid = new  c_string;
        $this->vFamilys = new  c_vector (new TFamily);
        $this->name = new  c_string;
        $this->photo = new  c_string;
        $this->studentNumber = new  c_string;
        $this->joinTime = new  c_string;
        $this->icon = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TStudent";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sid->write($_out,0);
        $this->vFamilys->write($_out,1);
        $this->name->write($_out,2);
        $this->photo->write($_out,3);
        $this->studentNumber->write($_out,4);
        $this->joinTime->write($_out,5);
        $this->icon->write($_out,6);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sid->read($_in , 0, true);
        $this->vFamilys->read($_in , 1, false);
        $this->name->read($_in , 2, true);
        $this->photo->read($_in , 3, true);
        $this->studentNumber->read($_in , 4, false);
        $this->joinTime->read($_in , 5, false);
        $this->icon->read($_in , 6, false);
    }
}

class TTeacher extends c_struct
{
    public $uid;
    public $name;
    public $photo;
    public $type;
    public $sex;
    public $mobilePhone;
    public $subject;
    public $joinTime;
    public $icon;
    public $teacherauth;
    public $loginstatus;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->photo = clone $this->photo;
        $this->type = clone $this->type;
        $this->sex = clone $this->sex;
        $this->mobilePhone = clone $this->mobilePhone;
        $this->subject = clone $this->subject;
        $this->joinTime = clone $this->joinTime;
        $this->icon = clone $this->icon;
        $this->teacherauth = clone $this->teacherauth;
        $this->loginstatus = clone $this->loginstatus;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->photo = new  c_string;
        $this->type = new  c_int;
        $this->sex = new  c_int;
        $this->mobilePhone = new  c_string;
        $this->subject = new  c_string;
        $this->joinTime = new  c_string;
        $this->icon = new  c_int;
        $this->teacherauth = new  c_short;
        $this->loginstatus = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TTeacher";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->photo->write($_out,2);
        $this->type->write($_out,3);
        $this->sex->write($_out,4);
        $this->mobilePhone->write($_out,5);
        $this->subject->write($_out,6);
        $this->joinTime->write($_out,7);
        $this->icon->write($_out,8);
        $this->teacherauth->write($_out,9);
        $this->loginstatus->write($_out,10);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->photo->read($_in , 2, false);
        $this->type->read($_in , 3, false);
        $this->sex->read($_in , 4, false);
        $this->mobilePhone->read($_in , 5, false);
        $this->subject->read($_in , 6, false);
        $this->joinTime->read($_in , 7, false);
        $this->icon->read($_in , 8, false);
        $this->teacherauth->read($_in , 9, false);
        $this->loginstatus->read($_in , 10, false);
    }
}

class TGrade extends c_struct
{
    public $gid;
    public $gName;
    public $stid;

    public function __clone()
    {
        $this->gid = clone $this->gid;
        $this->gName = clone $this->gName;
        $this->stid = clone $this->stid;
    }

    public function __construct()
    {
        $this->gid = new  c_int;
        $this->gName = new  c_string;
        $this->stid = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TGrade";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->gid->write($_out,0);
        $this->gName->write($_out,1);
        $this->stid->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->gid->read($_in , 0, true);
        $this->gName->read($_in , 1, true);
        $this->stid->read($_in , 2, true);
    }
}

class TChild extends c_struct
{
    public $sid;
    public $name;
    public $icon;

    public function __clone()
    {
        $this->sid = clone $this->sid;
        $this->name = clone $this->name;
        $this->icon = clone $this->icon;
    }

    public function __construct()
    {
        $this->sid = new  c_string;
        $this->name = new  c_string;
        $this->icon = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TChild";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sid->write($_out,0);
        $this->name->write($_out,1);
        $this->icon->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->icon->read($_in , 2, true);
    }
}

class TUserChild extends c_struct
{
    public $studentid;
    public $role;
    public $main;
    public $name;
    public $username;

    public function __clone()
    {
        $this->studentid = clone $this->studentid;
        $this->role = clone $this->role;
        $this->main = clone $this->main;
        $this->name = clone $this->name;
        $this->username = clone $this->username;
    }

    public function __construct()
    {
        $this->studentid = new  c_string;
        $this->role = new  c_string;
        $this->main = new  c_short;
        $this->name = new  c_string;
        $this->username = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TUserChild";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->studentid->write($_out,0);
        $this->role->write($_out,1);
        $this->main->write($_out,2);
        $this->name->write($_out,3);
        $this->username->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->studentid->read($_in , 0, true);
        $this->role->read($_in , 1, true);
        $this->main->read($_in , 2, true);
        $this->name->read($_in , 3, true);
        $this->username->read($_in , 4, true);
    }
}

class TStudentGuardian extends c_struct
{
    public $uid;
    public $role;
    public $main;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->role = clone $this->role;
        $this->main = clone $this->main;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->role = new  c_string;
        $this->main = new  c_short;
    }

    public function get_class_name()
    {
        return "Apollo.TStudentGuardian";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->role->write($_out,1);
        $this->main->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->role->read($_in , 1, true);
        $this->main->read($_in , 2, true);
    }
}

class TUserLabel extends c_struct
{
    public $id;
    public $text;

    public function __clone()
    {
        $this->id = clone $this->id;
        $this->text = clone $this->text;
    }

    public function __construct()
    {
        $this->id = new  c_int;
        $this->text = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TUserLabel";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->id->write($_out,0);
        $this->text->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->id->read($_in , 0, true);
        $this->text->read($_in , 1, true);
    }
}

class TUser extends c_struct
{
    public $uid;
    public $name;
    public $sex;
    public $icon;
    public $signature;
    public $mobilephone;
    public $address;
    public $identity;
    public $addressId;
    public $teacherauth;
    public $issmsauth;
    public $usertype;
    public $userschoolname;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->sex = clone $this->sex;
        $this->icon = clone $this->icon;
        $this->signature = clone $this->signature;
        $this->mobilephone = clone $this->mobilephone;
        $this->address = clone $this->address;
        $this->identity = clone $this->identity;
        $this->addressId = clone $this->addressId;
        $this->teacherauth = clone $this->teacherauth;
        $this->issmsauth = clone $this->issmsauth;
        $this->usertype = clone $this->usertype;
        $this->userschoolname = clone $this->userschoolname;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->sex = new  c_short;
        $this->icon = new  c_string;
        $this->signature = new  c_string;
        $this->mobilephone = new  c_string;
        $this->address = new  c_string;
        $this->identity = new  c_int;
        $this->addressId = new  c_int;
        $this->teacherauth = new  c_short;
        $this->issmsauth = new  c_short;
        $this->usertype = new  c_short;
        $this->userschoolname = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TUser";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->sex->write($_out,2);
        $this->icon->write($_out,3);
        $this->signature->write($_out,4);
        $this->mobilephone->write($_out,5);
        $this->address->write($_out,6);
        $this->identity->write($_out,7);
        $this->addressId->write($_out,8);
        $this->teacherauth->write($_out,9);
        $this->issmsauth->write($_out,10);
        $this->usertype->write($_out,11);
        $this->userschoolname->write($_out,12);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->sex->read($_in , 2, true);
        $this->icon->read($_in , 3, true);
        $this->signature->read($_in , 4, true);
        $this->mobilephone->read($_in , 5, true);
        $this->address->read($_in , 6, true);
        $this->identity->read($_in , 7, true);
        $this->addressId->read($_in , 8, false);
        $this->teacherauth->read($_in , 9, false);
        $this->issmsauth->read($_in , 10, false);
        $this->usertype->read($_in , 11, false);
        $this->userschoolname->read($_in , 12, false);
    }
}

class TThirdAccount extends c_struct
{
    public $flag;
    public $threeuserid;
    public $threeusername;

    public function __clone()
    {
        $this->flag = clone $this->flag;
        $this->threeuserid = clone $this->threeuserid;
        $this->threeusername = clone $this->threeusername;
    }

    public function __construct()
    {
        $this->flag = new  c_int;
        $this->threeuserid = new  c_string;
        $this->threeusername = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TThirdAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->flag->write($_out,0);
        $this->threeuserid->write($_out,1);
        $this->threeusername->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->flag->read($_in , 0, true);
        $this->threeuserid->read($_in , 1, true);
        $this->threeusername->read($_in , 2, true);
    }
}

class TUserBase extends c_struct
{
    public $tUser;
    public $vChildrenMain;
    public $vChildrenForcus;
    public $isRelatedClass;
    public $timestamp;
    public $banban;
    public $vThirdAccounts;
    public $canSetBanBanNo;
    public $userdesc;
    public $vLabels;

    public function __clone()
    {
        $this->tUser = clone $this->tUser;
        $this->vChildrenMain = clone $this->vChildrenMain;
        $this->vChildrenForcus = clone $this->vChildrenForcus;
        $this->isRelatedClass = clone $this->isRelatedClass;
        $this->timestamp = clone $this->timestamp;
        $this->banban = clone $this->banban;
        $this->vThirdAccounts = clone $this->vThirdAccounts;
        $this->canSetBanBanNo = clone $this->canSetBanBanNo;
        $this->userdesc = clone $this->userdesc;
        $this->vLabels = clone $this->vLabels;
    }

    public function __construct()
    {
        $this->tUser = new  TUser;
        $this->vChildrenMain = new  c_vector (new TChild);
        $this->vChildrenForcus = new  c_vector (new TChild);
        $this->isRelatedClass = new  c_short;
        $this->timestamp = new  c_int64;
        $this->banban = new  c_string;
        $this->vThirdAccounts = new  c_vector (new TThirdAccount);
        $this->canSetBanBanNo = new  c_short;
        $this->userdesc = new  c_string;
        $this->vLabels = new  c_vector (new TUserLabel);
    }

    public function get_class_name()
    {
        return "Apollo.TUserBase";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->tUser->write($_out,0);
        $this->vChildrenMain->write($_out,1);
        $this->vChildrenForcus->write($_out,2);
        $this->isRelatedClass->write($_out,3);
        $this->timestamp->write($_out,4);
        $this->banban->write($_out,5);
        $this->vThirdAccounts->write($_out,6);
        $this->canSetBanBanNo->write($_out,7);
        $this->userdesc->write($_out,8);
        $this->vLabels->write($_out,9);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->tUser->read($_in , 0, true);
        $this->vChildrenMain->read($_in , 1, true);
        $this->vChildrenForcus->read($_in , 2, true);
        $this->isRelatedClass->read($_in , 3, false);
        $this->timestamp->read($_in , 4, false);
        $this->banban->read($_in , 5, false);
        $this->vThirdAccounts->read($_in , 6, false);
        $this->canSetBanBanNo->read($_in , 7, false);
        $this->userdesc->read($_in , 8, false);
        $this->vLabels->read($_in , 9, false);
    }
}

class TClassOfMember extends c_struct
{
    public $vStudents;
    public $vTeachers;

    public function __clone()
    {
        $this->vStudents = clone $this->vStudents;
        $this->vTeachers = clone $this->vTeachers;
    }

    public function __construct()
    {
        $this->vStudents = new  c_vector (new TStudent);
        $this->vTeachers = new  c_vector (new TTeacher);
    }

    public function get_class_name()
    {
        return "Apollo.TClassOfMember";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vStudents->write($_out,0);
        $this->vTeachers->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vStudents->read($_in , 0, true);
        $this->vTeachers->read($_in , 1, true);
    }
}

class TRecFamily extends c_struct
{
    public $uid;
    public $name;
    public $role;
    public $main;
    public $mobilePhone;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->role = clone $this->role;
        $this->main = clone $this->main;
        $this->mobilePhone = clone $this->mobilePhone;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->role = new  c_string;
        $this->main = new  c_short;
        $this->mobilePhone = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRecFamily";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->role->write($_out,2);
        $this->main->write($_out,3);
        $this->mobilePhone->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->role->read($_in , 2, true);
        $this->main->read($_in , 3, true);
        $this->mobilePhone->read($_in , 4, true);
    }
}

class TRecUserInfo extends c_struct
{
    public $uid;
    public $name;
    public $identity;
    public $vecFamily;
    public $mobilePhone;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->identity = clone $this->identity;
        $this->vecFamily = clone $this->vecFamily;
        $this->mobilePhone = clone $this->mobilePhone;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->identity = new  c_short;
        $this->vecFamily = new  c_vector (new TRecFamily);
        $this->mobilePhone = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRecUserInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->identity->write($_out,2);
        $this->vecFamily->write($_out,3);
        $this->mobilePhone->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->identity->read($_in , 2, true);
        $this->vecFamily->read($_in , 3, true);
        $this->mobilePhone->read($_in , 4, true);
    }
}

class TUserInfoForSendSysNotice extends c_struct
{
    public $masterName;
    public $masterIcon;
    public $userName;
    public $userIcon;
    public $student;
    public $masterUid;

    public function __clone()
    {
        $this->masterName = clone $this->masterName;
        $this->masterIcon = clone $this->masterIcon;
        $this->userName = clone $this->userName;
        $this->userIcon = clone $this->userIcon;
        $this->student = clone $this->student;
        $this->masterUid = clone $this->masterUid;
    }

    public function __construct()
    {
        $this->masterName = new  c_string;
        $this->masterIcon = new  c_string;
        $this->userName = new  c_string;
        $this->userIcon = new  c_string;
        $this->student = new  TStudent;
        $this->masterUid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TUserInfoForSendSysNotice";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->masterName->write($_out,0);
        $this->masterIcon->write($_out,1);
        $this->userName->write($_out,2);
        $this->userIcon->write($_out,3);
        $this->student->write($_out,4);
        $this->masterUid->write($_out,5);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->masterName->read($_in , 0, true);
        $this->masterIcon->read($_in , 1, true);
        $this->userName->read($_in , 2, true);
        $this->userIcon->read($_in , 3, true);
        $this->student->read($_in , 4, true);
        $this->masterUid->read($_in , 5, true);
    }
}

class TRecSchoolGroup extends c_struct
{
    public $sid;
    public $name;
    public $vClass;

    public function __clone()
    {
        $this->sid = clone $this->sid;
        $this->name = clone $this->name;
        $this->vClass = clone $this->vClass;
    }

    public function __construct()
    {
        $this->sid = new  c_int;
        $this->name = new  c_string;
        $this->vClass = new  c_vector (new TClass);
    }

    public function get_class_name()
    {
        return "Apollo.TRecSchoolGroup";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sid->write($_out,0);
        $this->name->write($_out,1);
        $this->vClass->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->vClass->read($_in , 2, true);
    }
}

class TRecEmClassTeacher extends c_struct
{
    public $cid;
    public $name;
    public $vTeachers;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->name = clone $this->name;
        $this->vTeachers = clone $this->vTeachers;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->name = new  c_string;
        $this->vTeachers = new  c_vector (new TTeacher);
    }

    public function get_class_name()
    {
        return "Apollo.TRecEmClassTeacher";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->name->write($_out,1);
        $this->vTeachers->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->vTeachers->read($_in , 2, true);
    }
}

class TRecEmergencySchoolClassTeacherGroup extends c_struct
{
    public $sid;
    public $name;
    public $vEmClassTeacher;

    public function __clone()
    {
        $this->sid = clone $this->sid;
        $this->name = clone $this->name;
        $this->vEmClassTeacher = clone $this->vEmClassTeacher;
    }

    public function __construct()
    {
        $this->sid = new  c_int;
        $this->name = new  c_string;
        $this->vEmClassTeacher = new  c_vector (new TRecEmClassTeacher);
    }

    public function get_class_name()
    {
        return "Apollo.TRecEmergencySchoolClassTeacherGroup";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sid->write($_out,0);
        $this->name->write($_out,1);
        $this->vEmClassTeacher->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->vEmClassTeacher->read($_in , 2, true);
    }
}

class TAuthTeacherApplication extends c_struct
{
    public $id;
    public $uid;
    public $name;
    public $mobilePhone;
    public $sex;
    public $pic;
    public $creationtime;
    public $audittime;
    public $auditstatus;
    public $desc;

    public function __clone()
    {
        $this->id = clone $this->id;
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->mobilePhone = clone $this->mobilePhone;
        $this->sex = clone $this->sex;
        $this->pic = clone $this->pic;
        $this->creationtime = clone $this->creationtime;
        $this->audittime = clone $this->audittime;
        $this->auditstatus = clone $this->auditstatus;
        $this->desc = clone $this->desc;
    }

    public function __construct()
    {
        $this->id = new  c_int;
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->mobilePhone = new  c_string;
        $this->sex = new  c_short;
        $this->pic = new  c_string;
        $this->creationtime = new  c_int64;
        $this->audittime = new  c_int64;
        $this->auditstatus = new  c_short;
        $this->desc = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TAuthTeacherApplication";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->id->write($_out,0);
        $this->uid->write($_out,1);
        $this->name->write($_out,2);
        $this->mobilePhone->write($_out,3);
        $this->sex->write($_out,4);
        $this->pic->write($_out,5);
        $this->creationtime->write($_out,6);
        $this->audittime->write($_out,7);
        $this->auditstatus->write($_out,8);
        $this->desc->write($_out,9);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->id->read($_in , 0, true);
        $this->uid->read($_in , 1, true);
        $this->name->read($_in , 2, true);
        $this->mobilePhone->read($_in , 3, true);
        $this->sex->read($_in , 4, true);
        $this->pic->read($_in , 5, true);
        $this->creationtime->read($_in , 6, true);
        $this->audittime->read($_in , 7, true);
        $this->auditstatus->read($_in , 8, true);
        $this->desc->read($_in , 9, true);
    }
}

class TProFileUserInfo extends c_struct
{
    public $uid;
    public $name;
    public $sex;
    public $identity;
    public $teacherauth;
    public $address;
    public $photo;
    public $userdesc;
    public $vLabels;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->sex = clone $this->sex;
        $this->identity = clone $this->identity;
        $this->teacherauth = clone $this->teacherauth;
        $this->address = clone $this->address;
        $this->photo = clone $this->photo;
        $this->userdesc = clone $this->userdesc;
        $this->vLabels = clone $this->vLabels;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->sex = new  c_short;
        $this->identity = new  c_int;
        $this->teacherauth = new  c_short;
        $this->address = new  c_string;
        $this->photo = new  c_string;
        $this->userdesc = new  c_string;
        $this->vLabels = new  c_vector (new TUserLabel);
    }

    public function get_class_name()
    {
        return "Apollo.TProFileUserInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->sex->write($_out,2);
        $this->identity->write($_out,3);
        $this->teacherauth->write($_out,4);
        $this->address->write($_out,5);
        $this->photo->write($_out,6);
        $this->userdesc->write($_out,7);
        $this->vLabels->write($_out,8);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->sex->read($_in , 2, true);
        $this->identity->read($_in , 3, true);
        $this->teacherauth->read($_in , 4, true);
        $this->address->read($_in , 5, true);
        $this->photo->read($_in , 6, true);
        $this->userdesc->read($_in , 7, false);
        $this->vLabels->read($_in , 8, false);
    }
}


?>