<?php

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************


require_once('jce.php');
class TReqCreateClass extends c_struct
{
    public $name;
    public $sid;
    public $grade;

    public function __clone()
    {
        $this->name = clone $this->name;
        $this->sid = clone $this->sid;
        $this->grade = clone $this->grade;
    }

    public function __construct()
    {
        $this->name = new  c_string;
        $this->sid = new  c_int;
        $this->grade = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqCreateClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->name->write($_out,0);
        $this->sid->write($_out,1);
        $this->grade->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->name->read($_in , 0, true);
        $this->sid->read($_in , 1, false);
        $this->grade->read($_in , 2, false);
    }
}

class TRespCreateClass extends c_struct
{
    public $classCard;

    public function __clone()
    {
        $this->classCard = clone $this->classCard;
    }

    public function __construct()
    {
        $this->classCard = new  TClassCardInfo;
    }

    public function get_class_name()
    {
        return "Apollo.TRespCreateClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->classCard->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->classCard->read($_in , 0, true);
    }
}

class TReqSearchClass extends c_struct
{
    public $content;
    public $type;

    public function __clone()
    {
        $this->content = clone $this->content;
        $this->type = clone $this->type;
    }

    public function __construct()
    {
        $this->content = new  c_string;
        $this->type = new  c_short;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSearchClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->content->write($_out,0);
        $this->type->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->content->read($_in , 0, true);
        $this->type->read($_in , 1, true);
    }
}

class TRespSearchClass extends c_struct
{
    public $vecClass;

    public function __clone()
    {
        $this->vecClass = clone $this->vecClass;
    }

    public function __construct()
    {
        $this->vecClass = new  c_vector (new TClassCardInfo);
    }

    public function get_class_name()
    {
        return "Apollo.TRespSearchClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vecClass->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vecClass->read($_in , 0, true);
    }
}

class TReqJoinClass extends c_struct
{
    public $cid;
    public $uid;
    public $type;
    public $classCode;
    public $studentName;
    public $relation;
    public $subjectName;
    public $studentId;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->uid = clone $this->uid;
        $this->type = clone $this->type;
        $this->classCode = clone $this->classCode;
        $this->studentName = clone $this->studentName;
        $this->relation = clone $this->relation;
        $this->subjectName = clone $this->subjectName;
        $this->studentId = clone $this->studentId;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->uid = new  c_string;
        $this->type = new  c_short;
        $this->classCode = new  c_string;
        $this->studentName = new  c_string;
        $this->relation = new  c_string;
        $this->subjectName = new  c_string;
        $this->studentId = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqJoinClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->uid->write($_out,1);
        $this->type->write($_out,2);
        $this->classCode->write($_out,3);
        $this->studentName->write($_out,4);
        $this->relation->write($_out,5);
        $this->subjectName->write($_out,6);
        $this->studentId->write($_out,7);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->uid->read($_in , 1, true);
        $this->type->read($_in , 2, true);
        $this->classCode->read($_in , 3, false);
        $this->studentName->read($_in , 4, false);
        $this->relation->read($_in , 5, false);
        $this->subjectName->read($_in , 6, false);
        $this->studentId->read($_in , 7, false);
    }
}

class TRespJoinClass extends c_struct
{
    public $studentId;

    public function __clone()
    {
        $this->studentId = clone $this->studentId;
    }

    public function __construct()
    {
        $this->studentId = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespJoinClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->studentId->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->studentId->read($_in , 0, true);
    }
}

class TRespClassGroups extends c_struct
{
    public $vClassGroups;

    public function __clone()
    {
        $this->vClassGroups = clone $this->vClassGroups;
    }

    public function __construct()
    {
        $this->vClassGroups = new  c_vector (new TClassGroup);
    }

    public function get_class_name()
    {
        return "Apollo.TRespClassGroups";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vClassGroups->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vClassGroups->read($_in , 0, true);
    }
}

class TReqClassInfo extends c_struct
{
    public $cid;
    public $authority;
    public $childId;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->authority = clone $this->authority;
        $this->childId = clone $this->childId;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->authority = new  c_int;
        $this->childId = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqClassInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->authority->write($_out,1);
        $this->childId->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->authority->read($_in , 1, true);
        $this->childId->read($_in , 2, false);
    }
}

class TRespClassInfo extends c_struct
{
    public $tClass;

    public function __clone()
    {
        $this->tClass = clone $this->tClass;
    }

    public function __construct()
    {
        $this->tClass = new  TClass;
    }

    public function get_class_name()
    {
        return "Apollo.TRespClassInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->tClass->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->tClass->read($_in , 0, true);
    }
}

class TReqExitClass extends c_struct
{
    public $cid;
    public $flag;
    public $studentId;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->flag = clone $this->flag;
        $this->studentId = clone $this->studentId;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->flag = new  c_int;
        $this->studentId = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqExitClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->flag->write($_out,1);
        $this->studentId->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->flag->read($_in , 1, true);
        $this->studentId->read($_in , 2, false);
    }
}

class TReqGetClassMember extends c_struct
{
    public $cid;
    public $flag;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->flag = clone $this->flag;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->flag = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetClassMember";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->flag->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->flag->read($_in , 1, true);
    }
}

class TRespGetClassMember extends c_struct
{
    public $vStudents;
    public $vTeachers;

    public function __clone()
    {
        $this->vStudents = clone $this->vStudents;
        $this->vTeachers = clone $this->vTeachers;
    }

    public function __construct()
    {
        $this->vStudents = new  c_vector (new TStudent);
        $this->vTeachers = new  c_vector (new TTeacher);
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetClassMember";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vStudents->write($_out,0);
        $this->vTeachers->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vStudents->read($_in , 0, false);
        $this->vTeachers->read($_in , 1, false);
    }
}

class TReqDeleteClassMember extends c_struct
{
    public $cid;
    public $flag;
    public $vMemberIds;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->flag = clone $this->flag;
        $this->vMemberIds = clone $this->vMemberIds;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->flag = new  c_int;
        $this->vMemberIds = new  c_vector (new c_string);
    }

    public function get_class_name()
    {
        return "Apollo.TReqDeleteClassMember";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->flag->write($_out,1);
        $this->vMemberIds->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->flag->read($_in , 1, true);
        $this->vMemberIds->read($_in , 2, true);
    }
}

class TReqSetClass extends c_struct
{
    public $cid;
    public $flag;
    public $tSchool;
    public $validate;
    public $cName;
    public $uid;
    public $gid;
    public $stid;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->flag = clone $this->flag;
        $this->tSchool = clone $this->tSchool;
        $this->validate = clone $this->validate;
        $this->cName = clone $this->cName;
        $this->uid = clone $this->uid;
        $this->gid = clone $this->gid;
        $this->stid = clone $this->stid;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->flag = new  c_int;
        $this->tSchool = new  TSchool;
        $this->validate = new  c_int;
        $this->cName = new  c_string;
        $this->uid = new  c_string;
        $this->gid = new  c_int;
        $this->stid = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSetClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->flag->write($_out,1);
        $this->tSchool->write($_out,2);
        $this->validate->write($_out,3);
        $this->cName->write($_out,4);
        $this->uid->write($_out,5);
        $this->gid->write($_out,6);
        $this->stid->write($_out,7);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->flag->read($_in , 1, true);
        $this->tSchool->read($_in , 2, false);
        $this->validate->read($_in , 3, false);
        $this->cName->read($_in , 4, false);
        $this->uid->read($_in , 5, false);
        $this->gid->read($_in , 6, false);
        $this->stid->read($_in , 7, false);
    }
}

class TReqVerifyJoinClass extends c_struct
{
    public $auditRecordId;
    public $flag;
    public $cid;

    public function __clone()
    {
        $this->auditRecordId = clone $this->auditRecordId;
        $this->flag = clone $this->flag;
        $this->cid = clone $this->cid;
    }

    public function __construct()
    {
        $this->auditRecordId = new  c_string;
        $this->flag = new  c_int;
        $this->cid = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqVerifyJoinClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->auditRecordId->write($_out,0);
        $this->flag->write($_out,1);
        $this->cid->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->auditRecordId->read($_in , 0, true);
        $this->flag->read($_in , 1, true);
        $this->cid->read($_in , 2, true);
    }
}

class TReqDismissClass extends c_struct
{
    public $cid;

    public function __clone()
    {
        $this->cid = clone $this->cid;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqDismissClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
    }
}

class TRespGetAllSchoolTypes extends c_struct
{
    public $mapSChoolTypes;

    public function __clone()
    {
        $this->mapSChoolTypes = clone $this->mapSChoolTypes;
    }

    public function __construct()
    {
        $this->mapSChoolTypes = new  c_map (new c_int,new c_string);
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetAllSchoolTypes";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mapSChoolTypes->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mapSChoolTypes->read($_in , 0, true);
    }
}

class TRespGetAllGrades extends c_struct
{
    public $vGrades;

    public function __clone()
    {
        $this->vGrades = clone $this->vGrades;
    }

    public function __construct()
    {
        $this->vGrades = new  c_vector (new TGrade);
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetAllGrades";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vGrades->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vGrades->read($_in , 0, true);
    }
}

class TReqGetClassGrade extends c_struct
{
    public $cid;

    public function __clone()
    {
        $this->cid = clone $this->cid;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetClassGrade";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
    }
}

class TRespGetClassGrade extends c_struct
{
    public $tGrade;

    public function __clone()
    {
        $this->tGrade = clone $this->tGrade;
    }

    public function __construct()
    {
        $this->tGrade = new  TGrade;
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetClassGrade";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->tGrade->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->tGrade->read($_in , 0, true);
    }
}

class TReqSetSubject extends c_struct
{
    public $cid;
    public $teacherId;
    public $newSubject;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->teacherId = clone $this->teacherId;
        $this->newSubject = clone $this->newSubject;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->teacherId = new  c_string;
        $this->newSubject = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSetSubject";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->teacherId->write($_out,2);
        $this->newSubject->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->teacherId->read($_in , 2, true);
        $this->newSubject->read($_in , 3, true);
    }
}

class TReqGetDetailedIdentity extends c_struct
{
    public $uid;

    public function __clone()
    {
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetDetailedIdentity";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
    }
}

class TRespGetDetailedIdentity extends c_struct
{
    public $isMaster;
    public $isTeacher;
    public $isPatriarch;
    public $isFocus;

    public function __clone()
    {
        $this->isMaster = clone $this->isMaster;
        $this->isTeacher = clone $this->isTeacher;
        $this->isPatriarch = clone $this->isPatriarch;
        $this->isFocus = clone $this->isFocus;
    }

    public function __construct()
    {
        $this->isMaster = new  c_short;
        $this->isTeacher = new  c_short;
        $this->isPatriarch = new  c_short;
        $this->isFocus = new  c_short;
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetDetailedIdentity";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->isMaster->write($_out,0);
        $this->isTeacher->write($_out,1);
        $this->isPatriarch->write($_out,2);
        $this->isFocus->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->isMaster->read($_in , 0, true);
        $this->isTeacher->read($_in , 1, true);
        $this->isPatriarch->read($_in , 2, true);
        $this->isFocus->read($_in , 3, true);
    }
}

class TReqSetStudentNumber extends c_struct
{
    public $studentUid;
    public $studentNumber;

    public function __clone()
    {
        $this->studentUid = clone $this->studentUid;
        $this->studentNumber = clone $this->studentNumber;
    }

    public function __construct()
    {
        $this->studentUid = new  c_string;
        $this->studentNumber = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSetStudentNumber";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->studentUid->write($_out,0);
        $this->studentNumber->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->studentUid->read($_in , 0, true);
        $this->studentNumber->read($_in , 1, true);
    }
}

class TMyChildClass extends c_struct
{
    public $cid;
    public $cName;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->cName = clone $this->cName;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->cName = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TMyChildClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->cName->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->cName->read($_in , 1, true);
    }
}

class TMyChild extends c_struct
{
    public $uid;
    public $name;
    public $photo;
    public $sex;
    public $birthday;
    public $role;
    public $vClasses;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->photo = clone $this->photo;
        $this->sex = clone $this->sex;
        $this->birthday = clone $this->birthday;
        $this->role = clone $this->role;
        $this->vClasses = clone $this->vClasses;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->photo = new  c_string;
        $this->sex = new  c_short;
        $this->birthday = new  c_int64;
        $this->role = new  c_string;
        $this->vClasses = new  c_vector (new TMyChildClass);
    }

    public function get_class_name()
    {
        return "Apollo.TMyChild";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->photo->write($_out,2);
        $this->sex->write($_out,3);
        $this->birthday->write($_out,4);
        $this->role->write($_out,5);
        $this->vClasses->write($_out,6);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->photo->read($_in , 2, true);
        $this->sex->read($_in , 3, true);
        $this->birthday->read($_in , 4, true);
        $this->role->read($_in , 5, true);
        $this->vClasses->read($_in , 6, false);
    }
}

class TRespGetParentTStudent extends c_struct
{
    public $vMyStudents;
    public $vFocusStudents;

    public function __clone()
    {
        $this->vMyStudents = clone $this->vMyStudents;
        $this->vFocusStudents = clone $this->vFocusStudents;
    }

    public function __construct()
    {
        $this->vMyStudents = new  c_vector (new TStudent);
        $this->vFocusStudents = new  c_vector (new TStudent);
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetParentTStudent";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vMyStudents->write($_out,0);
        $this->vFocusStudents->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vMyStudents->read($_in , 0, true);
        $this->vFocusStudents->read($_in , 1, true);
    }
}

class TRespGetParentChildren extends c_struct
{
    public $vMyChildren;
    public $vFocusChildren;

    public function __clone()
    {
        $this->vMyChildren = clone $this->vMyChildren;
        $this->vFocusChildren = clone $this->vFocusChildren;
    }

    public function __construct()
    {
        $this->vMyChildren = new  c_vector (new TMyChild);
        $this->vFocusChildren = new  c_vector (new TMyChild);
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetParentChildren";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vMyChildren->write($_out,0);
        $this->vFocusChildren->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vMyChildren->read($_in , 0, true);
        $this->vFocusChildren->read($_in , 1, true);
    }
}

class TReqSetPersonalInfo extends c_struct
{
    public $uid;
    public $flag;
    public $photo;
    public $name;
    public $sex;
    public $address;
    public $desc;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->flag = clone $this->flag;
        $this->photo = clone $this->photo;
        $this->name = clone $this->name;
        $this->sex = clone $this->sex;
        $this->address = clone $this->address;
        $this->desc = clone $this->desc;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->flag = new  c_int;
        $this->photo = new  c_string;
        $this->name = new  c_string;
        $this->sex = new  c_short;
        $this->address = new  c_int;
        $this->desc = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSetPersonalInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->flag->write($_out,1);
        $this->photo->write($_out,2);
        $this->name->write($_out,3);
        $this->sex->write($_out,4);
        $this->address->write($_out,5);
        $this->desc->write($_out,6);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->flag->read($_in , 1, true);
        $this->photo->read($_in , 2, true);
        $this->name->read($_in , 3, true);
        $this->sex->read($_in , 4, true);
        $this->address->read($_in , 5, true);
        $this->desc->read($_in , 6, true);
    }
}

class TReqSetPassword extends c_struct
{
    public $uid;
    public $oldPwd;
    public $newPwd;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->oldPwd = clone $this->oldPwd;
        $this->newPwd = clone $this->newPwd;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->oldPwd = new  c_string;
        $this->newPwd = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSetPassword";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->oldPwd->write($_out,1);
        $this->newPwd->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->oldPwd->read($_in , 1, true);
        $this->newPwd->read($_in , 2, true);
    }
}

class TReqSetMobilePhone extends c_struct
{
    public $uid;
    public $flag;
    public $code;
    public $mobilePhone;
    public $pwd;
    public $oldMobilePhone;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->flag = clone $this->flag;
        $this->code = clone $this->code;
        $this->mobilePhone = clone $this->mobilePhone;
        $this->pwd = clone $this->pwd;
        $this->oldMobilePhone = clone $this->oldMobilePhone;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->flag = new  c_short;
        $this->code = new  c_string;
        $this->mobilePhone = new  c_string;
        $this->pwd = new  c_string;
        $this->oldMobilePhone = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSetMobilePhone";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->flag->write($_out,1);
        $this->code->write($_out,2);
        $this->mobilePhone->write($_out,3);
        $this->pwd->write($_out,4);
        $this->oldMobilePhone->write($_out,5);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->flag->read($_in , 1, true);
        $this->code->read($_in , 2, true);
        $this->mobilePhone->read($_in , 3, true);
        $this->pwd->read($_in , 4, true);
        $this->oldMobilePhone->read($_in , 5, false);
    }
}

class TReqCreateChild extends c_struct
{
    public $uid;
    public $name;
    public $role;
    public $photo;
    public $sex;
    public $birthday;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->role = clone $this->role;
        $this->photo = clone $this->photo;
        $this->sex = clone $this->sex;
        $this->birthday = clone $this->birthday;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->role = new  c_string;
        $this->photo = new  c_string;
        $this->sex = new  c_short;
        $this->birthday = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TReqCreateChild";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->role->write($_out,2);
        $this->photo->write($_out,3);
        $this->sex->write($_out,4);
        $this->birthday->write($_out,5);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->role->read($_in , 2, true);
        $this->photo->read($_in , 3, false);
        $this->sex->read($_in , 4, false);
        $this->birthday->read($_in , 5, false);
    }
}

class TRespCreateChild extends c_struct
{
    public $studentUid;

    public function __clone()
    {
        $this->studentUid = clone $this->studentUid;
    }

    public function __construct()
    {
        $this->studentUid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespCreateChild";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->studentUid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->studentUid->read($_in , 0, true);
    }
}

class TRespGetRecSchoolClass extends c_struct
{
    public $vRecSchoolGroups;

    public function __clone()
    {
        $this->vRecSchoolGroups = clone $this->vRecSchoolGroups;
    }

    public function __construct()
    {
        $this->vRecSchoolGroups = new  c_vector (new TRecSchoolGroup);
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetRecSchoolClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vRecSchoolGroups->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vRecSchoolGroups->read($_in , 0, true);
    }
}

class TRespGetTUser extends c_struct
{
    public $user;
    public $vChildrenMain;
    public $vChildrenForcus;
    public $isRelatedClass;
    public $timestamp;
    public $banban;
    public $vThirdAccounts;
    public $canSetBanBanNo;
    public $userdesc;
    public $vLabels;

    public function __clone()
    {
        $this->user = clone $this->user;
        $this->vChildrenMain = clone $this->vChildrenMain;
        $this->vChildrenForcus = clone $this->vChildrenForcus;
        $this->isRelatedClass = clone $this->isRelatedClass;
        $this->timestamp = clone $this->timestamp;
        $this->banban = clone $this->banban;
        $this->vThirdAccounts = clone $this->vThirdAccounts;
        $this->canSetBanBanNo = clone $this->canSetBanBanNo;
        $this->userdesc = clone $this->userdesc;
        $this->vLabels = clone $this->vLabels;
    }

    public function __construct()
    {
        $this->user = new  TUser;
        $this->vChildrenMain = new  c_vector (new TChild);
        $this->vChildrenForcus = new  c_vector (new TChild);
        $this->isRelatedClass = new  c_short;
        $this->timestamp = new  c_int64;
        $this->banban = new  c_string;
        $this->vThirdAccounts = new  c_vector (new TThirdAccount);
        $this->canSetBanBanNo = new  c_short;
        $this->userdesc = new  c_string;
        $this->vLabels = new  c_vector (new TUserLabel);
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetTUser";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->user->write($_out,0);
        $this->vChildrenMain->write($_out,1);
        $this->vChildrenForcus->write($_out,2);
        $this->isRelatedClass->write($_out,3);
        $this->timestamp->write($_out,4);
        $this->banban->write($_out,5);
        $this->vThirdAccounts->write($_out,6);
        $this->canSetBanBanNo->write($_out,7);
        $this->userdesc->write($_out,8);
        $this->vLabels->write($_out,9);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->user->read($_in , 0, true);
        $this->vChildrenMain->read($_in , 1, false);
        $this->vChildrenForcus->read($_in , 2, false);
        $this->isRelatedClass->read($_in , 3, false);
        $this->timestamp->read($_in , 4, false);
        $this->banban->read($_in , 5, false);
        $this->vThirdAccounts->read($_in , 6, false);
        $this->canSetBanBanNo->read($_in , 7, false);
        $this->userdesc->read($_in , 8, false);
        $this->vLabels->read($_in , 9, false);
    }
}

class TRespGetEmergencySchoolClassTeacher extends c_struct
{
    public $vEmSCT;

    public function __clone()
    {
        $this->vEmSCT = clone $this->vEmSCT;
    }

    public function __construct()
    {
        $this->vEmSCT = new  c_vector (new TRecEmergencySchoolClassTeacherGroup);
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetEmergencySchoolClassTeacher";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vEmSCT->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vEmSCT->read($_in , 0, true);
    }
}

class TReqCreateOfficialAccount extends c_struct
{
    public $name;
    public $sex;
    public $teacherauth;
    public $photo;

    public function __clone()
    {
        $this->name = clone $this->name;
        $this->sex = clone $this->sex;
        $this->teacherauth = clone $this->teacherauth;
        $this->photo = clone $this->photo;
    }

    public function __construct()
    {
        $this->name = new  c_string;
        $this->sex = new  c_short;
        $this->teacherauth = new  c_short;
        $this->photo = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqCreateOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->name->write($_out,0);
        $this->sex->write($_out,1);
        $this->teacherauth->write($_out,2);
        $this->photo->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->name->read($_in , 0, true);
        $this->sex->read($_in , 1, true);
        $this->teacherauth->read($_in , 2, true);
        $this->photo->read($_in , 3, true);
    }
}

class TRespCreateOfficialAccount extends c_struct
{
    public $uid;

    public function __clone()
    {
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespCreateOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
    }
}

class TReqSetOfficialAccount extends c_struct
{
    public $uid;
    public $name;
    public $sex;
    public $teacherauth;
    public $photo;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->sex = clone $this->sex;
        $this->teacherauth = clone $this->teacherauth;
        $this->photo = clone $this->photo;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->sex = new  c_short;
        $this->teacherauth = new  c_short;
        $this->photo = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSetOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->sex->write($_out,2);
        $this->teacherauth->write($_out,3);
        $this->photo->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->sex->read($_in , 2, true);
        $this->teacherauth->read($_in , 3, true);
        $this->photo->read($_in , 4, true);
    }
}

class TReqDeleteOfficialAccount extends c_struct
{
    public $uid;

    public function __clone()
    {
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqDeleteOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
    }
}

class TReqApplyAuthTeacher extends c_struct
{
    public $uid;
    public $pic;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->pic = clone $this->pic;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->pic = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqApplyAuthTeacher";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->pic->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->pic->read($_in , 1, true);
    }
}

class TReqAuthTeacherApplication extends c_struct
{
    public $id;
    public $auditstatus;
    public $desc;

    public function __clone()
    {
        $this->id = clone $this->id;
        $this->auditstatus = clone $this->auditstatus;
        $this->desc = clone $this->desc;
    }

    public function __construct()
    {
        $this->id = new  c_int;
        $this->auditstatus = new  c_short;
        $this->desc = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqAuthTeacherApplication";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->id->write($_out,0);
        $this->auditstatus->write($_out,1);
        $this->desc->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->id->read($_in , 0, true);
        $this->auditstatus->read($_in , 1, true);
        $this->desc->read($_in , 2, true);
    }
}

class TReqGetAuthTeacherApplicationList extends c_struct
{
    public $pageNum;

    public function __clone()
    {
        $this->pageNum = clone $this->pageNum;
    }

    public function __construct()
    {
        $this->pageNum = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetAuthTeacherApplicationList";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->pageNum->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->pageNum->read($_in , 0, true);
    }
}

class TRespGetAuthTeacherApplicationList extends c_struct
{
    public $vATA;
    public $total;

    public function __clone()
    {
        $this->vATA = clone $this->vATA;
        $this->total = clone $this->total;
    }

    public function __construct()
    {
        $this->vATA = new  c_vector (new TAuthTeacherApplication);
        $this->total = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetAuthTeacherApplicationList";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vATA->write($_out,0);
        $this->total->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vATA->read($_in , 0, true);
        $this->total->read($_in , 1, true);
    }
}

class TSameNameChildInClass extends c_struct
{
    public $studentuid;
    public $photo;
    public $mobilephone;
    public $role;

    public function __clone()
    {
        $this->studentuid = clone $this->studentuid;
        $this->photo = clone $this->photo;
        $this->mobilephone = clone $this->mobilephone;
        $this->role = clone $this->role;
    }

    public function __construct()
    {
        $this->studentuid = new  c_string;
        $this->photo = new  c_string;
        $this->mobilephone = new  c_string;
        $this->role = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TSameNameChildInClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->studentuid->write($_out,0);
        $this->photo->write($_out,1);
        $this->mobilephone->write($_out,2);
        $this->role->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->studentuid->read($_in , 0, true);
        $this->photo->read($_in , 1, true);
        $this->mobilephone->read($_in , 2, true);
        $this->role->read($_in , 3, true);
    }
}

class TReqChildTestJoinClass extends c_struct
{
    public $studentuid;
    public $studentname;
    public $cid;

    public function __clone()
    {
        $this->studentuid = clone $this->studentuid;
        $this->studentname = clone $this->studentname;
        $this->cid = clone $this->cid;
    }

    public function __construct()
    {
        $this->studentuid = new  c_string;
        $this->studentname = new  c_string;
        $this->cid = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqChildTestJoinClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->studentuid->write($_out,0);
        $this->studentname->write($_out,1);
        $this->cid->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->studentuid->read($_in , 0, true);
        $this->studentname->read($_in , 1, true);
        $this->cid->read($_in , 2, true);
    }
}

class TRespChildTestJoinClass extends c_struct
{
    public $vSameNameStudent;

    public function __clone()
    {
        $this->vSameNameStudent = clone $this->vSameNameStudent;
    }

    public function __construct()
    {
        $this->vSameNameStudent = new  c_vector (new TSameNameChildInClass);
    }

    public function get_class_name()
    {
        return "Apollo.TRespChildTestJoinClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vSameNameStudent->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vSameNameStudent->read($_in , 0, true);
    }
}

class TReqFocusInChild extends c_struct
{
    public $childid;
    public $role;

    public function __clone()
    {
        $this->childid = clone $this->childid;
        $this->role = clone $this->role;
    }

    public function __construct()
    {
        $this->childid = new  c_string;
        $this->role = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqFocusInChild";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->childid->write($_out,0);
        $this->role->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->childid->read($_in , 0, true);
        $this->role->read($_in , 1, true);
    }
}

class TReqSetChildInfo extends c_struct
{
    public $uid;
    public $flag;
    public $photo;
    public $name;
    public $sex;
    public $role;
    public $birthday;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->flag = clone $this->flag;
        $this->photo = clone $this->photo;
        $this->name = clone $this->name;
        $this->sex = clone $this->sex;
        $this->role = clone $this->role;
        $this->birthday = clone $this->birthday;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->flag = new  c_int;
        $this->photo = new  c_string;
        $this->name = new  c_string;
        $this->sex = new  c_short;
        $this->role = new  c_string;
        $this->birthday = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSetChildInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->flag->write($_out,1);
        $this->photo->write($_out,2);
        $this->name->write($_out,3);
        $this->sex->write($_out,4);
        $this->role->write($_out,5);
        $this->birthday->write($_out,6);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->flag->read($_in , 1, true);
        $this->photo->read($_in , 2, true);
        $this->name->read($_in , 3, true);
        $this->sex->read($_in , 4, true);
        $this->role->read($_in , 5, true);
        $this->birthday->read($_in , 6, true);
    }
}

class TReqDelFocusChild extends c_struct
{
    public $childid;

    public function __clone()
    {
        $this->childid = clone $this->childid;
    }

    public function __construct()
    {
        $this->childid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqDelFocusChild";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->childid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->childid->read($_in , 0, true);
    }
}

class TReqDelChild extends c_struct
{
    public $childid;

    public function __clone()
    {
        $this->childid = clone $this->childid;
    }

    public function __construct()
    {
        $this->childid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqDelChild";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->childid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->childid->read($_in , 0, true);
    }
}

class TReqUnlockBindingAccount extends c_struct
{
    public $flag;

    public function __clone()
    {
        $this->flag = clone $this->flag;
    }

    public function __construct()
    {
        $this->flag = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqUnlockBindingAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->flag->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->flag->read($_in , 0, true);
    }
}

class TReqBindingThirdAccount extends c_struct
{
    public $flag;
    public $type;
    public $account;
    public $nick;
    public $photo;
    public $sex;

    public function __clone()
    {
        $this->flag = clone $this->flag;
        $this->type = clone $this->type;
        $this->account = clone $this->account;
        $this->nick = clone $this->nick;
        $this->photo = clone $this->photo;
        $this->sex = clone $this->sex;
    }

    public function __construct()
    {
        $this->flag = new  c_int;
        $this->type = new  c_int;
        $this->account = new  c_string;
        $this->nick = new  c_string;
        $this->photo = new  c_string;
        $this->sex = new  c_short;
    }

    public function get_class_name()
    {
        return "Apollo.TReqBindingThirdAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->flag->write($_out,0);
        $this->type->write($_out,1);
        $this->account->write($_out,2);
        $this->nick->write($_out,3);
        $this->photo->write($_out,4);
        $this->sex->write($_out,5);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->flag->read($_in , 0, true);
        $this->type->read($_in , 1, true);
        $this->account->read($_in , 2, true);
        $this->nick->read($_in , 3, true);
        $this->photo->read($_in , 4, true);
        $this->sex->read($_in , 5, true);
    }
}

class TReqSetBanBanNo extends c_struct
{
    public $uid;
    public $banbanno;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->banbanno = clone $this->banbanno;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->banbanno = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSetBanBanNo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->banbanno->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->banbanno->read($_in , 1, true);
    }
}

class TChildFocusUser extends c_struct
{
    public $uid;
    public $name;
    public $photo;
    public $role;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->photo = clone $this->photo;
        $this->role = clone $this->role;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->photo = new  c_string;
        $this->role = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TChildFocusUser";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->photo->write($_out,2);
        $this->role->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->photo->read($_in , 2, true);
        $this->role->read($_in , 3, true);
    }
}

class TReqGetChildFocusUser extends c_struct
{
    public $childUid;

    public function __clone()
    {
        $this->childUid = clone $this->childUid;
    }

    public function __construct()
    {
        $this->childUid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetChildFocusUser";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->childUid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->childUid->read($_in , 0, true);
    }
}

class TRespGetChildFocusUser extends c_struct
{
    public $vFocusUseres;
    public $maxCount;

    public function __clone()
    {
        $this->vFocusUseres = clone $this->vFocusUseres;
        $this->maxCount = clone $this->maxCount;
    }

    public function __construct()
    {
        $this->vFocusUseres = new  c_vector (new TChildFocusUser);
        $this->maxCount = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetChildFocusUser";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vFocusUseres->write($_out,0);
        $this->maxCount->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vFocusUseres->read($_in , 0, true);
        $this->maxCount->read($_in , 1, true);
    }
}

class TReqAddChildFocusUser extends c_struct
{
    public $childUid;
    public $mobilephone;
    public $role;

    public function __clone()
    {
        $this->childUid = clone $this->childUid;
        $this->mobilephone = clone $this->mobilephone;
        $this->role = clone $this->role;
    }

    public function __construct()
    {
        $this->childUid = new  c_string;
        $this->mobilephone = new  c_string;
        $this->role = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqAddChildFocusUser";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->childUid->write($_out,0);
        $this->mobilephone->write($_out,1);
        $this->role->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->childUid->read($_in , 0, true);
        $this->mobilephone->read($_in , 1, true);
        $this->role->read($_in , 2, true);
    }
}

class TRespAddChildFocusUser extends c_struct
{
    public $focusUser;

    public function __clone()
    {
        $this->focusUser = clone $this->focusUser;
    }

    public function __construct()
    {
        $this->focusUser = new  TChildFocusUser;
    }

    public function get_class_name()
    {
        return "Apollo.TRespAddChildFocusUser";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->focusUser->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->focusUser->read($_in , 0, true);
    }
}

class TChildSchoolAndClassInfo extends c_struct
{
    public $sid;
    public $schoolName;
    public $cid;
    public $cName;

    public function __clone()
    {
        $this->sid = clone $this->sid;
        $this->schoolName = clone $this->schoolName;
        $this->cid = clone $this->cid;
        $this->cName = clone $this->cName;
    }

    public function __construct()
    {
        $this->sid = new  c_int;
        $this->schoolName = new  c_string;
        $this->cid = new  c_int;
        $this->cName = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TChildSchoolAndClassInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sid->write($_out,0);
        $this->schoolName->write($_out,1);
        $this->cid->write($_out,2);
        $this->cName->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sid->read($_in , 0, true);
        $this->schoolName->read($_in , 1, true);
        $this->cid->read($_in , 2, true);
        $this->cName->read($_in , 3, true);
    }
}

class TRespGetChildInfo extends c_struct
{
    public $uid;
    public $name;
    public $photo;
    public $vSchoolAndClassesInfo;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->photo = clone $this->photo;
        $this->vSchoolAndClassesInfo = clone $this->vSchoolAndClassesInfo;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->photo = new  c_string;
        $this->vSchoolAndClassesInfo = new  c_vector (new TChildSchoolAndClassInfo);
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetChildInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->photo->write($_out,2);
        $this->vSchoolAndClassesInfo->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->photo->read($_in , 2, true);
        $this->vSchoolAndClassesInfo->read($_in , 3, true);
    }
}

class TReqDelChildFocusUser extends c_struct
{
    public $childid;
    public $focusUid;

    public function __clone()
    {
        $this->childid = clone $this->childid;
        $this->focusUid = clone $this->focusUid;
    }

    public function __construct()
    {
        $this->childid = new  c_string;
        $this->focusUid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqDelChildFocusUser";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->childid->write($_out,0);
        $this->focusUid->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->childid->read($_in , 0, true);
        $this->focusUid->read($_in , 1, true);
    }
}

class TReqEditLabel extends c_struct
{
    public $id;
    public $flag;
    public $userlabel;

    public function __clone()
    {
        $this->id = clone $this->id;
        $this->flag = clone $this->flag;
        $this->userlabel = clone $this->userlabel;
    }

    public function __construct()
    {
        $this->id = new  c_int;
        $this->flag = new  c_int;
        $this->userlabel = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqEditLabel";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->id->write($_out,0);
        $this->flag->write($_out,1);
        $this->userlabel->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->id->read($_in , 0, true);
        $this->flag->read($_in , 1, true);
        $this->userlabel->read($_in , 2, true);
    }
}

class TRespEditLabel extends c_struct
{
    public $id;

    public function __clone()
    {
        $this->id = clone $this->id;
    }

    public function __construct()
    {
        $this->id = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespEditLabel";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->id->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->id->read($_in , 0, true);
    }
}


?>