<?php

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************


require_once('jce.php');
class TReceiverObject extends c_struct
{
    public $iType;
    public $objectId;
    public $uid;

    public function __clone()
    {
        $this->iType = clone $this->iType;
        $this->objectId = clone $this->objectId;
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->iType = new  c_int;
        $this->objectId = new  c_string;
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReceiverObject";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->iType->write($_out,0);
        $this->objectId->write($_out,1);
        $this->uid->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->iType->read($_in , 0, true);
        $this->objectId->read($_in , 1, true);
        $this->uid->read($_in , 2, false);
    }
}

class TSubjectScore extends c_struct
{
    public $subject;
    public $score;

    public function __clone()
    {
        $this->subject = clone $this->subject;
        $this->score = clone $this->score;
    }

    public function __construct()
    {
        $this->subject = new  c_string;
        $this->score = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TSubjectScore";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->subject->write($_out,0);
        $this->score->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->subject->read($_in , 0, true);
        $this->score->read($_in , 1, true);
    }
}

class TScoreContent extends c_struct
{
    public $tagid;
    public $title;
    public $examine;
    public $timestamp;
    public $vSubjectScore;
    public $cid;

    public function __clone()
    {
        $this->tagid = clone $this->tagid;
        $this->title = clone $this->title;
        $this->examine = clone $this->examine;
        $this->timestamp = clone $this->timestamp;
        $this->vSubjectScore = clone $this->vSubjectScore;
        $this->cid = clone $this->cid;
    }

    public function __construct()
    {
        $this->tagid = new  c_string;
        $this->title = new  c_string;
        $this->examine = new  c_string;
        $this->timestamp = new  c_int64;
        $this->vSubjectScore = new  c_vector (new TSubjectScore);
        $this->cid = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TScoreContent";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->tagid->write($_out,0);
        $this->title->write($_out,1);
        $this->examine->write($_out,2);
        $this->timestamp->write($_out,3);
        $this->vSubjectScore->write($_out,4);
        $this->cid->write($_out,5);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->tagid->read($_in , 0, true);
        $this->title->read($_in , 1, true);
        $this->examine->read($_in , 2, true);
        $this->timestamp->read($_in , 3, true);
        $this->vSubjectScore->read($_in , 4, true);
        $this->cid->read($_in , 5, false);
    }
}

class TNoticeText extends c_struct
{
    public $content;
    public $vPhotos;
    public $vVoices;
    public $vScore;
    public $subject;
    public $actionUrl;
    public $actionText;

    public function __clone()
    {
        $this->content = clone $this->content;
        $this->vPhotos = clone $this->vPhotos;
        $this->vVoices = clone $this->vVoices;
        $this->vScore = clone $this->vScore;
        $this->subject = clone $this->subject;
        $this->actionUrl = clone $this->actionUrl;
        $this->actionText = clone $this->actionText;
    }

    public function __construct()
    {
        $this->content = new  c_string;
        $this->vPhotos = new  c_vector (new c_string);
        $this->vVoices = new  c_vector (new c_string);
        $this->vScore = new  c_vector (new TScoreContent);
        $this->subject = new  c_string;
        $this->actionUrl = new  c_string;
        $this->actionText = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TNoticeText";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->content->write($_out,0);
        $this->vPhotos->write($_out,1);
        $this->vVoices->write($_out,2);
        $this->vScore->write($_out,3);
        $this->subject->write($_out,4);
        $this->actionUrl->write($_out,5);
        $this->actionText->write($_out,6);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->content->read($_in , 0, true);
        $this->vPhotos->read($_in , 1, false);
        $this->vVoices->read($_in , 2, false);
        $this->vScore->read($_in , 3, false);
        $this->subject->read($_in , 4, false);
        $this->actionUrl->read($_in , 5, false);
        $this->actionText->read($_in , 6, false);
    }
}

class TNotice extends c_struct
{
    public $iNoticeId;
    public $sSenderId;
    public $sSenderPhoto;
    public $sSenderTitle;
    public $vReceiver;
    public $receiverTitle;
    public $iType;
    public $tContent;
    public $lSendTime;
    public $nPlatform;
    public $evalute;
    public $action;
    public $ReceiverNum;
    public $readedNum;
    public $index;
    public $isSendSms;
    public $schoolid;
    public $schoolName;
    public $teacherauth;

    public function __clone()
    {
        $this->iNoticeId = clone $this->iNoticeId;
        $this->sSenderId = clone $this->sSenderId;
        $this->sSenderPhoto = clone $this->sSenderPhoto;
        $this->sSenderTitle = clone $this->sSenderTitle;
        $this->vReceiver = clone $this->vReceiver;
        $this->receiverTitle = clone $this->receiverTitle;
        $this->iType = clone $this->iType;
        $this->tContent = clone $this->tContent;
        $this->lSendTime = clone $this->lSendTime;
        $this->nPlatform = clone $this->nPlatform;
        $this->evalute = clone $this->evalute;
        $this->action = clone $this->action;
        $this->ReceiverNum = clone $this->ReceiverNum;
        $this->readedNum = clone $this->readedNum;
        $this->index = clone $this->index;
        $this->isSendSms = clone $this->isSendSms;
        $this->schoolid = clone $this->schoolid;
        $this->schoolName = clone $this->schoolName;
        $this->teacherauth = clone $this->teacherauth;
    }

    public function __construct()
    {
        $this->iNoticeId = new  c_int64;
        $this->sSenderId = new  c_string;
        $this->sSenderPhoto = new  c_string;
        $this->sSenderTitle = new  c_string;
        $this->vReceiver = new  c_vector (new TReceiverObject);
        $this->receiverTitle = new  c_string;
        $this->iType = new  c_int;
        $this->tContent = new  TNoticeText;
        $this->lSendTime = new  c_int64;
        $this->nPlatform = new  c_int;
        $this->evalute = new  c_int;
        $this->action = new  c_int;
        $this->ReceiverNum = new  c_int;
        $this->readedNum = new  c_int;
        $this->index = new  c_int64;
        $this->isSendSms = new  c_int;
        $this->schoolid = new  c_int;
        $this->schoolName = new  c_string;
        $this->teacherauth = new  c_short;
    }

    public function get_class_name()
    {
        return "Apollo.TNotice";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->iNoticeId->write($_out,0);
        $this->sSenderId->write($_out,1);
        $this->sSenderPhoto->write($_out,2);
        $this->sSenderTitle->write($_out,3);
        $this->vReceiver->write($_out,4);
        $this->receiverTitle->write($_out,5);
        $this->iType->write($_out,6);
        $this->tContent->write($_out,7);
        $this->lSendTime->write($_out,8);
        $this->nPlatform->write($_out,9);
        $this->evalute->write($_out,10);
        $this->action->write($_out,11);
        $this->ReceiverNum->write($_out,12);
        $this->readedNum->write($_out,13);
        $this->index->write($_out,14);
        $this->isSendSms->write($_out,15);
        $this->schoolid->write($_out,16);
        $this->schoolName->write($_out,17);
        $this->teacherauth->write($_out,18);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->iNoticeId->read($_in , 0, true);
        $this->sSenderId->read($_in , 1, true);
        $this->sSenderPhoto->read($_in , 2, true);
        $this->sSenderTitle->read($_in , 3, true);
        $this->vReceiver->read($_in , 4, true);
        $this->receiverTitle->read($_in , 5, true);
        $this->iType->read($_in , 6, true);
        $this->tContent->read($_in , 7, true);
        $this->lSendTime->read($_in , 8, true);
        $this->nPlatform->read($_in , 9, true);
        $this->evalute->read($_in , 10, false);
        $this->action->read($_in , 11, false);
        $this->ReceiverNum->read($_in , 12, false);
        $this->readedNum->read($_in , 13, false);
        $this->index->read($_in , 14, false);
        $this->isSendSms->read($_in , 15, false);
        $this->schoolid->read($_in , 16, false);
        $this->schoolName->read($_in , 17, false);
        $this->teacherauth->read($_in , 18, false);
    }
}

class TSMSMsg extends c_struct
{
    public $smsid;
    public $sSenderId;
    public $sSenderPhoto;
    public $sSenderTitle;
    public $vReceiver;
    public $receiverTitle;
    public $iType;
    public $content;
    public $lSendTime;
    public $nPlatform;
    public $index;

    public function __clone()
    {
        $this->smsid = clone $this->smsid;
        $this->sSenderId = clone $this->sSenderId;
        $this->sSenderPhoto = clone $this->sSenderPhoto;
        $this->sSenderTitle = clone $this->sSenderTitle;
        $this->vReceiver = clone $this->vReceiver;
        $this->receiverTitle = clone $this->receiverTitle;
        $this->iType = clone $this->iType;
        $this->content = clone $this->content;
        $this->lSendTime = clone $this->lSendTime;
        $this->nPlatform = clone $this->nPlatform;
        $this->index = clone $this->index;
    }

    public function __construct()
    {
        $this->smsid = new  c_int64;
        $this->sSenderId = new  c_string;
        $this->sSenderPhoto = new  c_string;
        $this->sSenderTitle = new  c_string;
        $this->vReceiver = new  c_vector (new TReceiverObject);
        $this->receiverTitle = new  c_string;
        $this->iType = new  c_int;
        $this->content = new  c_string;
        $this->lSendTime = new  c_int64;
        $this->nPlatform = new  c_int;
        $this->index = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TSMSMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->smsid->write($_out,0);
        $this->sSenderId->write($_out,1);
        $this->sSenderPhoto->write($_out,2);
        $this->sSenderTitle->write($_out,3);
        $this->vReceiver->write($_out,4);
        $this->receiverTitle->write($_out,5);
        $this->iType->write($_out,6);
        $this->content->write($_out,7);
        $this->lSendTime->write($_out,8);
        $this->nPlatform->write($_out,9);
        $this->index->write($_out,10);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->smsid->read($_in , 0, true);
        $this->sSenderId->read($_in , 1, true);
        $this->sSenderPhoto->read($_in , 2, true);
        $this->sSenderTitle->read($_in , 3, true);
        $this->vReceiver->read($_in , 4, true);
        $this->receiverTitle->read($_in , 5, true);
        $this->iType->read($_in , 6, true);
        $this->content->read($_in , 7, true);
        $this->lSendTime->read($_in , 8, true);
        $this->nPlatform->read($_in , 9, true);
        $this->index->read($_in , 10, false);
    }
}

class TNoticeMessage extends c_struct
{
    public $iNoticeId;
    public $sSenderId;
    public $sSenderPhoto;
    public $sSenderTitle;
    public $sReceiverId;
    public $targteid;
    public $tagidName;
    public $targtePhoto;
    public $iType;
    public $tContent;
    public $lSendTime;
    public $index;
    public $read;
    public $evalute;
    public $action;
    public $teacherauth;

    public function __clone()
    {
        $this->iNoticeId = clone $this->iNoticeId;
        $this->sSenderId = clone $this->sSenderId;
        $this->sSenderPhoto = clone $this->sSenderPhoto;
        $this->sSenderTitle = clone $this->sSenderTitle;
        $this->sReceiverId = clone $this->sReceiverId;
        $this->targteid = clone $this->targteid;
        $this->tagidName = clone $this->tagidName;
        $this->targtePhoto = clone $this->targtePhoto;
        $this->iType = clone $this->iType;
        $this->tContent = clone $this->tContent;
        $this->lSendTime = clone $this->lSendTime;
        $this->index = clone $this->index;
        $this->read = clone $this->read;
        $this->evalute = clone $this->evalute;
        $this->action = clone $this->action;
        $this->teacherauth = clone $this->teacherauth;
    }

    public function __construct()
    {
        $this->iNoticeId = new  c_int64;
        $this->sSenderId = new  c_string;
        $this->sSenderPhoto = new  c_string;
        $this->sSenderTitle = new  c_string;
        $this->sReceiverId = new  c_string;
        $this->targteid = new  c_string;
        $this->tagidName = new  c_string;
        $this->targtePhoto = new  c_string;
        $this->iType = new  c_int;
        $this->tContent = new  TNoticeText;
        $this->lSendTime = new  c_int64;
        $this->index = new  c_int64;
        $this->read = new  c_int;
        $this->evalute = new  c_int;
        $this->action = new  c_int;
        $this->teacherauth = new  c_short;
    }

    public function get_class_name()
    {
        return "Apollo.TNoticeMessage";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->iNoticeId->write($_out,0);
        $this->sSenderId->write($_out,1);
        $this->sSenderPhoto->write($_out,2);
        $this->sSenderTitle->write($_out,3);
        $this->sReceiverId->write($_out,4);
        $this->targteid->write($_out,5);
        $this->tagidName->write($_out,6);
        $this->targtePhoto->write($_out,7);
        $this->iType->write($_out,8);
        $this->tContent->write($_out,9);
        $this->lSendTime->write($_out,10);
        $this->index->write($_out,11);
        $this->read->write($_out,12);
        $this->evalute->write($_out,13);
        $this->action->write($_out,14);
        $this->teacherauth->write($_out,15);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->iNoticeId->read($_in , 0, true);
        $this->sSenderId->read($_in , 1, true);
        $this->sSenderPhoto->read($_in , 2, true);
        $this->sSenderTitle->read($_in , 3, true);
        $this->sReceiverId->read($_in , 4, true);
        $this->targteid->read($_in , 5, true);
        $this->tagidName->read($_in , 6, true);
        $this->targtePhoto->read($_in , 7, true);
        $this->iType->read($_in , 8, true);
        $this->tContent->read($_in , 9, true);
        $this->lSendTime->read($_in , 10, true);
        $this->index->read($_in , 11, true);
        $this->read->read($_in , 12, false);
        $this->evalute->read($_in , 13, false);
        $this->action->read($_in , 14, false);
        $this->teacherauth->read($_in , 15, false);
    }
}

class TNoticeReadTime extends c_struct
{
    public $iNoticeId;
    public $readTime;
    public $userid;
    public $tagid;

    public function __clone()
    {
        $this->iNoticeId = clone $this->iNoticeId;
        $this->readTime = clone $this->readTime;
        $this->userid = clone $this->userid;
        $this->tagid = clone $this->tagid;
    }

    public function __construct()
    {
        $this->iNoticeId = new  c_int64;
        $this->readTime = new  c_int64;
        $this->userid = new  c_string;
        $this->tagid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TNoticeReadTime";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->iNoticeId->write($_out,0);
        $this->readTime->write($_out,1);
        $this->userid->write($_out,2);
        $this->tagid->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->iNoticeId->read($_in , 0, true);
        $this->readTime->read($_in , 1, true);
        $this->userid->read($_in , 2, true);
        $this->tagid->read($_in , 3, true);
    }
}

class TStudentInfo extends c_struct
{
    public $sid;
    public $vFamilys;
    public $name;
    public $photo;
    public $studentNumber;
    public $joinTime;
    public $icon;
    public $readTime;

    public function __clone()
    {
        $this->sid = clone $this->sid;
        $this->vFamilys = clone $this->vFamilys;
        $this->name = clone $this->name;
        $this->photo = clone $this->photo;
        $this->studentNumber = clone $this->studentNumber;
        $this->joinTime = clone $this->joinTime;
        $this->icon = clone $this->icon;
        $this->readTime = clone $this->readTime;
    }

    public function __construct()
    {
        $this->sid = new  c_string;
        $this->vFamilys = new  c_vector (new TFamily);
        $this->name = new  c_string;
        $this->photo = new  c_string;
        $this->studentNumber = new  c_string;
        $this->joinTime = new  c_string;
        $this->icon = new  c_int;
        $this->readTime = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TStudentInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sid->write($_out,0);
        $this->vFamilys->write($_out,1);
        $this->name->write($_out,2);
        $this->photo->write($_out,3);
        $this->studentNumber->write($_out,4);
        $this->joinTime->write($_out,5);
        $this->icon->write($_out,6);
        $this->readTime->write($_out,7);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sid->read($_in , 0, true);
        $this->vFamilys->read($_in , 1, false);
        $this->name->read($_in , 2, true);
        $this->photo->read($_in , 3, true);
        $this->studentNumber->read($_in , 4, false);
        $this->joinTime->read($_in , 5, false);
        $this->icon->read($_in , 6, false);
        $this->readTime->read($_in , 7, false);
    }
}

class TTeacherInfo extends c_struct
{
    public $uid;
    public $name;
    public $photo;
    public $type;
    public $sex;
    public $mobilePhone;
    public $subject;
    public $joinTime;
    public $icon;
    public $teacherauth;
    public $loginstatus;
    public $readTime;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->photo = clone $this->photo;
        $this->type = clone $this->type;
        $this->sex = clone $this->sex;
        $this->mobilePhone = clone $this->mobilePhone;
        $this->subject = clone $this->subject;
        $this->joinTime = clone $this->joinTime;
        $this->icon = clone $this->icon;
        $this->teacherauth = clone $this->teacherauth;
        $this->loginstatus = clone $this->loginstatus;
        $this->readTime = clone $this->readTime;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->photo = new  c_string;
        $this->type = new  c_int;
        $this->sex = new  c_int;
        $this->mobilePhone = new  c_string;
        $this->subject = new  c_string;
        $this->joinTime = new  c_string;
        $this->icon = new  c_int;
        $this->teacherauth = new  c_short;
        $this->loginstatus = new  c_int;
        $this->readTime = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TTeacherInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->photo->write($_out,2);
        $this->type->write($_out,3);
        $this->sex->write($_out,4);
        $this->mobilePhone->write($_out,5);
        $this->subject->write($_out,6);
        $this->joinTime->write($_out,7);
        $this->icon->write($_out,8);
        $this->teacherauth->write($_out,9);
        $this->loginstatus->write($_out,10);
        $this->readTime->write($_out,11);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->photo->read($_in , 2, false);
        $this->type->read($_in , 3, false);
        $this->sex->read($_in , 4, false);
        $this->mobilePhone->read($_in , 5, false);
        $this->subject->read($_in , 6, false);
        $this->joinTime->read($_in , 7, false);
        $this->icon->read($_in , 8, false);
        $this->teacherauth->read($_in , 9, false);
        $this->loginstatus->read($_in , 10, false);
        $this->readTime->read($_in , 11, false);
    }
}

class TReqSendNotice extends c_struct
{
    public $notice;

    public function __clone()
    {
        $this->notice = clone $this->notice;
    }

    public function __construct()
    {
        $this->notice = new  TNotice;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSendNotice";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->notice->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->notice->read($_in , 0, true);
    }
}

class TReqSendEurgencyNotice extends c_struct
{
    public $notice;

    public function __clone()
    {
        $this->notice = clone $this->notice;
    }

    public function __construct()
    {
        $this->notice = new  TNotice;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSendEurgencyNotice";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->notice->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->notice->read($_in , 0, true);
    }
}

class TRespSendEurgencyNotice extends c_struct
{
    public $result;
    public $sendSmsNum;
    public $surplusSmsNum;

    public function __clone()
    {
        $this->result = clone $this->result;
        $this->sendSmsNum = clone $this->sendSmsNum;
        $this->surplusSmsNum = clone $this->surplusSmsNum;
    }

    public function __construct()
    {
        $this->result = new  c_int;
        $this->sendSmsNum = new  c_int;
        $this->surplusSmsNum = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespSendEurgencyNotice";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->result->write($_out,0);
        $this->sendSmsNum->write($_out,1);
        $this->surplusSmsNum->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->result->read($_in , 0, true);
        $this->sendSmsNum->read($_in , 1, false);
        $this->surplusSmsNum->read($_in , 2, false);
    }
}

class TReqSendFixedTimeNotice extends c_struct
{
    public $notice;
    public $fixedTime;

    public function __clone()
    {
        $this->notice = clone $this->notice;
        $this->fixedTime = clone $this->fixedTime;
    }

    public function __construct()
    {
        $this->notice = new  TNotice;
        $this->fixedTime = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSendFixedTimeNotice";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->notice->write($_out,0);
        $this->fixedTime->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->notice->read($_in , 0, true);
        $this->fixedTime->read($_in , 1, true);
    }
}

class TReqAckNoticeStatus extends c_struct
{
    public $noticeid;
    public $uid;
    public $tagid;
    public $flag;

    public function __clone()
    {
        $this->noticeid = clone $this->noticeid;
        $this->uid = clone $this->uid;
        $this->tagid = clone $this->tagid;
        $this->flag = clone $this->flag;
    }

    public function __construct()
    {
        $this->noticeid = new  c_string;
        $this->uid = new  c_string;
        $this->tagid = new  c_string;
        $this->flag = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqAckNoticeStatus";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->noticeid->write($_out,0);
        $this->uid->write($_out,1);
        $this->tagid->write($_out,2);
        $this->flag->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->noticeid->read($_in , 0, true);
        $this->uid->read($_in , 1, true);
        $this->tagid->read($_in , 2, true);
        $this->flag->read($_in , 3, true);
    }
}

class TReqBatchAckNoticeStatus extends c_struct
{
    public $uid;

    public function __clone()
    {
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqBatchAckNoticeStatus";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
    }
}

class TReqGetNoticeSendDetail extends c_struct
{
    public $noticeid;

    public function __clone()
    {
        $this->noticeid = clone $this->noticeid;
    }

    public function __construct()
    {
        $this->noticeid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetNoticeSendDetail";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->noticeid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->noticeid->read($_in , 0, true);
    }
}

class TRespGetNoticeSendDetail extends c_struct
{
    public $teacherRead;
    public $teacherUnread;
    public $studentRead;
    public $studentUnread;
    public $totalStudent;
    public $readTime;

    public function __clone()
    {
        $this->teacherRead = clone $this->teacherRead;
        $this->teacherUnread = clone $this->teacherUnread;
        $this->studentRead = clone $this->studentRead;
        $this->studentUnread = clone $this->studentUnread;
        $this->totalStudent = clone $this->totalStudent;
        $this->readTime = clone $this->readTime;
    }

    public function __construct()
    {
        $this->teacherRead = new  c_vector (new TTeacher);
        $this->teacherUnread = new  c_vector (new TTeacher);
        $this->studentRead = new  c_vector (new TStudent);
        $this->studentUnread = new  c_vector (new TStudent);
        $this->totalStudent = new  c_int;
        $this->readTime = new  c_vector (new TNoticeReadTime);
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetNoticeSendDetail";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->teacherRead->write($_out,0);
        $this->teacherUnread->write($_out,1);
        $this->studentRead->write($_out,2);
        $this->studentUnread->write($_out,3);
        $this->totalStudent->write($_out,4);
        $this->readTime->write($_out,5);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->teacherRead->read($_in , 0, true);
        $this->teacherUnread->read($_in , 1, true);
        $this->studentRead->read($_in , 2, true);
        $this->studentUnread->read($_in , 3, true);
        $this->totalStudent->read($_in , 4, false);
        $this->readTime->read($_in , 5, false);
    }
}

class TReqAppSendNoticeDetail extends c_struct
{
    public $noticeid;

    public function __clone()
    {
        $this->noticeid = clone $this->noticeid;
    }

    public function __construct()
    {
        $this->noticeid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqAppSendNoticeDetail";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->noticeid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->noticeid->read($_in , 0, true);
    }
}

class TRespAppSendNoticeDetail extends c_struct
{
    public $teacherRead;
    public $teacherUnread;
    public $studentRead;
    public $studentUnread;
    public $totalStudent;
    public $readTime;

    public function __clone()
    {
        $this->teacherRead = clone $this->teacherRead;
        $this->teacherUnread = clone $this->teacherUnread;
        $this->studentRead = clone $this->studentRead;
        $this->studentUnread = clone $this->studentUnread;
        $this->totalStudent = clone $this->totalStudent;
        $this->readTime = clone $this->readTime;
    }

    public function __construct()
    {
        $this->teacherRead = new  c_vector (new TTeacher);
        $this->teacherUnread = new  c_vector (new TTeacher);
        $this->studentRead = new  c_vector (new TStudent);
        $this->studentUnread = new  c_vector (new TStudent);
        $this->totalStudent = new  c_int;
        $this->readTime = new  c_vector (new TNoticeReadTime);
    }

    public function get_class_name()
    {
        return "Apollo.TRespAppSendNoticeDetail";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->teacherRead->write($_out,0);
        $this->teacherUnread->write($_out,1);
        $this->studentRead->write($_out,2);
        $this->studentUnread->write($_out,3);
        $this->totalStudent->write($_out,4);
        $this->readTime->write($_out,5);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->teacherRead->read($_in , 0, true);
        $this->teacherUnread->read($_in , 1, true);
        $this->studentRead->read($_in , 2, true);
        $this->studentUnread->read($_in , 3, true);
        $this->totalStudent->read($_in , 4, false);
        $this->readTime->read($_in , 5, false);
    }
}

class TReqClientGetNoticeSendDetail extends c_struct
{
    public $noticeid;

    public function __clone()
    {
        $this->noticeid = clone $this->noticeid;
    }

    public function __construct()
    {
        $this->noticeid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqClientGetNoticeSendDetail";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->noticeid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->noticeid->read($_in , 0, true);
    }
}

class TRespClientSendNoticeDetail extends c_struct
{
    public $teacherRead;
    public $teacherUnread;
    public $studentRead;
    public $studentUnread;
    public $totalStudent;

    public function __clone()
    {
        $this->teacherRead = clone $this->teacherRead;
        $this->teacherUnread = clone $this->teacherUnread;
        $this->studentRead = clone $this->studentRead;
        $this->studentUnread = clone $this->studentUnread;
        $this->totalStudent = clone $this->totalStudent;
    }

    public function __construct()
    {
        $this->teacherRead = new  c_vector (new TTeacherInfo);
        $this->teacherUnread = new  c_vector (new TTeacher);
        $this->studentRead = new  c_vector (new TStudentInfo);
        $this->studentUnread = new  c_vector (new TStudent);
        $this->totalStudent = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespClientSendNoticeDetail";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->teacherRead->write($_out,0);
        $this->teacherUnread->write($_out,1);
        $this->studentRead->write($_out,2);
        $this->studentUnread->write($_out,3);
        $this->totalStudent->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->teacherRead->read($_in , 0, true);
        $this->teacherUnread->read($_in , 1, true);
        $this->studentRead->read($_in , 2, true);
        $this->studentUnread->read($_in , 3, true);
        $this->totalStudent->read($_in , 4, false);
    }
}

class TReqGetNoticeMsg extends c_struct
{
    public $index;
    public $targetid;
    public $flag;
    public $uid;

    public function __clone()
    {
        $this->index = clone $this->index;
        $this->targetid = clone $this->targetid;
        $this->flag = clone $this->flag;
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->index = new  c_int64;
        $this->targetid = new  c_string;
        $this->flag = new  c_int;
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetNoticeMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->index->write($_out,0);
        $this->targetid->write($_out,1);
        $this->flag->write($_out,2);
        $this->uid->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->index->read($_in , 0, true);
        $this->targetid->read($_in , 1, true);
        $this->flag->read($_in , 2, true);
        $this->uid->read($_in , 3, true);
    }
}

class TRespGetNoticeMsg extends c_struct
{
    public $vNoticeMsg;
    public $count;
    public $total;

    public function __clone()
    {
        $this->vNoticeMsg = clone $this->vNoticeMsg;
        $this->count = clone $this->count;
        $this->total = clone $this->total;
    }

    public function __construct()
    {
        $this->vNoticeMsg = new  c_vector (new TNoticeMessage);
        $this->count = new  c_int;
        $this->total = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetNoticeMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vNoticeMsg->write($_out,0);
        $this->count->write($_out,1);
        $this->total->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vNoticeMsg->read($_in , 0, true);
        $this->count->read($_in , 1, true);
        $this->total->read($_in , 2, true);
    }
}

class TReqGetSendedSMS extends c_struct
{
    public $index;
    public $flag;
    public $uid;

    public function __clone()
    {
        $this->index = clone $this->index;
        $this->flag = clone $this->flag;
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->index = new  c_int64;
        $this->flag = new  c_int;
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetSendedSMS";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->index->write($_out,0);
        $this->flag->write($_out,1);
        $this->uid->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->index->read($_in , 0, true);
        $this->flag->read($_in , 1, true);
        $this->uid->read($_in , 2, true);
    }
}

class TRespGetSendedSMS extends c_struct
{
    public $vSMSMsg;
    public $total;

    public function __clone()
    {
        $this->vSMSMsg = clone $this->vSMSMsg;
        $this->total = clone $this->total;
    }

    public function __construct()
    {
        $this->vSMSMsg = new  c_vector (new TSMSMsg);
        $this->total = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetSendedSMS";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vSMSMsg->write($_out,0);
        $this->total->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vSMSMsg->read($_in , 0, true);
        $this->total->read($_in , 1, true);
    }
}

class TReqGetSingleNoticeMsg extends c_struct
{
    public $noticeid;
    public $index;
    public $targetid;
    public $uid;

    public function __clone()
    {
        $this->noticeid = clone $this->noticeid;
        $this->index = clone $this->index;
        $this->targetid = clone $this->targetid;
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->noticeid = new  c_int64;
        $this->index = new  c_int64;
        $this->targetid = new  c_string;
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetSingleNoticeMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->noticeid->write($_out,0);
        $this->index->write($_out,1);
        $this->targetid->write($_out,2);
        $this->uid->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->noticeid->read($_in , 0, true);
        $this->index->read($_in , 1, true);
        $this->targetid->read($_in , 2, true);
        $this->uid->read($_in , 3, true);
    }
}

class TRespGetSingleNoticeMsg extends c_struct
{
    public $NoticeMsg;

    public function __clone()
    {
        $this->NoticeMsg = clone $this->NoticeMsg;
    }

    public function __construct()
    {
        $this->NoticeMsg = new  TNoticeMessage;
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetSingleNoticeMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->NoticeMsg->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->NoticeMsg->read($_in , 0, true);
    }
}

class TReqGetSendedNotices extends c_struct
{
    public $flag;
    public $index;
    public $uid;
    public $clientType;

    public function __clone()
    {
        $this->flag = clone $this->flag;
        $this->index = clone $this->index;
        $this->uid = clone $this->uid;
        $this->clientType = clone $this->clientType;
    }

    public function __construct()
    {
        $this->flag = new  c_int;
        $this->index = new  c_int64;
        $this->uid = new  c_string;
        $this->clientType = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetSendedNotices";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->flag->write($_out,0);
        $this->index->write($_out,1);
        $this->uid->write($_out,2);
        $this->clientType->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->flag->read($_in , 0, true);
        $this->index->read($_in , 1, true);
        $this->uid->read($_in , 2, true);
        $this->clientType->read($_in , 3, true);
    }
}

class TRespGetSendedNotices extends c_struct
{
    public $vNotice;
    public $total;

    public function __clone()
    {
        $this->vNotice = clone $this->vNotice;
        $this->total = clone $this->total;
    }

    public function __construct()
    {
        $this->vNotice = new  c_vector (new TNotice);
        $this->total = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetSendedNotices";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vNotice->write($_out,0);
        $this->total->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vNotice->read($_in , 0, true);
        $this->total->read($_in , 1, true);
    }
}

class TReqGetSingleSendedNotice extends c_struct
{
    public $noticeid;
    public $index;
    public $uid;
    public $clientType;

    public function __clone()
    {
        $this->noticeid = clone $this->noticeid;
        $this->index = clone $this->index;
        $this->uid = clone $this->uid;
        $this->clientType = clone $this->clientType;
    }

    public function __construct()
    {
        $this->noticeid = new  c_int64;
        $this->index = new  c_int64;
        $this->uid = new  c_string;
        $this->clientType = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetSingleSendedNotice";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->noticeid->write($_out,0);
        $this->index->write($_out,1);
        $this->uid->write($_out,2);
        $this->clientType->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->noticeid->read($_in , 0, true);
        $this->index->read($_in , 1, true);
        $this->uid->read($_in , 2, true);
        $this->clientType->read($_in , 3, true);
    }
}

class TRespGetSingleSendedNotice extends c_struct
{
    public $notice;

    public function __clone()
    {
        $this->notice = clone $this->notice;
    }

    public function __construct()
    {
        $this->notice = new  TNotice;
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetSingleSendedNotice";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->notice->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->notice->read($_in , 0, true);
    }
}

class TNoticeMessageBox extends c_struct
{
    public $count;
    public $total;
    public $vNoticeMsgs;
    public $targeterid;

    public function __clone()
    {
        $this->count = clone $this->count;
        $this->total = clone $this->total;
        $this->vNoticeMsgs = clone $this->vNoticeMsgs;
        $this->targeterid = clone $this->targeterid;
    }

    public function __construct()
    {
        $this->count = new  c_int;
        $this->total = new  c_int;
        $this->vNoticeMsgs = new  c_vector (new TNoticeMessage);
        $this->targeterid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TNoticeMessageBox";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->count->write($_out,0);
        $this->total->write($_out,1);
        $this->vNoticeMsgs->write($_out,2);
        $this->targeterid->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->count->read($_in , 0, true);
        $this->total->read($_in , 1, true);
        $this->vNoticeMsgs->read($_in , 2, true);
        $this->targeterid->read($_in , 3, true);
    }
}

class TReqGetNoticeboxs extends c_struct
{
    public $uid;
    public $vChild;
    public $flag;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->vChild = clone $this->vChild;
        $this->flag = clone $this->flag;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->vChild = new  c_vector (new c_string);
        $this->flag = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetNoticeboxs";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->vChild->write($_out,1);
        $this->flag->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->vChild->read($_in , 1, true);
        $this->flag->read($_in , 2, false);
    }
}

class TRespGetNoticeboxs extends c_struct
{
    public $vNoticeboxs;

    public function __clone()
    {
        $this->vNoticeboxs = clone $this->vNoticeboxs;
    }

    public function __construct()
    {
        $this->vNoticeboxs = new  c_vector (new TNoticeMessageBox);
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetNoticeboxs";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vNoticeboxs->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vNoticeboxs->read($_in , 0, true);
    }
}

class TReqPushNoticeboxs extends c_struct
{
    public $vNoticeBoxs;

    public function __clone()
    {
        $this->vNoticeBoxs = clone $this->vNoticeBoxs;
    }

    public function __construct()
    {
        $this->vNoticeBoxs = new  c_vector (new TNoticeMessageBox);
    }

    public function get_class_name()
    {
        return "Apollo.TReqPushNoticeboxs";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vNoticeBoxs->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vNoticeBoxs->read($_in , 0, true);
    }
}

class TClientReceiveNoticeIndex extends c_struct
{
    public $targeterid;
    public $index;
    public $uid;

    public function __clone()
    {
        $this->targeterid = clone $this->targeterid;
        $this->index = clone $this->index;
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->targeterid = new  c_string;
        $this->index = new  c_int64;
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TClientReceiveNoticeIndex";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->targeterid->write($_out,0);
        $this->index->write($_out,1);
        $this->uid->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->targeterid->read($_in , 0, true);
        $this->index->read($_in , 1, true);
        $this->uid->read($_in , 2, true);
    }
}

class TRespPushNoticeboxs extends c_struct
{
    public $vrespIndex;

    public function __clone()
    {
        $this->vrespIndex = clone $this->vrespIndex;
    }

    public function __construct()
    {
        $this->vrespIndex = new  c_vector (new TClientReceiveNoticeIndex);
    }

    public function get_class_name()
    {
        return "Apollo.TRespPushNoticeboxs";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vrespIndex->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vrespIndex->read($_in , 0, true);
    }
}

class SystemNoticeReceiveObject extends c_struct
{
    public $uid;
    public $tagid;
    public $tagidName;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->tagid = clone $this->tagid;
        $this->tagidName = clone $this->tagidName;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->tagid = new  c_string;
        $this->tagidName = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.SystemNoticeReceiveObject";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->tagid->write($_out,1);
        $this->tagidName->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->tagid->read($_in , 1, true);
        $this->tagidName->read($_in , 2, false);
    }
}

class TReqSendSystemNotice extends c_struct
{
    public $uid;
    public $childId;
    public $childName;
    public $cid;
    public $cidName;
    public $type;
    public $senderId;
    public $senderIdName;
    public $senderPhoto;
    public $nPlatform;
    public $vObject;
    public $subject;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->childId = clone $this->childId;
        $this->childName = clone $this->childName;
        $this->cid = clone $this->cid;
        $this->cidName = clone $this->cidName;
        $this->type = clone $this->type;
        $this->senderId = clone $this->senderId;
        $this->senderIdName = clone $this->senderIdName;
        $this->senderPhoto = clone $this->senderPhoto;
        $this->nPlatform = clone $this->nPlatform;
        $this->vObject = clone $this->vObject;
        $this->subject = clone $this->subject;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->childId = new  c_string;
        $this->childName = new  c_string;
        $this->cid = new  c_int;
        $this->cidName = new  c_string;
        $this->type = new  c_int;
        $this->senderId = new  c_string;
        $this->senderIdName = new  c_string;
        $this->senderPhoto = new  c_string;
        $this->nPlatform = new  c_int;
        $this->vObject = new  c_vector (new SystemNoticeReceiveObject);
        $this->subject = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSendSystemNotice";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->childId->write($_out,1);
        $this->childName->write($_out,2);
        $this->cid->write($_out,3);
        $this->cidName->write($_out,4);
        $this->type->write($_out,5);
        $this->senderId->write($_out,6);
        $this->senderIdName->write($_out,7);
        $this->senderPhoto->write($_out,8);
        $this->nPlatform->write($_out,9);
        $this->vObject->write($_out,10);
        $this->subject->write($_out,11);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->childId->read($_in , 1, false);
        $this->childName->read($_in , 2, false);
        $this->cid->read($_in , 3, true);
        $this->cidName->read($_in , 4, true);
        $this->type->read($_in , 5, true);
        $this->senderId->read($_in , 6, true);
        $this->senderIdName->read($_in , 7, true);
        $this->senderPhoto->read($_in , 8, true);
        $this->nPlatform->read($_in , 9, true);
        $this->vObject->read($_in , 10, false);
        $this->subject->read($_in , 11, false);
    }
}


?>