<?php

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OfficialAccount.jce'
// **********************************************************************


require_once('jce.php');
class TOfficialAccount extends c_struct
{
    public $openId;
    public $name;
    public $type;
    public $description;
    public $logo;
    public $block;
    public $officialAccountId;
    public $sendLevel;
    public $phone;
    public $createTime;
    public $status;
    public $reason;

    public function __clone()
    {
        $this->openId = clone $this->openId;
        $this->name = clone $this->name;
        $this->type = clone $this->type;
        $this->description = clone $this->description;
        $this->logo = clone $this->logo;
        $this->block = clone $this->block;
        $this->officialAccountId = clone $this->officialAccountId;
        $this->sendLevel = clone $this->sendLevel;
        $this->phone = clone $this->phone;
        $this->createTime = clone $this->createTime;
        $this->status = clone $this->status;
        $this->reason = clone $this->reason;
    }

    public function __construct()
    {
        $this->openId = new  c_string;
        $this->name = new  c_string;
        $this->type = new  c_int;
        $this->description = new  c_string;
        $this->logo = new  c_string;
        $this->block = new  c_int;
        $this->officialAccountId = new  c_int64;
        $this->sendLevel = new  c_string;
        $this->phone = new  c_string;
        $this->createTime = new  c_string;
        $this->status = new  c_int;
        $this->reason = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->openId->write($_out,0);
        $this->name->write($_out,1);
        $this->type->write($_out,2);
        $this->description->write($_out,3);
        $this->logo->write($_out,4);
        $this->block->write($_out,5);
        $this->officialAccountId->write($_out,6);
        $this->sendLevel->write($_out,7);
        $this->phone->write($_out,8);
        $this->createTime->write($_out,9);
        $this->status->write($_out,10);
        $this->reason->write($_out,11);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->openId->read($_in , 0, false);
        $this->name->read($_in , 1, true);
        $this->type->read($_in , 2, true);
        $this->description->read($_in , 3, true);
        $this->logo->read($_in , 4, true);
        $this->block->read($_in , 5, false);
        $this->officialAccountId->read($_in , 6, false);
        $this->sendLevel->read($_in , 7, false);
        $this->phone->read($_in , 8, false);
        $this->createTime->read($_in , 9, false);
        $this->status->read($_in , 10, false);
        $this->reason->read($_in , 11, false);
    }
}

class TOfficialAccountContentItem extends c_struct
{
    public $type;
    public $content;
    public $width;
    public $height;

    public function __clone()
    {
        $this->type = clone $this->type;
        $this->content = clone $this->content;
        $this->width = clone $this->width;
        $this->height = clone $this->height;
    }

    public function __construct()
    {
        $this->type = new  c_string;
        $this->content = new  c_string;
        $this->width = new  c_int;
        $this->height = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TOfficialAccountContentItem";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->type->write($_out,0);
        $this->content->write($_out,1);
        $this->width->write($_out,2);
        $this->height->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->type->read($_in , 0, true);
        $this->content->read($_in , 1, true);
        $this->width->read($_in , 2, true);
        $this->height->read($_in , 3, true);
    }
}

class TOfficialAccountContentObject extends c_struct
{
    public $vContentItem;

    public function __clone()
    {
        $this->vContentItem = clone $this->vContentItem;
    }

    public function __construct()
    {
        $this->vContentItem = new  c_vector (new TOfficialAccountContentItem);
    }

    public function get_class_name()
    {
        return "Apollo.TOfficialAccountContentObject";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vContentItem->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vContentItem->read($_in , 0, true);
    }
}

class TOfficialAccountMsg extends c_struct
{
    public $mId;
    public $logo;
    public $name;
    public $title;
    public $subhead;
    public $cover;
    public $msgfrom;
    public $officialAccountId;
    public $viewCount;
    public $likeCount;
    public $pokeCount;
    public $status;
    public $publishTime;
    public $auth;
    public $numberId;
    public $publishStatus;
    public $fixedPublishTime;
    public $close;
    public $openId;
    public $createTime;
    public $Byinfoid;
    public $transmitTime;
    public $transmitLogo;

    public function __clone()
    {
        $this->mId = clone $this->mId;
        $this->logo = clone $this->logo;
        $this->name = clone $this->name;
        $this->title = clone $this->title;
        $this->subhead = clone $this->subhead;
        $this->cover = clone $this->cover;
        $this->msgfrom = clone $this->msgfrom;
        $this->officialAccountId = clone $this->officialAccountId;
        $this->viewCount = clone $this->viewCount;
        $this->likeCount = clone $this->likeCount;
        $this->pokeCount = clone $this->pokeCount;
        $this->status = clone $this->status;
        $this->publishTime = clone $this->publishTime;
        $this->auth = clone $this->auth;
        $this->numberId = clone $this->numberId;
        $this->publishStatus = clone $this->publishStatus;
        $this->fixedPublishTime = clone $this->fixedPublishTime;
        $this->close = clone $this->close;
        $this->openId = clone $this->openId;
        $this->createTime = clone $this->createTime;
        $this->Byinfoid = clone $this->Byinfoid;
        $this->transmitTime = clone $this->transmitTime;
        $this->transmitLogo = clone $this->transmitLogo;
    }

    public function __construct()
    {
        $this->mId = new  c_string;
        $this->logo = new  c_string;
        $this->name = new  c_string;
        $this->title = new  c_string;
        $this->subhead = new  c_string;
        $this->cover = new  c_string;
        $this->msgfrom = new  c_string;
        $this->officialAccountId = new  c_int64;
        $this->viewCount = new  c_int;
        $this->likeCount = new  c_int;
        $this->pokeCount = new  c_int;
        $this->status = new  c_int;
        $this->publishTime = new  c_string;
        $this->auth = new  c_string;
        $this->numberId = new  c_string;
        $this->publishStatus = new  c_int;
        $this->fixedPublishTime = new  c_string;
        $this->close = new  c_int;
        $this->openId = new  c_string;
        $this->createTime = new  c_string;
        $this->Byinfoid = new  c_int64;
        $this->transmitTime = new  c_string;
        $this->transmitLogo = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mId->write($_out,0);
        $this->logo->write($_out,1);
        $this->name->write($_out,2);
        $this->title->write($_out,3);
        $this->subhead->write($_out,4);
        $this->cover->write($_out,5);
        $this->msgfrom->write($_out,6);
        $this->officialAccountId->write($_out,7);
        $this->viewCount->write($_out,8);
        $this->likeCount->write($_out,9);
        $this->pokeCount->write($_out,10);
        $this->status->write($_out,11);
        $this->publishTime->write($_out,12);
        $this->auth->write($_out,13);
        $this->numberId->write($_out,14);
        $this->publishStatus->write($_out,15);
        $this->fixedPublishTime->write($_out,16);
        $this->close->write($_out,17);
        $this->openId->write($_out,18);
        $this->createTime->write($_out,19);
        $this->Byinfoid->write($_out,20);
        $this->transmitTime->write($_out,21);
        $this->transmitLogo->write($_out,22);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mId->read($_in , 0, false);
        $this->logo->read($_in , 1, true);
        $this->name->read($_in , 2, true);
        $this->title->read($_in , 3, true);
        $this->subhead->read($_in , 4, true);
        $this->cover->read($_in , 5, true);
        $this->msgfrom->read($_in , 6, true);
        $this->officialAccountId->read($_in , 7, true);
        $this->viewCount->read($_in , 8, true);
        $this->likeCount->read($_in , 9, true);
        $this->pokeCount->read($_in , 10, true);
        $this->status->read($_in , 11, true);
        $this->publishTime->read($_in , 12, true);
        $this->auth->read($_in , 13, true);
        $this->numberId->read($_in , 14, false);
        $this->publishStatus->read($_in , 15, false);
        $this->fixedPublishTime->read($_in , 16, false);
        $this->close->read($_in , 17, false);
        $this->openId->read($_in , 18, false);
        $this->createTime->read($_in , 19, false);
        $this->Byinfoid->read($_in , 20, false);
        $this->transmitTime->read($_in , 21, false);
        $this->transmitLogo->read($_in , 22, false);
    }
}

class TOfficialAccountMsgContent extends c_struct
{
    public $mId;
    public $content;
    public $reason;
    public $viewCount;
    public $likeCount;
    public $pokeCount;
    public $close;
    public $status;

    public function __clone()
    {
        $this->mId = clone $this->mId;
        $this->content = clone $this->content;
        $this->reason = clone $this->reason;
        $this->viewCount = clone $this->viewCount;
        $this->likeCount = clone $this->likeCount;
        $this->pokeCount = clone $this->pokeCount;
        $this->close = clone $this->close;
        $this->status = clone $this->status;
    }

    public function __construct()
    {
        $this->mId = new  c_string;
        $this->content = new  TOfficialAccountContentObject;
        $this->reason = new  c_string;
        $this->viewCount = new  c_int;
        $this->likeCount = new  c_int;
        $this->pokeCount = new  c_int;
        $this->close = new  c_int;
        $this->status = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TOfficialAccountMsgContent";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mId->write($_out,0);
        $this->content->write($_out,1);
        $this->reason->write($_out,2);
        $this->viewCount->write($_out,3);
        $this->likeCount->write($_out,4);
        $this->pokeCount->write($_out,5);
        $this->close->write($_out,6);
        $this->status->write($_out,7);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mId->read($_in , 0, false);
        $this->content->read($_in , 1, true);
        $this->reason->read($_in , 2, false);
        $this->viewCount->read($_in , 3, false);
        $this->likeCount->read($_in , 4, false);
        $this->pokeCount->read($_in , 5, false);
        $this->close->read($_in , 6, false);
        $this->status->read($_in , 7, false);
    }
}

class TQueryOfficialAccountMsgCondition extends c_struct
{
    public $send;
    public $title;
    public $close;
    public $openId;
    public $page;
    public $pageSize;

    public function __clone()
    {
        $this->send = clone $this->send;
        $this->title = clone $this->title;
        $this->close = clone $this->close;
        $this->openId = clone $this->openId;
        $this->page = clone $this->page;
        $this->pageSize = clone $this->pageSize;
    }

    public function __construct()
    {
        $this->send = new  c_int;
        $this->title = new  c_string;
        $this->close = new  c_int;
        $this->openId = new  c_string;
        $this->page = new  c_int;
        $this->pageSize = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TQueryOfficialAccountMsgCondition";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->send->write($_out,0);
        $this->title->write($_out,1);
        $this->close->write($_out,2);
        $this->openId->write($_out,3);
        $this->page->write($_out,4);
        $this->pageSize->write($_out,5);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->send->read($_in , 0, true);
        $this->title->read($_in , 1, true);
        $this->close->read($_in , 2, true);
        $this->openId->read($_in , 3, false);
        $this->page->read($_in , 4, false);
        $this->pageSize->read($_in , 5, false);
    }
}

class TQueryOfficialAccountCondition extends c_struct
{
    public $type;
    public $name;
    public $openId;
    public $close;
    public $officialAccountId;
    public $page;
    public $pageSize;

    public function __clone()
    {
        $this->type = clone $this->type;
        $this->name = clone $this->name;
        $this->openId = clone $this->openId;
        $this->close = clone $this->close;
        $this->officialAccountId = clone $this->officialAccountId;
        $this->page = clone $this->page;
        $this->pageSize = clone $this->pageSize;
    }

    public function __construct()
    {
        $this->type = new  c_int;
        $this->name = new  c_string;
        $this->openId = new  c_string;
        $this->close = new  c_int;
        $this->officialAccountId = new  c_int64;
        $this->page = new  c_int;
        $this->pageSize = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TQueryOfficialAccountCondition";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->type->write($_out,0);
        $this->name->write($_out,1);
        $this->openId->write($_out,2);
        $this->close->write($_out,3);
        $this->officialAccountId->write($_out,4);
        $this->page->write($_out,5);
        $this->pageSize->write($_out,6);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->type->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->openId->read($_in , 2, true);
        $this->close->read($_in , 3, true);
        $this->officialAccountId->read($_in , 4, false);
        $this->page->read($_in , 5, false);
        $this->pageSize->read($_in , 6, false);
    }
}

class TReqOfficialAccount extends c_struct
{
    public $flag;
    public $sMateField;

    public function __clone()
    {
        $this->flag = clone $this->flag;
        $this->sMateField = clone $this->sMateField;
    }

    public function __construct()
    {
        $this->flag = new  c_int;
        $this->sMateField = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->flag->write($_out,0);
        $this->sMateField->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->flag->read($_in , 0, true);
        $this->sMateField->read($_in , 1, false);
    }
}

class TRespOfficialAccount extends c_struct
{
    public $vOfficialAccount;

    public function __clone()
    {
        $this->vOfficialAccount = clone $this->vOfficialAccount;
    }

    public function __construct()
    {
        $this->vOfficialAccount = new  c_vector (new TOfficialAccount);
    }

    public function get_class_name()
    {
        return "Apollo.TRespOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vOfficialAccount->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vOfficialAccount->read($_in , 0, true);
    }
}

class TReqOfficialAccountMsg extends c_struct
{
    public $officialAccountId;
    public $currentMsgId;
    public $flag;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->currentMsgId = clone $this->currentMsgId;
        $this->flag = clone $this->flag;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->currentMsgId = new  c_string;
        $this->flag = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->currentMsgId->write($_out,1);
        $this->flag->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
        $this->currentMsgId->read($_in , 1, true);
        $this->flag->read($_in , 2, true);
    }
}

class TRespOfficialAccountMsg extends c_struct
{
    public $vOfficialAccountMsg;

    public function __clone()
    {
        $this->vOfficialAccountMsg = clone $this->vOfficialAccountMsg;
    }

    public function __construct()
    {
        $this->vOfficialAccountMsg = new  c_vector (new TOfficialAccountMsg);
    }

    public function get_class_name()
    {
        return "Apollo.TRespOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vOfficialAccountMsg->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vOfficialAccountMsg->read($_in , 0, true);
    }
}

class TReqOfficialAccountMsgContent extends c_struct
{
    public $mId;

    public function __clone()
    {
        $this->mId = clone $this->mId;
    }

    public function __construct()
    {
        $this->mId = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqOfficialAccountMsgContent";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mId->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mId->read($_in , 0, true);
    }
}

class TRespOfficialAccountMsgContent extends c_struct
{
    public $officialAccountMsgContent;

    public function __clone()
    {
        $this->officialAccountMsgContent = clone $this->officialAccountMsgContent;
    }

    public function __construct()
    {
        $this->officialAccountMsgContent = new  TOfficialAccountMsgContent;
    }

    public function get_class_name()
    {
        return "Apollo.TRespOfficialAccountMsgContent";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountMsgContent->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountMsgContent->read($_in , 0, true);
    }
}

class TReqFollowOfficialAccount extends c_struct
{
    public $followOfficialAccountId;
    public $flag;

    public function __clone()
    {
        $this->followOfficialAccountId = clone $this->followOfficialAccountId;
        $this->flag = clone $this->flag;
    }

    public function __construct()
    {
        $this->followOfficialAccountId = new  c_int64;
        $this->flag = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqFollowOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->followOfficialAccountId->write($_out,0);
        $this->flag->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->followOfficialAccountId->read($_in , 0, true);
        $this->flag->read($_in , 1, true);
    }
}

class TRespFollowOfficialAccount extends c_struct
{
    public $result;

    public function __clone()
    {
        $this->result = clone $this->result;
    }

    public function __construct()
    {
        $this->result = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespFollowOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->result->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->result->read($_in , 0, true);
    }
}

class TReqUpdateOfficialAccountMsgStatus extends c_struct
{
    public $mid;
    public $flag;

    public function __clone()
    {
        $this->mid = clone $this->mid;
        $this->flag = clone $this->flag;
    }

    public function __construct()
    {
        $this->mid = new  c_string;
        $this->flag = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqUpdateOfficialAccountMsgStatus";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mid->write($_out,0);
        $this->flag->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mid->read($_in , 0, true);
        $this->flag->read($_in , 1, true);
    }
}

class TRespUpdateOfficialAccountMsgStatus extends c_struct
{
    public $likeCount;
    public $pokeCount;
    public $viewCount;

    public function __clone()
    {
        $this->likeCount = clone $this->likeCount;
        $this->pokeCount = clone $this->pokeCount;
        $this->viewCount = clone $this->viewCount;
    }

    public function __construct()
    {
        $this->likeCount = new  c_int;
        $this->pokeCount = new  c_int;
        $this->viewCount = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespUpdateOfficialAccountMsgStatus";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->likeCount->write($_out,0);
        $this->pokeCount->write($_out,1);
        $this->viewCount->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->likeCount->read($_in , 0, true);
        $this->pokeCount->read($_in , 1, true);
        $this->viewCount->read($_in , 2, true);
    }
}

class TReqWebGetOfficialAccount extends c_struct
{
    public $queryCondition;

    public function __clone()
    {
        $this->queryCondition = clone $this->queryCondition;
    }

    public function __construct()
    {
        $this->queryCondition = new  TQueryOfficialAccountCondition;
    }

    public function get_class_name()
    {
        return "Apollo.TReqWebGetOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->queryCondition->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->queryCondition->read($_in , 0, true);
    }
}

class TRespWebGetOfficialAccount extends c_struct
{
    public $errCode;
    public $errMsg;
    public $officialAccountList;
    public $totalPage;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
        $this->officialAccountList = clone $this->officialAccountList;
        $this->totalPage = clone $this->totalPage;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
        $this->officialAccountList = new  c_vector (new TOfficialAccount);
        $this->totalPage = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespWebGetOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
        $this->officialAccountList->write($_out,2);
        $this->totalPage->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
        $this->officialAccountList->read($_in , 2, false);
        $this->totalPage->read($_in , 3, true);
    }
}

class TReqWebUpdateOfficialAccount extends c_struct
{
    public $officialAccount;

    public function __clone()
    {
        $this->officialAccount = clone $this->officialAccount;
    }

    public function __construct()
    {
        $this->officialAccount = new  TOfficialAccount;
    }

    public function get_class_name()
    {
        return "Apollo.TReqWebUpdateOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccount->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccount->read($_in , 0, true);
    }
}

class TRespWebUpdateOfficialAccount extends c_struct
{
    public $errCode;
    public $errMsg;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespWebUpdateOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
    }
}

class TReqWebUpdateOfficialAccountMsg extends c_struct
{
    public $officialAccountMsg;
    public $officialAccountMsgContent;

    public function __clone()
    {
        $this->officialAccountMsg = clone $this->officialAccountMsg;
        $this->officialAccountMsgContent = clone $this->officialAccountMsgContent;
    }

    public function __construct()
    {
        $this->officialAccountMsg = new  TOfficialAccountMsg;
        $this->officialAccountMsgContent = new  TOfficialAccountMsgContent;
    }

    public function get_class_name()
    {
        return "Apollo.TReqWebUpdateOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountMsg->write($_out,0);
        $this->officialAccountMsgContent->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountMsg->read($_in , 0, true);
        $this->officialAccountMsgContent->read($_in , 1, true);
    }
}

class TReqUpdateOfficialAccountMsgContent extends c_struct
{
    public $officialAccountMsgContent;

    public function __clone()
    {
        $this->officialAccountMsgContent = clone $this->officialAccountMsgContent;
    }

    public function __construct()
    {
        $this->officialAccountMsgContent = new  TOfficialAccountMsgContent;
    }

    public function get_class_name()
    {
        return "Apollo.TReqUpdateOfficialAccountMsgContent";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountMsgContent->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountMsgContent->read($_in , 0, true);
    }
}

class TReqUpdateOfficialAccountPassWord extends c_struct
{
    public $officialAccountId;
    public $oldPassWord;
    public $newPassWord;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->oldPassWord = clone $this->oldPassWord;
        $this->newPassWord = clone $this->newPassWord;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->oldPassWord = new  c_string;
        $this->newPassWord = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqUpdateOfficialAccountPassWord";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->oldPassWord->write($_out,1);
        $this->newPassWord->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
        $this->oldPassWord->read($_in , 1, true);
        $this->newPassWord->read($_in , 2, true);
    }
}

class TRespUpdateOfficialAccountPassWord extends c_struct
{
    public $errCode;
    public $errMsg;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespUpdateOfficialAccountPassWord";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
    }
}

class TReqWebGetOfficialAccountMsg extends c_struct
{
    public $mid;
    public $officialAccountId;

    public function __clone()
    {
        $this->mid = clone $this->mid;
        $this->officialAccountId = clone $this->officialAccountId;
    }

    public function __construct()
    {
        $this->mid = new  c_string;
        $this->officialAccountId = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TReqWebGetOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mid->write($_out,0);
        $this->officialAccountId->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mid->read($_in , 0, true);
        $this->officialAccountId->read($_in , 1, true);
    }
}

class TRespWebGetOfficialAccountMsg extends c_struct
{
    public $officialAccountMsg;
    public $officialAccountMsgContent;

    public function __clone()
    {
        $this->officialAccountMsg = clone $this->officialAccountMsg;
        $this->officialAccountMsgContent = clone $this->officialAccountMsgContent;
    }

    public function __construct()
    {
        $this->officialAccountMsg = new  TOfficialAccountMsg;
        $this->officialAccountMsgContent = new  TOfficialAccountMsgContent;
    }

    public function get_class_name()
    {
        return "Apollo.TRespWebGetOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountMsg->write($_out,0);
        $this->officialAccountMsgContent->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountMsg->read($_in , 0, true);
        $this->officialAccountMsgContent->read($_in , 1, true);
    }
}

class TReqCreateOfficialAccount extends c_struct
{
    public $officialAccount;
    public $phone;
    public $password;
    public $lastIp;
    public $loginTime;

    public function __clone()
    {
        $this->officialAccount = clone $this->officialAccount;
        $this->phone = clone $this->phone;
        $this->password = clone $this->password;
        $this->lastIp = clone $this->lastIp;
        $this->loginTime = clone $this->loginTime;
    }

    public function __construct()
    {
        $this->officialAccount = new  TOfficialAccount;
        $this->phone = new  c_string;
        $this->password = new  c_string;
        $this->lastIp = new  c_string;
        $this->loginTime = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqCreateOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccount->write($_out,0);
        $this->phone->write($_out,1);
        $this->password->write($_out,2);
        $this->lastIp->write($_out,3);
        $this->loginTime->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccount->read($_in , 0, true);
        $this->phone->read($_in , 1, true);
        $this->password->read($_in , 2, true);
        $this->lastIp->read($_in , 3, true);
        $this->loginTime->read($_in , 4, true);
    }
}

class TRespCreateOfficialAccount extends c_struct
{
    public $officialAccountId;
    public $errCode;
    public $errMsg;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespCreateOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->errCode->write($_out,1);
        $this->errMsg->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, false);
        $this->errCode->read($_in , 1, true);
        $this->errMsg->read($_in , 2, false);
    }
}

class TReqCreateOfficialAccountMsg extends c_struct
{
    public $officialAccountMsg;
    public $officialAccountMsgContent;

    public function __clone()
    {
        $this->officialAccountMsg = clone $this->officialAccountMsg;
        $this->officialAccountMsgContent = clone $this->officialAccountMsgContent;
    }

    public function __construct()
    {
        $this->officialAccountMsg = new  TOfficialAccountMsg;
        $this->officialAccountMsgContent = new  TOfficialAccountMsgContent;
    }

    public function get_class_name()
    {
        return "Apollo.TReqCreateOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountMsg->write($_out,0);
        $this->officialAccountMsgContent->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountMsg->read($_in , 0, true);
        $this->officialAccountMsgContent->read($_in , 1, true);
    }
}

class TRespCreateOfficialAccountMsg extends c_struct
{
    public $mid;
    public $numberId;
    public $errCode;
    public $errMsg;

    public function __clone()
    {
        $this->mid = clone $this->mid;
        $this->numberId = clone $this->numberId;
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
    }

    public function __construct()
    {
        $this->mid = new  c_string;
        $this->numberId = new  c_string;
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespCreateOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mid->write($_out,0);
        $this->numberId->write($_out,1);
        $this->errCode->write($_out,2);
        $this->errMsg->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mid->read($_in , 0, true);
        $this->numberId->read($_in , 1, false);
        $this->errCode->read($_in , 2, true);
        $this->errMsg->read($_in , 3, false);
    }
}

class TReqQueryOfficialAccountMsg extends c_struct
{
    public $officialAccountId;
    public $queryCondition;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->queryCondition = clone $this->queryCondition;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->queryCondition = new  TQueryOfficialAccountMsgCondition;
    }

    public function get_class_name()
    {
        return "Apollo.TReqQueryOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->queryCondition->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
        $this->queryCondition->read($_in , 1, true);
    }
}

class TRespQueryOfficialAccountMsg extends c_struct
{
    public $errCode;
    public $errMsg;
    public $msgList;
    public $pageTotal;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
        $this->msgList = clone $this->msgList;
        $this->pageTotal = clone $this->pageTotal;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
        $this->msgList = new  c_vector (new TOfficialAccountMsg);
        $this->pageTotal = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespQueryOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
        $this->msgList->write($_out,2);
        $this->pageTotal->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
        $this->msgList->read($_in , 2, false);
        $this->pageTotal->read($_in , 3, false);
    }
}

class TReqEraseOfficialAccountMsg extends c_struct
{
    public $officialAccountId;
    public $mid;
    public $numberId;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->mid = clone $this->mid;
        $this->numberId = clone $this->numberId;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->mid = new  c_string;
        $this->numberId = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TReqEraseOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->mid->write($_out,1);
        $this->numberId->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
        $this->mid->read($_in , 1, true);
        $this->numberId->read($_in , 2, true);
    }
}

class TRespEraseOfficialAccountMsg extends c_struct
{
    public $errCode;
    public $errMsg;
    public $mid;
    public $officialAccountId;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
        $this->mid = clone $this->mid;
        $this->officialAccountId = clone $this->officialAccountId;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
        $this->mid = new  c_string;
        $this->officialAccountId = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TRespEraseOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
        $this->mid->write($_out,2);
        $this->officialAccountId->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
        $this->mid->read($_in , 2, false);
        $this->officialAccountId->read($_in , 3, false);
    }
}

class TReqPublishOfficialAccountMsg extends c_struct
{
    public $officialAccountId;
    public $mid;
    public $numberId;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->mid = clone $this->mid;
        $this->numberId = clone $this->numberId;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->mid = new  c_string;
        $this->numberId = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TReqPublishOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->mid->write($_out,1);
        $this->numberId->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
        $this->mid->read($_in , 1, true);
        $this->numberId->read($_in , 2, true);
    }
}

class TRespPublishOfficialAccountMsg extends c_struct
{
    public $errCode;
    public $errMsg;
    public $mid;
    public $officialAccountId;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
        $this->mid = clone $this->mid;
        $this->officialAccountId = clone $this->officialAccountId;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
        $this->mid = new  c_string;
        $this->officialAccountId = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TRespPublishOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
        $this->mid->write($_out,2);
        $this->officialAccountId->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
        $this->mid->read($_in , 2, false);
        $this->officialAccountId->read($_in , 3, false);
    }
}

class TReqUnCopyOfficialAccountMsgList extends c_struct
{
    public $officialAccountId;
    public $title;
    public $page;
    public $pageSize;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->title = clone $this->title;
        $this->page = clone $this->page;
        $this->pageSize = clone $this->pageSize;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->title = new  c_string;
        $this->page = new  c_int;
        $this->pageSize = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqUnCopyOfficialAccountMsgList";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->title->write($_out,1);
        $this->page->write($_out,2);
        $this->pageSize->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
        $this->title->read($_in , 1, true);
        $this->page->read($_in , 2, false);
        $this->pageSize->read($_in , 3, false);
    }
}

class TRespUnCopyOfficialAccountMsgList extends c_struct
{
    public $errCode;
    public $errMsg;
    public $officialAccountId;
    public $msgList;
    public $pageTotal;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
        $this->officialAccountId = clone $this->officialAccountId;
        $this->msgList = clone $this->msgList;
        $this->pageTotal = clone $this->pageTotal;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
        $this->officialAccountId = new  c_int64;
        $this->msgList = new  c_vector (new TOfficialAccountMsg);
        $this->pageTotal = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespUnCopyOfficialAccountMsgList";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
        $this->officialAccountId->write($_out,2);
        $this->msgList->write($_out,3);
        $this->pageTotal->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
        $this->officialAccountId->read($_in , 2, false);
        $this->msgList->read($_in , 3, false);
        $this->pageTotal->read($_in , 4, false);
    }
}

class TReqCopyOfficialAccountMsgList extends c_struct
{
    public $officialAccountId;
    public $title;
    public $page;
    public $pageSize;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->title = clone $this->title;
        $this->page = clone $this->page;
        $this->pageSize = clone $this->pageSize;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->title = new  c_string;
        $this->page = new  c_int;
        $this->pageSize = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqCopyOfficialAccountMsgList";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->title->write($_out,1);
        $this->page->write($_out,2);
        $this->pageSize->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
        $this->title->read($_in , 1, true);
        $this->page->read($_in , 2, false);
        $this->pageSize->read($_in , 3, false);
    }
}

class TRespCopyOfficialAccountMsgList extends c_struct
{
    public $errCode;
    public $errMsg;
    public $officialAccountId;
    public $msgList;
    public $copyTimeMap;
    public $pageTotal;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
        $this->officialAccountId = clone $this->officialAccountId;
        $this->msgList = clone $this->msgList;
        $this->copyTimeMap = clone $this->copyTimeMap;
        $this->pageTotal = clone $this->pageTotal;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
        $this->officialAccountId = new  c_int64;
        $this->msgList = new  c_vector (new TOfficialAccountMsg);
        $this->copyTimeMap = new  c_map (new c_string,new c_string);
        $this->pageTotal = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespCopyOfficialAccountMsgList";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
        $this->officialAccountId->write($_out,2);
        $this->msgList->write($_out,3);
        $this->copyTimeMap->write($_out,4);
        $this->pageTotal->write($_out,5);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
        $this->officialAccountId->read($_in , 2, false);
        $this->msgList->read($_in , 3, false);
        $this->copyTimeMap->read($_in , 4, false);
        $this->pageTotal->read($_in , 5, false);
    }
}

class TReqCopyOfficialAccountMsg extends c_struct
{
    public $officialAccountId;
    public $mid;
    public $copyTime;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->mid = clone $this->mid;
        $this->copyTime = clone $this->copyTime;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->mid = new  c_string;
        $this->copyTime = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqCopyOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->mid->write($_out,1);
        $this->copyTime->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
        $this->mid->read($_in , 1, true);
        $this->copyTime->read($_in , 2, true);
    }
}

class TRespCopyOfficialAccountMsg extends c_struct
{
    public $errCode;
    public $errMsg;
    public $officialAccountId;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
        $this->officialAccountId = clone $this->officialAccountId;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
        $this->officialAccountId = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TRespCopyOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
        $this->officialAccountId->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
        $this->officialAccountId->read($_in , 2, false);
    }
}

class TReqCancelCopyOfficialAccountMsg extends c_struct
{
    public $officialAccountId;
    public $mid;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->mid = clone $this->mid;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->mid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqCancelCopyOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->mid->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
        $this->mid->read($_in , 1, true);
    }
}

class TRespCancelCopyOfficialAccountMsg extends c_struct
{
    public $errCode;
    public $errMsg;
    public $officialAccountId;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
        $this->officialAccountId = clone $this->officialAccountId;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
        $this->officialAccountId = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TRespCancelCopyOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
        $this->officialAccountId->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
        $this->officialAccountId->read($_in , 2, false);
    }
}

class TReqCloseOfficialAccount extends c_struct
{
    public $officialAccountId;
    public $reason;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->reason = clone $this->reason;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->reason = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqCloseOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->reason->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
        $this->reason->read($_in , 1, true);
    }
}

class TRespCloseOfficialAccount extends c_struct
{
    public $errCode;
    public $errMsg;
    public $officialAccountId;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
        $this->officialAccountId = clone $this->officialAccountId;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
        $this->officialAccountId = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TRespCloseOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
        $this->officialAccountId->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
        $this->officialAccountId->read($_in , 2, false);
    }
}

class TReqDecapsulationOfficialAccount extends c_struct
{
    public $officialAccountId;
    public $reason;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->reason = clone $this->reason;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->reason = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqDecapsulationOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->reason->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
        $this->reason->read($_in , 1, true);
    }
}

class TRespDecapsulationOfficialAccount extends c_struct
{
    public $officialAccountId;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TRespDecapsulationOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, false);
    }
}

class TReqEraseOfficialAccount extends c_struct
{
    public $officialAccountId;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TReqEraseOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
    }
}

class TRespEraseOfficialAccount extends c_struct
{
    public $errCode;
    public $errMsg;
    public $officialAccountId;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
        $this->officialAccountId = clone $this->officialAccountId;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
        $this->officialAccountId = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TRespEraseOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
        $this->officialAccountId->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
        $this->officialAccountId->read($_in , 2, false);
    }
}

class TReqCloseOfficialAccountMsg extends c_struct
{
    public $mid;
    public $reason;

    public function __clone()
    {
        $this->mid = clone $this->mid;
        $this->reason = clone $this->reason;
    }

    public function __construct()
    {
        $this->mid = new  c_string;
        $this->reason = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqCloseOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mid->write($_out,0);
        $this->reason->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mid->read($_in , 0, true);
        $this->reason->read($_in , 1, true);
    }
}

class TRespCloseOfficialAccountMsg extends c_struct
{
    public $errCode;
    public $errMsg;
    public $mid;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
        $this->mid = clone $this->mid;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
        $this->mid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespCloseOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
        $this->mid->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
        $this->mid->read($_in , 2, false);
    }
}

class TReqOfficialAccountLogin extends c_struct
{
    public $phone;
    public $password;
    public $loginIp;

    public function __clone()
    {
        $this->phone = clone $this->phone;
        $this->password = clone $this->password;
        $this->loginIp = clone $this->loginIp;
    }

    public function __construct()
    {
        $this->phone = new  c_string;
        $this->password = new  c_string;
        $this->loginIp = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqOfficialAccountLogin";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->phone->write($_out,0);
        $this->password->write($_out,1);
        $this->loginIp->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->phone->read($_in , 0, true);
        $this->password->read($_in , 1, true);
        $this->loginIp->read($_in , 2, true);
    }
}

class TRespOfficialAccountLogin extends c_struct
{
    public $errCode;
    public $errMsg;
    public $officialAccount;
    public $lastLoginIp;
    public $loginTime;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
        $this->officialAccount = clone $this->officialAccount;
        $this->lastLoginIp = clone $this->lastLoginIp;
        $this->loginTime = clone $this->loginTime;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
        $this->officialAccount = new  TOfficialAccount;
        $this->lastLoginIp = new  c_string;
        $this->loginTime = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespOfficialAccountLogin";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
        $this->officialAccount->write($_out,2);
        $this->lastLoginIp->write($_out,3);
        $this->loginTime->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
        $this->officialAccount->read($_in , 2, false);
        $this->lastLoginIp->read($_in , 3, false);
        $this->loginTime->read($_in , 4, false);
    }
}

class TReqSetOfficialAccountSendLevel extends c_struct
{
    public $sendLevelMap;

    public function __clone()
    {
        $this->sendLevelMap = clone $this->sendLevelMap;
    }

    public function __construct()
    {
        $this->sendLevelMap = new  c_map (new c_string,new c_int);
    }

    public function get_class_name()
    {
        return "Apollo.TReqSetOfficialAccountSendLevel";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sendLevelMap->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sendLevelMap->read($_in , 0, true);
    }
}

class TReqGetOfficialAccountSendLevel extends c_struct
{
    public $mapSize;

    public function __clone()
    {
        $this->mapSize = clone $this->mapSize;
    }

    public function __construct()
    {
        $this->mapSize = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetOfficialAccountSendLevel";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mapSize->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mapSize->read($_in , 0, false);
    }
}

class TRespGetOfficialAccountSendLevel extends c_struct
{
    public $sendLevelMap;

    public function __clone()
    {
        $this->sendLevelMap = clone $this->sendLevelMap;
    }

    public function __construct()
    {
        $this->sendLevelMap = new  c_map (new c_string,new c_int);
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetOfficialAccountSendLevel";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sendLevelMap->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sendLevelMap->read($_in , 0, true);
    }
}

class TReqResetOfficialAccountPassWord extends c_struct
{
    public $officialAccountId;
    public $newPassWord;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->newPassWord = clone $this->newPassWord;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->newPassWord = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqResetOfficialAccountPassWord";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->newPassWord->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
        $this->newPassWord->read($_in , 1, true);
    }
}

class TRespResetOfficialAccountPassWord extends c_struct
{
    public $errCode;
    public $errMsg;

    public function __clone()
    {
        $this->errCode = clone $this->errCode;
        $this->errMsg = clone $this->errMsg;
    }

    public function __construct()
    {
        $this->errCode = new  c_int;
        $this->errMsg = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespResetOfficialAccountPassWord";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->errCode->write($_out,0);
        $this->errMsg->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->errCode->read($_in , 0, true);
        $this->errMsg->read($_in , 1, false);
    }
}

class TReqOfficialAccountSurplusPublishNumber extends c_struct
{
    public $officialAccountId;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TReqOfficialAccountSurplusPublishNumber";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
    }
}

class TRespOfficialAccountSurplusPublishNumber extends c_struct
{
    public $surplus;

    public function __clone()
    {
        $this->surplus = clone $this->surplus;
    }

    public function __construct()
    {
        $this->surplus = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespOfficialAccountSurplusPublishNumber";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->surplus->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->surplus->read($_in , 0, true);
    }
}

class TReqDecapsulationOfficialAccountMsg extends c_struct
{
    public $mid;
    public $reason;

    public function __clone()
    {
        $this->mid = clone $this->mid;
        $this->reason = clone $this->reason;
    }

    public function __construct()
    {
        $this->mid = new  c_string;
        $this->reason = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqDecapsulationOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mid->write($_out,0);
        $this->reason->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mid->read($_in , 0, true);
        $this->reason->read($_in , 1, true);
    }
}

class TRespDecapsulationOfficialAccountMsg extends c_struct
{
    public $mid;

    public function __clone()
    {
        $this->mid = clone $this->mid;
    }

    public function __construct()
    {
        $this->mid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespDecapsulationOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mid->read($_in , 0, false);
    }
}

class TReqSetDefaultFollowOfficialAccount extends c_struct
{
    public $uid;

    public function __clone()
    {
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSetDefaultFollowOfficialAccount";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
    }
}

class TOfficialAccountMsgBox extends c_struct
{
    public $officialAccountId;
    public $totalNewMsg;
    public $officialAccountMsgList;

    public function __clone()
    {
        $this->officialAccountId = clone $this->officialAccountId;
        $this->totalNewMsg = clone $this->totalNewMsg;
        $this->officialAccountMsgList = clone $this->officialAccountMsgList;
    }

    public function __construct()
    {
        $this->officialAccountId = new  c_int64;
        $this->totalNewMsg = new  c_int;
        $this->officialAccountMsgList = new  c_vector (new TOfficialAccountMsg);
    }

    public function get_class_name()
    {
        return "Apollo.TOfficialAccountMsgBox";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->officialAccountId->write($_out,0);
        $this->totalNewMsg->write($_out,1);
        $this->officialAccountMsgList->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->officialAccountId->read($_in , 0, true);
        $this->totalNewMsg->read($_in , 1, true);
        $this->officialAccountMsgList->read($_in , 2, true);
    }
}

class TReqGetNewFocusOfficialAccountMsg extends c_struct
{
    public $uid;

    public function __clone()
    {
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetNewFocusOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
    }
}

class TRespGetNewFocusOfficialAccountMsg extends c_struct
{
    public $vOfficialAccountMsgBox;

    public function __clone()
    {
        $this->vOfficialAccountMsgBox = clone $this->vOfficialAccountMsgBox;
    }

    public function __construct()
    {
        $this->vOfficialAccountMsgBox = new  c_vector (new TOfficialAccountMsgBox);
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetNewFocusOfficialAccountMsg";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vOfficialAccountMsgBox->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vOfficialAccountMsgBox->read($_in , 0, false);
    }
}

class TReqIsExistOfficialAccountPhone extends c_struct
{
    public $phone;

    public function __clone()
    {
        $this->phone = clone $this->phone;
    }

    public function __construct()
    {
        $this->phone = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqIsExistOfficialAccountPhone";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->phone->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->phone->read($_in , 0, true);
    }
}

class TRespsExistOfficialAccountPhone extends c_struct
{
    public $isExist;
    public $officialAccountId;

    public function __clone()
    {
        $this->isExist = clone $this->isExist;
        $this->officialAccountId = clone $this->officialAccountId;
    }

    public function __construct()
    {
        $this->isExist = new  c_int;
        $this->officialAccountId = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TRespsExistOfficialAccountPhone";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->isExist->write($_out,0);
        $this->officialAccountId->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->isExist->read($_in , 0, true);
        $this->officialAccountId->read($_in , 1, false);
    }
}


?>