<?php

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************


require_once('jce.php');
class TReqSendSystemTeamMessage extends c_struct
{
    public $Message;
    public $type;
    public $userType;
    public $region;

    public function __clone()
    {
        $this->Message = clone $this->Message;
        $this->type = clone $this->type;
        $this->userType = clone $this->userType;
        $this->region = clone $this->region;
    }

    public function __construct()
    {
        $this->Message = new  TNotice;
        $this->type = new  c_int;
        $this->userType = new  c_int;
        $this->region = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSendSystemTeamMessage";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->Message->write($_out,0);
        $this->type->write($_out,1);
        $this->userType->write($_out,2);
        $this->region->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->Message->read($_in , 0, false);
        $this->type->read($_in , 1, false);
        $this->userType->read($_in , 2, false);
        $this->region->read($_in , 3, false);
    }
}

class TReqSendBanBanTeamMessage extends c_struct
{
    public $message;
    public $type;
    public $userType;
    public $region;

    public function __clone()
    {
        $this->message = clone $this->message;
        $this->type = clone $this->type;
        $this->userType = clone $this->userType;
        $this->region = clone $this->region;
    }

    public function __construct()
    {
        $this->message = new  TChatMessage;
        $this->type = new  c_int;
        $this->userType = new  c_int;
        $this->region = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSendBanBanTeamMessage";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->message->write($_out,0);
        $this->type->write($_out,1);
        $this->userType->write($_out,2);
        $this->region->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->message->read($_in , 0, false);
        $this->type->read($_in , 1, false);
        $this->userType->read($_in , 2, false);
        $this->region->read($_in , 3, false);
    }
}

class TReqSendBanBanTeamMessageToSpecialUser extends c_struct
{
    public $message;
    public $type;
    public $vPhoneNumOrUserIdsStr;

    public function __clone()
    {
        $this->message = clone $this->message;
        $this->type = clone $this->type;
        $this->vPhoneNumOrUserIdsStr = clone $this->vPhoneNumOrUserIdsStr;
    }

    public function __construct()
    {
        $this->message = new  TChatMessage;
        $this->type = new  c_int;
        $this->vPhoneNumOrUserIdsStr = new  c_vector (new c_string);
    }

    public function get_class_name()
    {
        return "Apollo.TReqSendBanBanTeamMessageToSpecialUser";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->message->write($_out,0);
        $this->type->write($_out,1);
        $this->vPhoneNumOrUserIdsStr->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->message->read($_in , 0, false);
        $this->type->read($_in , 1, false);
        $this->vPhoneNumOrUserIdsStr->read($_in , 2, false);
    }
}

class TReqSendBanBanDailyPaperMessageToSpecialUser extends c_struct
{
    public $message;
    public $type;
    public $vPhoneNumOrUserIdsStr;

    public function __clone()
    {
        $this->message = clone $this->message;
        $this->type = clone $this->type;
        $this->vPhoneNumOrUserIdsStr = clone $this->vPhoneNumOrUserIdsStr;
    }

    public function __construct()
    {
        $this->message = new  TBanbanDailyPaperMessage;
        $this->type = new  c_int;
        $this->vPhoneNumOrUserIdsStr = new  c_vector (new c_string);
    }

    public function get_class_name()
    {
        return "Apollo.TReqSendBanBanDailyPaperMessageToSpecialUser";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->message->write($_out,0);
        $this->type->write($_out,1);
        $this->vPhoneNumOrUserIdsStr->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->message->read($_in , 0, false);
        $this->type->read($_in , 1, false);
        $this->vPhoneNumOrUserIdsStr->read($_in , 2, false);
    }
}

class TReqSendSystemTeamMessageToSpecialUser extends c_struct
{
    public $Message;
    public $type;
    public $vPhoneNumOrUserIdsStr;

    public function __clone()
    {
        $this->Message = clone $this->Message;
        $this->type = clone $this->type;
        $this->vPhoneNumOrUserIdsStr = clone $this->vPhoneNumOrUserIdsStr;
    }

    public function __construct()
    {
        $this->Message = new  TNotice;
        $this->type = new  c_int;
        $this->vPhoneNumOrUserIdsStr = new  c_vector (new c_string);
    }

    public function get_class_name()
    {
        return "Apollo.TReqSendSystemTeamMessageToSpecialUser";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->Message->write($_out,0);
        $this->type->write($_out,1);
        $this->vPhoneNumOrUserIdsStr->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->Message->read($_in , 0, false);
        $this->type->read($_in , 1, false);
        $this->vPhoneNumOrUserIdsStr->read($_in , 2, false);
    }
}

class TReqSendZoneMessasge extends c_struct
{
    public $message;
    public $type;
    public $userType;
    public $region;

    public function __clone()
    {
        $this->message = clone $this->message;
        $this->type = clone $this->type;
        $this->userType = clone $this->userType;
        $this->region = clone $this->region;
    }

    public function __construct()
    {
        $this->message = new  TZoneMessage;
        $this->type = new  c_int;
        $this->userType = new  c_int;
        $this->region = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSendZoneMessasge";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->message->write($_out,0);
        $this->type->write($_out,1);
        $this->userType->write($_out,2);
        $this->region->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->message->read($_in , 0, true);
        $this->type->read($_in , 1, true);
        $this->userType->read($_in , 2, true);
        $this->region->read($_in , 3, false);
    }
}

class TReqDeviceActived extends c_struct
{
    public $sDeviceID;
    public $sPhonetype;
    public $sChannelID;

    public function __clone()
    {
        $this->sDeviceID = clone $this->sDeviceID;
        $this->sPhonetype = clone $this->sPhonetype;
        $this->sChannelID = clone $this->sChannelID;
    }

    public function __construct()
    {
        $this->sDeviceID = new  c_string;
        $this->sPhonetype = new  c_string;
        $this->sChannelID = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqDeviceActived";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sDeviceID->write($_out,1);
        $this->sPhonetype->write($_out,2);
        $this->sChannelID->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sDeviceID->read($_in , 1, true);
        $this->sPhonetype->read($_in , 2, true);
        $this->sChannelID->read($_in , 3, true);
    }
}

class TRespGetQiniuUpToken extends c_struct
{
    public $token;
    public $url;

    public function __clone()
    {
        $this->token = clone $this->token;
        $this->url = clone $this->url;
    }

    public function __construct()
    {
        $this->token = new  c_string;
        $this->url = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetQiniuUpToken";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->token->write($_out,0);
        $this->url->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->token->read($_in , 0, true);
        $this->url->read($_in , 1, true);
    }
}

class TReqSendSmsLoadAppAddress extends c_struct
{
    public $mobilePhone;

    public function __clone()
    {
        $this->mobilePhone = clone $this->mobilePhone;
    }

    public function __construct()
    {
        $this->mobilePhone = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSendSmsLoadAppAddress";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mobilePhone->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mobilePhone->read($_in , 0, true);
    }
}

class TReqSendSmsInvitation extends c_struct
{
    public $vMobilePhone;
    public $content;

    public function __clone()
    {
        $this->vMobilePhone = clone $this->vMobilePhone;
        $this->content = clone $this->content;
    }

    public function __construct()
    {
        $this->vMobilePhone = new  c_vector (new c_string);
        $this->content = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqSendSmsInvitation";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vMobilePhone->write($_out,0);
        $this->content->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vMobilePhone->read($_in , 0, true);
        $this->content->read($_in , 1, true);
    }
}

class TRespSendSmsInvitation extends c_struct
{
    public $vRegisteredMobilePhones;
    public $vManyTimesInviteMobilePhones;

    public function __clone()
    {
        $this->vRegisteredMobilePhones = clone $this->vRegisteredMobilePhones;
        $this->vManyTimesInviteMobilePhones = clone $this->vManyTimesInviteMobilePhones;
    }

    public function __construct()
    {
        $this->vRegisteredMobilePhones = new  c_vector (new c_string);
        $this->vManyTimesInviteMobilePhones = new  c_vector (new c_string);
    }

    public function get_class_name()
    {
        return "Apollo.TRespSendSmsInvitation";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vRegisteredMobilePhones->write($_out,0);
        $this->vManyTimesInviteMobilePhones->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vRegisteredMobilePhones->read($_in , 0, true);
        $this->vManyTimesInviteMobilePhones->read($_in , 1, true);
    }
}

class TReqGetInvitedClassFeeCard extends c_struct
{
    public $mobilePhone;
    public $sender;
    public $activeid1;
    public $activeid2;
    public $activeid3;

    public function __clone()
    {
        $this->mobilePhone = clone $this->mobilePhone;
        $this->sender = clone $this->sender;
        $this->activeid1 = clone $this->activeid1;
        $this->activeid2 = clone $this->activeid2;
        $this->activeid3 = clone $this->activeid3;
    }

    public function __construct()
    {
        $this->mobilePhone = new  c_string;
        $this->sender = new  c_string;
        $this->activeid1 = new  c_string;
        $this->activeid2 = new  c_string;
        $this->activeid3 = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqGetInvitedClassFeeCard";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mobilePhone->write($_out,0);
        $this->sender->write($_out,1);
        $this->activeid1->write($_out,2);
        $this->activeid2->write($_out,3);
        $this->activeid3->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mobilePhone->read($_in , 0, true);
        $this->sender->read($_in , 1, true);
        $this->activeid1->read($_in , 2, true);
        $this->activeid2->read($_in , 3, true);
        $this->activeid3->read($_in , 4, true);
    }
}

class TRespGetInvitedClassFeeCard extends c_struct
{
    public $money;

    public function __clone()
    {
        $this->money = clone $this->money;
    }

    public function __construct()
    {
        $this->money = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespGetInvitedClassFeeCard";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->money->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->money->read($_in , 0, true);
    }
}

class TReqBatchUidJoinActive extends c_struct
{
    public $vecReqJoinActive;

    public function __clone()
    {
        $this->vecReqJoinActive = clone $this->vecReqJoinActive;
    }

    public function __construct()
    {
        $this->vecReqJoinActive = new  c_vector (new TReqJoinClassFeeCardActivity);
    }

    public function get_class_name()
    {
        return "Apollo.TReqBatchUidJoinActive";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vecReqJoinActive->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vecReqJoinActive->read($_in , 0, true);
    }
}

class TRespBatchUidJoinActive extends c_struct
{
    public $mapRespJoinActive;

    public function __clone()
    {
        $this->mapRespJoinActive = clone $this->mapRespJoinActive;
    }

    public function __construct()
    {
        $this->mapRespJoinActive = new  c_map (new c_string,new TRespJoinClassFeeCardActivity);
    }

    public function get_class_name()
    {
        return "Apollo.TRespBatchUidJoinActive";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mapRespJoinActive->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mapRespJoinActive->read($_in , 0, true);
    }
}

class TTeacherItem extends c_struct
{
    public $name;
    public $mobilephone;

    public function __clone()
    {
        $this->name = clone $this->name;
        $this->mobilephone = clone $this->mobilephone;
    }

    public function __construct()
    {
        $this->name = new  c_string;
        $this->mobilephone = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TTeacherItem";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->name->write($_out,0);
        $this->mobilephone->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->name->read($_in , 0, true);
        $this->mobilephone->read($_in , 1, true);
    }
}

class TImportClassTeacherItem extends c_struct
{
    public $name;
    public $classMaster;
    public $vClassTeacher;

    public function __clone()
    {
        $this->name = clone $this->name;
        $this->classMaster = clone $this->classMaster;
        $this->vClassTeacher = clone $this->vClassTeacher;
    }

    public function __construct()
    {
        $this->name = new  c_string;
        $this->classMaster = new  TTeacherItem;
        $this->vClassTeacher = new  c_vector (new TTeacherItem);
    }

    public function get_class_name()
    {
        return "Apollo.TImportClassTeacherItem";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->name->write($_out,0);
        $this->classMaster->write($_out,1);
        $this->vClassTeacher->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->name->read($_in , 0, true);
        $this->classMaster->read($_in , 1, true);
        $this->vClassTeacher->read($_in , 2, true);
    }
}

class TReqBatchImportClassTeacher extends c_struct
{
    public $sid;
    public $vClassTeacherItem;

    public function __clone()
    {
        $this->sid = clone $this->sid;
        $this->vClassTeacherItem = clone $this->vClassTeacherItem;
    }

    public function __construct()
    {
        $this->sid = new  c_int;
        $this->vClassTeacherItem = new  c_vector (new TImportClassTeacherItem);
    }

    public function get_class_name()
    {
        return "Apollo.TReqBatchImportClassTeacher";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sid->write($_out,0);
        $this->vClassTeacherItem->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sid->read($_in , 0, true);
        $this->vClassTeacherItem->read($_in , 1, true);
    }
}

class TRespBatchImportClassTeacher extends c_struct
{
    public $mapErrXY;

    public function __clone()
    {
        $this->mapErrXY = clone $this->mapErrXY;
    }

    public function __construct()
    {
        $this->mapErrXY = new  c_map (new c_int,new c_vector (new c_int));
    }

    public function get_class_name()
    {
        return "Apollo.TRespBatchImportClassTeacher";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mapErrXY->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mapErrXY->read($_in , 0, true);
    }
}

class TImportClassStudentGuardianItem extends c_struct
{
    public $classcode;
    public $studentName;
    public $mobilePhone;
    public $vMobilePhones;

    public function __clone()
    {
        $this->classcode = clone $this->classcode;
        $this->studentName = clone $this->studentName;
        $this->mobilePhone = clone $this->mobilePhone;
        $this->vMobilePhones = clone $this->vMobilePhones;
    }

    public function __construct()
    {
        $this->classcode = new  c_string;
        $this->studentName = new  c_string;
        $this->mobilePhone = new  c_string;
        $this->vMobilePhones = new  c_vector (new c_string);
    }

    public function get_class_name()
    {
        return "Apollo.TImportClassStudentGuardianItem";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->classcode->write($_out,0);
        $this->studentName->write($_out,1);
        $this->mobilePhone->write($_out,2);
        $this->vMobilePhones->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->classcode->read($_in , 0, true);
        $this->studentName->read($_in , 1, true);
        $this->mobilePhone->read($_in , 2, true);
        $this->vMobilePhones->read($_in , 3, true);
    }
}

class TReqBatchImportClassStudentGuardian extends c_struct
{
    public $vClassStudentItem;

    public function __clone()
    {
        $this->vClassStudentItem = clone $this->vClassStudentItem;
    }

    public function __construct()
    {
        $this->vClassStudentItem = new  c_vector (new TImportClassStudentGuardianItem);
    }

    public function get_class_name()
    {
        return "Apollo.TReqBatchImportClassStudentGuardian";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vClassStudentItem->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vClassStudentItem->read($_in , 0, true);
    }
}

class TRespBatchImportClassStudentGuardian extends c_struct
{
    public $mapErrXY;

    public function __clone()
    {
        $this->mapErrXY = clone $this->mapErrXY;
    }

    public function __construct()
    {
        $this->mapErrXY = new  c_map (new c_int,new c_vector (new c_int));
    }

    public function get_class_name()
    {
        return "Apollo.TRespBatchImportClassStudentGuardian";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mapErrXY->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mapErrXY->read($_in , 0, true);
    }
}

class TReqOmsExitClass extends c_struct
{
    public $flag;
    public $cid;
    public $uid;

    public function __clone()
    {
        $this->flag = clone $this->flag;
        $this->cid = clone $this->cid;
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->flag = new  c_int;
        $this->cid = new  c_int;
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsExitClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->flag->write($_out,0);
        $this->cid->write($_out,1);
        $this->uid->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->flag->read($_in , 0, true);
        $this->cid->read($_in , 1, true);
        $this->uid->read($_in , 2, true);
    }
}

class TReqOmsDelGuardianRelation extends c_struct
{
    public $studentid;
    public $guardianuid;

    public function __clone()
    {
        $this->studentid = clone $this->studentid;
        $this->guardianuid = clone $this->guardianuid;
    }

    public function __construct()
    {
        $this->studentid = new  c_string;
        $this->guardianuid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsDelGuardianRelation";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->studentid->write($_out,0);
        $this->guardianuid->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->studentid->read($_in , 0, true);
        $this->guardianuid->read($_in , 1, true);
    }
}

class TReqOmsResetPwd extends c_struct
{
    public $uid;

    public function __clone()
    {
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsResetPwd";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
    }
}

class TReqOmsSetBlackList extends c_struct
{
    public $uid;
    public $flag;
    public $remark;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->flag = clone $this->flag;
        $this->remark = clone $this->remark;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->flag = new  c_int;
        $this->remark = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsSetBlackList";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->flag->write($_out,1);
        $this->remark->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->flag->read($_in , 1, true);
        $this->remark->read($_in , 2, true);
    }
}

class TAddSingleTeacherClassItem extends c_struct
{
    public $cid;
    public $subject;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->subject = clone $this->subject;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->subject = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TAddSingleTeacherClassItem";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->subject->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->subject->read($_in , 1, true);
    }
}

class TReqOmsAddSingleTeacher extends c_struct
{
    public $mobilePhone;
    public $name;
    public $vItem;

    public function __clone()
    {
        $this->mobilePhone = clone $this->mobilePhone;
        $this->name = clone $this->name;
        $this->vItem = clone $this->vItem;
    }

    public function __construct()
    {
        $this->mobilePhone = new  c_string;
        $this->name = new  c_string;
        $this->vItem = new  c_vector (new TAddSingleTeacherClassItem);
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsAddSingleTeacher";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mobilePhone->write($_out,0);
        $this->name->write($_out,1);
        $this->vItem->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mobilePhone->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->vItem->read($_in , 2, true);
    }
}

class TEditTeacherClassItem extends c_struct
{
    public $cid;
    public $subject;
    public $type;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->subject = clone $this->subject;
        $this->type = clone $this->type;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->subject = new  c_string;
        $this->type = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TEditTeacherClassItem";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->subject->write($_out,1);
        $this->type->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->subject->read($_in , 1, true);
        $this->type->read($_in , 2, true);
    }
}

class TReqOmsEditTeacher extends c_struct
{
    public $uid;
    public $name;
    public $vItem;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->vItem = clone $this->vItem;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->vItem = new  c_vector (new TEditTeacherClassItem);
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsEditTeacher";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->vItem->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->vItem->read($_in , 2, true);
    }
}

class TReqOmsSearchUserLoginStatus extends c_struct
{
    public $vUids;

    public function __clone()
    {
        $this->vUids = clone $this->vUids;
    }

    public function __construct()
    {
        $this->vUids = new  c_vector (new c_string);
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsSearchUserLoginStatus";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vUids->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vUids->read($_in , 0, true);
    }
}

class TRespOmsSearchUserLoginStatus extends c_struct
{
    public $mapUidStatus;

    public function __clone()
    {
        $this->mapUidStatus = clone $this->mapUidStatus;
    }

    public function __construct()
    {
        $this->mapUidStatus = new  c_map (new c_string,new c_int);
    }

    public function get_class_name()
    {
        return "Apollo.TRespOmsSearchUserLoginStatus";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mapUidStatus->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mapUidStatus->read($_in , 0, true);
    }
}

class TSingleStudentParentItem extends c_struct
{
    public $mobile;
    public $name;
    public $role;
    public $main;

    public function __clone()
    {
        $this->mobile = clone $this->mobile;
        $this->name = clone $this->name;
        $this->role = clone $this->role;
        $this->main = clone $this->main;
    }

    public function __construct()
    {
        $this->mobile = new  c_string;
        $this->name = new  c_string;
        $this->role = new  c_string;
        $this->main = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TSingleStudentParentItem";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mobile->write($_out,0);
        $this->name->write($_out,1);
        $this->role->write($_out,2);
        $this->main->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mobile->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->role->read($_in , 2, true);
        $this->main->read($_in , 3, true);
    }
}

class TReqOmsAddSingleStudent extends c_struct
{
    public $name;
    public $vItem;
    public $vCids;

    public function __clone()
    {
        $this->name = clone $this->name;
        $this->vItem = clone $this->vItem;
        $this->vCids = clone $this->vCids;
    }

    public function __construct()
    {
        $this->name = new  c_string;
        $this->vItem = new  c_vector (new TSingleStudentParentItem);
        $this->vCids = new  c_vector (new c_int);
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsAddSingleStudent";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->name->write($_out,0);
        $this->vItem->write($_out,1);
        $this->vCids->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->name->read($_in , 0, true);
        $this->vItem->read($_in , 1, true);
        $this->vCids->read($_in , 2, true);
    }
}

class TReqOmsEditStudent extends c_struct
{
    public $uid;
    public $name;
    public $vItem;
    public $vCids;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->name = clone $this->name;
        $this->vItem = clone $this->vItem;
        $this->vCids = clone $this->vCids;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->name = new  c_string;
        $this->vItem = new  c_vector (new TSingleStudentParentItem);
        $this->vCids = new  c_vector (new c_int);
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsEditStudent";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->name->write($_out,1);
        $this->vItem->write($_out,2);
        $this->vCids->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->vItem->read($_in , 2, true);
        $this->vCids->read($_in , 3, true);
    }
}

class TReqOmsBatchResetPwd extends c_struct
{
    public $vUid;

    public function __clone()
    {
        $this->vUid = clone $this->vUid;
    }

    public function __construct()
    {
        $this->vUid = new  c_vector (new c_string);
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsBatchResetPwd";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vUid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vUid->read($_in , 0, true);
    }
}

class TRespOmsBatchResetPwd extends c_struct
{
    public $vVailUid;

    public function __clone()
    {
        $this->vVailUid = clone $this->vVailUid;
    }

    public function __construct()
    {
        $this->vVailUid = new  c_vector (new c_string);
    }

    public function get_class_name()
    {
        return "Apollo.TRespOmsBatchResetPwd";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vVailUid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vVailUid->read($_in , 0, true);
    }
}

class TReqCreatClass extends c_struct
{
    public $name;
    public $sid;
    public $classtype;
    public $grade;
    public $phone;
    public $mastername;
    public $joinverify;

    public function __clone()
    {
        $this->name = clone $this->name;
        $this->sid = clone $this->sid;
        $this->classtype = clone $this->classtype;
        $this->grade = clone $this->grade;
        $this->phone = clone $this->phone;
        $this->mastername = clone $this->mastername;
        $this->joinverify = clone $this->joinverify;
    }

    public function __construct()
    {
        $this->name = new  c_string;
        $this->sid = new  c_int;
        $this->classtype = new  c_int;
        $this->grade = new  c_int;
        $this->phone = new  c_string;
        $this->mastername = new  c_string;
        $this->joinverify = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqCreatClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->name->write($_out,0);
        $this->sid->write($_out,1);
        $this->classtype->write($_out,2);
        $this->grade->write($_out,3);
        $this->phone->write($_out,4);
        $this->mastername->write($_out,5);
        $this->joinverify->write($_out,6);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->name->read($_in , 0, true);
        $this->sid->read($_in , 1, true);
        $this->classtype->read($_in , 2, true);
        $this->grade->read($_in , 3, true);
        $this->phone->read($_in , 4, true);
        $this->mastername->read($_in , 5, true);
        $this->joinverify->read($_in , 6, true);
    }
}

class TRespCreatClass extends c_struct
{
    public $cid;
    public $classcode;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->classcode = clone $this->classcode;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->classcode = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TRespCreatClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->classcode->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->classcode->read($_in , 1, true);
    }
}

class TReqEditClass extends c_struct
{
    public $classcode;
    public $name;
    public $cid;
    public $sid;
    public $classtype;
    public $grade;
    public $masteruid;
    public $joinverify;

    public function __clone()
    {
        $this->classcode = clone $this->classcode;
        $this->name = clone $this->name;
        $this->cid = clone $this->cid;
        $this->sid = clone $this->sid;
        $this->classtype = clone $this->classtype;
        $this->grade = clone $this->grade;
        $this->masteruid = clone $this->masteruid;
        $this->joinverify = clone $this->joinverify;
    }

    public function __construct()
    {
        $this->classcode = new  c_string;
        $this->name = new  c_string;
        $this->cid = new  c_int;
        $this->sid = new  c_int;
        $this->classtype = new  c_int;
        $this->grade = new  c_int;
        $this->masteruid = new  c_string;
        $this->joinverify = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqEditClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->classcode->write($_out,0);
        $this->name->write($_out,1);
        $this->cid->write($_out,2);
        $this->sid->write($_out,3);
        $this->classtype->write($_out,4);
        $this->grade->write($_out,5);
        $this->masteruid->write($_out,6);
        $this->joinverify->write($_out,7);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->classcode->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->cid->read($_in , 2, true);
        $this->sid->read($_in , 3, true);
        $this->classtype->read($_in , 4, true);
        $this->grade->read($_in , 5, true);
        $this->masteruid->read($_in , 6, true);
        $this->joinverify->read($_in , 7, true);
    }
}

class TReqClassOutOfSchool extends c_struct
{
    public $classcode;
    public $cid;
    public $sid;

    public function __clone()
    {
        $this->classcode = clone $this->classcode;
        $this->cid = clone $this->cid;
        $this->sid = clone $this->sid;
    }

    public function __construct()
    {
        $this->classcode = new  c_string;
        $this->cid = new  c_int;
        $this->sid = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqClassOutOfSchool";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->classcode->write($_out,0);
        $this->cid->write($_out,1);
        $this->sid->write($_out,2);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->classcode->read($_in , 0, true);
        $this->cid->read($_in , 1, true);
        $this->sid->read($_in , 2, true);
    }
}

class TReqOmsCreateSchool extends c_struct
{
    public $name;
    public $aid;
    public $stid;
    public $isjoin;

    public function __clone()
    {
        $this->name = clone $this->name;
        $this->aid = clone $this->aid;
        $this->stid = clone $this->stid;
        $this->isjoin = clone $this->isjoin;
    }

    public function __construct()
    {
        $this->name = new  c_string;
        $this->aid = new  c_int;
        $this->stid = new  c_string;
        $this->isjoin = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsCreateSchool";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->name->write($_out,0);
        $this->aid->write($_out,1);
        $this->stid->write($_out,2);
        $this->isjoin->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->name->read($_in , 0, true);
        $this->aid->read($_in , 1, true);
        $this->stid->read($_in , 2, true);
        $this->isjoin->read($_in , 3, true);
    }
}

class TRespOmsCreateSchool extends c_struct
{
    public $sid;

    public function __clone()
    {
        $this->sid = clone $this->sid;
    }

    public function __construct()
    {
        $this->sid = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespOmsCreateSchool";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sid->read($_in , 0, true);
    }
}

class TReqOmsEditSchool extends c_struct
{
    public $sid;
    public $name;
    public $aid;
    public $stid;
    public $isjoin;

    public function __clone()
    {
        $this->sid = clone $this->sid;
        $this->name = clone $this->name;
        $this->aid = clone $this->aid;
        $this->stid = clone $this->stid;
        $this->isjoin = clone $this->isjoin;
    }

    public function __construct()
    {
        $this->sid = new  c_int;
        $this->name = new  c_string;
        $this->aid = new  c_int;
        $this->stid = new  c_string;
        $this->isjoin = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsEditSchool";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sid->write($_out,0);
        $this->name->write($_out,1);
        $this->aid->write($_out,2);
        $this->stid->write($_out,3);
        $this->isjoin->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sid->read($_in , 0, true);
        $this->name->read($_in , 1, true);
        $this->aid->read($_in , 2, true);
        $this->stid->read($_in , 3, true);
        $this->isjoin->read($_in , 4, true);
    }
}

class TReqOmsToZoneBanBanDailypaper extends c_struct
{
    public $mid;
    public $type;
    public $phoneOruid;
    public $channelId;

    public function __clone()
    {
        $this->mid = clone $this->mid;
        $this->type = clone $this->type;
        $this->phoneOruid = clone $this->phoneOruid;
        $this->channelId = clone $this->channelId;
    }

    public function __construct()
    {
        $this->mid = new  c_string;
        $this->type = new  c_int;
        $this->phoneOruid = new  c_string;
        $this->channelId = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsToZoneBanBanDailypaper";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->mid->write($_out,0);
        $this->type->write($_out,1);
        $this->phoneOruid->write($_out,2);
        $this->channelId->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->mid->read($_in , 0, true);
        $this->type->read($_in , 1, true);
        $this->phoneOruid->read($_in , 2, true);
        $this->channelId->read($_in , 3, true);
    }
}

class TReqOmsDismissClass extends c_struct
{
    public $cid;

    public function __clone()
    {
        $this->cid = clone $this->cid;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqOmsDismissClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
    }
}


?>