<?php

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/UserInfo.jce'
// **********************************************************************


require_once('jce.php');
class TUserInfo extends c_struct
{
    public $uid;
    public $iIdentity;
    public $sMobilePhone;
    public $sName;
    public $iSex;
    public $sPhoto;
    public $sIntro;
    public $sRemark;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->iIdentity = clone $this->iIdentity;
        $this->sMobilePhone = clone $this->sMobilePhone;
        $this->sName = clone $this->sName;
        $this->iSex = clone $this->iSex;
        $this->sPhoto = clone $this->sPhoto;
        $this->sIntro = clone $this->sIntro;
        $this->sRemark = clone $this->sRemark;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->iIdentity = new  c_int;
        $this->sMobilePhone = new  c_string;
        $this->sName = new  c_string;
        $this->iSex = new  c_int;
        $this->sPhoto = new  c_string;
        $this->sIntro = new  c_string;
        $this->sRemark = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TUserInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->iIdentity->write($_out,1);
        $this->sMobilePhone->write($_out,2);
        $this->sName->write($_out,3);
        $this->iSex->write($_out,4);
        $this->sPhoto->write($_out,5);
        $this->sIntro->write($_out,6);
        $this->sRemark->write($_out,7);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->iIdentity->read($_in , 1, true);
        $this->sMobilePhone->read($_in , 2, true);
        $this->sName->read($_in , 3, true);
        $this->iSex->read($_in , 4, true);
        $this->sPhoto->read($_in , 5, true);
        $this->sIntro->read($_in , 6, true);
        $this->sRemark->read($_in , 7, false);
    }
}

class TChildInfo extends c_struct
{
    public $id;
    public $sName;
    public $iSex;
    public $vClass;

    public function __clone()
    {
        $this->id = clone $this->id;
        $this->sName = clone $this->sName;
        $this->iSex = clone $this->iSex;
        $this->vClass = clone $this->vClass;
    }

    public function __construct()
    {
        $this->id = new  c_int;
        $this->sName = new  c_string;
        $this->iSex = new  c_int;
        $this->vClass = new  c_vector (new c_int);
    }

    public function get_class_name()
    {
        return "Apollo.TChildInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->id->write($_out,0);
        $this->sName->write($_out,1);
        $this->iSex->write($_out,2);
        $this->vClass->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->id->read($_in , 0, true);
        $this->sName->read($_in , 1, true);
        $this->iSex->read($_in , 2, true);
        $this->vClass->read($_in , 3, true);
    }
}

class TClassAllInfo extends c_struct
{
    public $cid;
    public $sName;
    public $vTeacherInfos;
    public $vGuardianInfos;
    public $uid;

    public function __clone()
    {
        $this->cid = clone $this->cid;
        $this->sName = clone $this->sName;
        $this->vTeacherInfos = clone $this->vTeacherInfos;
        $this->vGuardianInfos = clone $this->vGuardianInfos;
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->cid = new  c_int;
        $this->sName = new  c_string;
        $this->vTeacherInfos = new  c_vector (new TUserInfo);
        $this->vGuardianInfos = new  c_vector (new TUserInfo);
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TClassAllInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->cid->write($_out,0);
        $this->sName->write($_out,1);
        $this->vTeacherInfos->write($_out,2);
        $this->vGuardianInfos->write($_out,3);
        $this->uid->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->cid->read($_in , 0, true);
        $this->sName->read($_in , 1, true);
        $this->vTeacherInfos->read($_in , 2, false);
        $this->vGuardianInfos->read($_in , 3, false);
        $this->uid->read($_in , 4, false);
    }
}

class TSchoolAllInfo extends c_struct
{
    public $sid;
    public $sName;
    public $vTeacherInfos;
    public $vClassInfos;

    public function __clone()
    {
        $this->sid = clone $this->sid;
        $this->sName = clone $this->sName;
        $this->vTeacherInfos = clone $this->vTeacherInfos;
        $this->vClassInfos = clone $this->vClassInfos;
    }

    public function __construct()
    {
        $this->sid = new  c_int;
        $this->sName = new  c_string;
        $this->vTeacherInfos = new  c_vector (new TUserInfo);
        $this->vClassInfos = new  c_vector (new TClassAllInfo);
    }

    public function get_class_name()
    {
        return "Apollo.TSchoolAllInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->sid->write($_out,0);
        $this->sName->write($_out,1);
        $this->vTeacherInfos->write($_out,2);
        $this->vClassInfos->write($_out,3);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->sid->read($_in , 0, true);
        $this->sName->read($_in , 1, true);
        $this->vTeacherInfos->read($_in , 2, false);
        $this->vClassInfos->read($_in , 3, false);
    }
}

class TReqAddressInfo extends c_struct
{
    public $timestamp;

    public function __clone()
    {
        $this->timestamp = clone $this->timestamp;
    }

    public function __construct()
    {
        $this->timestamp = new  c_int64;
    }

    public function get_class_name()
    {
        return "Apollo.TReqAddressInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->timestamp->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->timestamp->read($_in , 0, true);
    }
}

class TRespAddressInfo extends c_struct
{
    public $status;
    public $timestamp;
    public $personInfo;
    public $vChild;
    public $vSchoolInfos;

    public function __clone()
    {
        $this->status = clone $this->status;
        $this->timestamp = clone $this->timestamp;
        $this->personInfo = clone $this->personInfo;
        $this->vChild = clone $this->vChild;
        $this->vSchoolInfos = clone $this->vSchoolInfos;
    }

    public function __construct()
    {
        $this->status = new  c_int;
        $this->timestamp = new  c_int64;
        $this->personInfo = new  TUserInfo;
        $this->vChild = new  c_vector (new TChildInfo);
        $this->vSchoolInfos = new  c_vector (new TSchoolAllInfo);
    }

    public function get_class_name()
    {
        return "Apollo.TRespAddressInfo";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->status->write($_out,0);
        $this->timestamp->write($_out,1);
        $this->personInfo->write($_out,2);
        $this->vChild->write($_out,3);
        $this->vSchoolInfos->write($_out,4);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->status->read($_in , 0, true);
        $this->timestamp->read($_in , 1, false);
        $this->personInfo->read($_in , 2, false);
        $this->vChild->read($_in , 3, false);
        $this->vSchoolInfos->read($_in , 4, false);
    }
}

class TUserClass extends c_struct
{
    public $uid;
    public $mapClass;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->mapClass = clone $this->mapClass;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->mapClass = new  c_map (new c_int,new c_string);
    }

    public function get_class_name()
    {
        return "Apollo.TUserClass";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->mapClass->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->mapClass->read($_in , 1, true);
    }
}

class TReqUser extends c_struct
{
    public $uid;

    public function __clone()
    {
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqUser";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
    }
}

class TReqFoucsFriend extends c_struct
{
    public $uid;
    public $focusUid;

    public function __clone()
    {
        $this->uid = clone $this->uid;
        $this->focusUid = clone $this->focusUid;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
        $this->focusUid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqFoucsFriend";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
        $this->focusUid->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
        $this->focusUid->read($_in , 1, true);
    }
}

class TRespFoucsFriend extends c_struct
{
    public $result;

    public function __clone()
    {
        $this->result = clone $this->result;
    }

    public function __construct()
    {
        $this->result = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TRespFoucsFriend";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->result->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->result->read($_in , 0, true);
    }
}

class TReqFoucsFriendList extends c_struct
{
    public $uid;

    public function __clone()
    {
        $this->uid = clone $this->uid;
    }

    public function __construct()
    {
        $this->uid = new  c_string;
    }

    public function get_class_name()
    {
        return "Apollo.TReqFoucsFriendList";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->uid->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->uid->read($_in , 0, true);
    }
}

class TRespFoucsFriendList extends c_struct
{
    public $vFriend;

    public function __clone()
    {
        $this->vFriend = clone $this->vFriend;
    }

    public function __construct()
    {
        $this->vFriend = new  c_vector (new c_string);
    }

    public function get_class_name()
    {
        return "Apollo.TRespFoucsFriendList";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->vFriend->write($_out,0);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->vFriend->read($_in , 0, true);
    }
}


?>