<?php

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/word.jce'
// **********************************************************************


require_once('jce.php');
class TReqContainBadWord extends c_struct
{
    public $content;
    public $type;

    public function __clone()
    {
        $this->content = clone $this->content;
        $this->type = clone $this->type;
    }

    public function __construct()
    {
        $this->content = new  c_string;
        $this->type = new  c_int;
    }

    public function get_class_name()
    {
        return "Apollo.TReqContainBadWord";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->content->write($_out,0);
        $this->type->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->content->read($_in , 0, true);
        $this->type->read($_in , 1, false);
    }
}

class TRespContainBadWord extends c_struct
{
    public $b;
    public $containedBadWord;

    public function __clone()
    {
        $this->b = clone $this->b;
        $this->containedBadWord = clone $this->containedBadWord;
    }

    public function __construct()
    {
        $this->b = new  c_int;
        $this->containedBadWord = new  c_vector (new c_string);
    }

    public function get_class_name()
    {
        return "Apollo.TRespContainBadWord";
    }

    public function writeTo(&$_out,$tag)
    {
        $this->b->write($_out,0);
        $this->containedBadWord->write($_out,1);
    }
    public function readFrom(&$_in,$tag,$isRequire = true)
    {
        $this->b->read($_in , 0, true);
        $this->containedBadWord->read($_in , 1, false);
    }
}


?>